package.json, packages/common/package.json, packages/common/src/editors/__tests__/dateEditor.spec.ts, packages/common/src/editors/dateEditor.ts, packages/common/src/interfaces/column.interface.ts, packages/excel-export/package.json, packages/file-export/package.json, packages/vanilla-bundle/package.json, packages/vanilla-bundle/src/salesforce-global-grid-options.ts, packages/web-demo-vanilla-bundle/package.json, packages/web-demo-vanilla-bundle/src/examples/example07.ts, yarn.lock
- we now have 3 available types to use with the Date Editors formatting
1. `type` (data input format),
2. `outputType` (picker display format)
3. `saveOutputType` (save format)
=> fix(editors): add saveOutputType to finally have proper save format

examples/webpack-demo-vanilla-bundle/src/examples/example03.ts, packages/common/src/constants.ts, packages/common/src/editorValidators/integerValidator.ts, packages/common/src/editorValidators/textValidator.ts, packages/common/src/editors/__tests__/autoCompleteEditor.spec.ts, packages/common/src/editors/__tests__/longTextEditor.spec.ts, packages/common/src/editors/__tests__/textEditor.spec.ts, packages/common/src/editors/autoCompleteEditor.ts, packages/common/src/editors/longTextEditor.ts, packages/common/src/editors/textEditor.ts, packages/common/src/interfaces/columnEditor.interface.ts, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-editors.scss
- add a text length counter (currentTextLength/maxLength) to the LongText Editor
- the new `minLenght`, `maxLength` options can be used by the following Editors (autoComplete, longText, text)
- also flip the position of the Cancel/Save buttons, Cancel should be on the left and Save on the right
=> feat(editors): add min/max length options to text editors

examples/webpack-demo-vanilla-bundle/src/examples/example11-modal.html, examples/webpack-demo-vanilla-bundle/src/examples/example11-modal.scss, examples/webpack-demo-vanilla-bundle/src/examples/example11-modal.ts, examples/webpack-demo-vanilla-bundle/src/examples/example11.html, examples/webpack-demo-vanilla-bundle/src/examples/example11.ts, examples/webpack-demo-vanilla-bundle/src/examples/utilities.ts, examples/webpack-demo-vanilla-bundle/src/renderer.ts, packages/common/src/aggregators/__tests__/countAggregator.spec.ts, packages/common/src/aggregators/avgAggregator.ts, packages/common/src/aggregators/cloneAggregator.ts, packages/common/src/aggregators/countAggregator.ts, packages/common/src/aggregators/distinctAggregator.ts, packages/common/src/aggregators/index.ts, packages/common/src/aggregators/minAggregator.ts, packages/common/src/aggregators/sumAggregator.ts, packages/common/src/extensions/__tests__/contextMenuExtension.spec.ts, packages/common/src/extensions/contextMenuExtension.ts, packages/common/src/interfaces/aggregator.interface.ts, packages/common/src/services/__tests__/utilities.spec.ts, packages/common/src/services/utilities.ts, packages/common/src/styles/material-svg-icons.scss, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid-constructor.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, packages/vanilla-bundle/src/services/__tests__/resizer.service.spec.ts, packages/vanilla-bundle/src/services/resizer.service.ts
- add a Mass Update (modal window) functionality via the Grid Menu and/or Context Menu. The Mass Update can be done for the entire dataset (when no rows are selected) or a set of selected rows
=> feat(examples): add mass update feat to Example 11

examples/webpack-demo-vanilla-bundle/package.json, package.json, packages/common/package.json, packages/common/src/editors/__tests__/autoCompleteEditor.spec.ts, packages/common/src/editors/__tests__/selectEditor.spec.ts, packages/common/src/editors/autoCompleteEditor.ts, packages/common/src/editors/checkboxEditor.ts, packages/common/src/editors/dateEditor.ts, packages/common/src/editors/dualInputEditor.ts, packages/common/src/editors/floatEditor.ts, packages/common/src/editors/integerEditor.ts, packages/common/src/editors/longTextEditor.ts, packages/common/src/editors/selectEditor.ts, packages/common/src/editors/sliderEditor.ts, packages/common/src/editors/textEditor.ts, packages/common/src/interfaces/columnEditor.interface.ts, packages/common/src/interfaces/editor.interface.ts, packages/vanilla-bundle/package.json, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, test/cypress/integration/example12.spec.js, yarn.lock
- when using collectionAsync, we'll only get the collection afterward and during the waiting period our editor (DOM element) should be disabled and we will re-enable it only after getting the collection filled.
=> feat(editors): disable editor when collectionAsync, re-enable after

examples/webpack-demo-vanilla-bundle/src/examples/example07.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/interfaces/hideColumnOption.interface.ts, packages/common/src/interfaces/index.ts, packages/common/src/services/__tests__/grid.service.spec.ts, packages/common/src/services/grid.service.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, test/cypress.json
- deprecate previous methods (hideColumn, hideColumnByIndex) since the new methods offer more values with extra options to resize and/or hide from pickers
=> feat(services): add 2x new methods hideColumnById or ..byIds

packages/common/src/formatters/__tests__/alignRightFormatter.spec.ts, packages/common/src/formatters/__tests__/centerFormatter.spec.ts, packages/common/src/formatters/__tests__/treeFormatter.spec.ts, packages/common/src/formatters/__tests__/yesNoFormatter.spec.ts, packages/common/src/formatters/alignRightFormatter.ts, packages/common/src/formatters/centerFormatter.ts, packages/common/src/formatters/formatters.index.ts, packages/common/src/formatters/index.ts
- center already existed but we can add alignCenter to be in line with the other alignRight formatter
- note also that there's no need for alignLeft since everything is aligned to the left in SlickGrid
=> feat(formatters): add AlignRight Formatter & alias AlignCenter=>Center

packages/common/src/services/__tests__/shared.service.spec.ts, packages/common/src/services/excelExport.service.ts, packages/common/src/services/shared.service.ts, packages/common/src/services/textExport.service.ts, packages/composite-editor-component/src/slick-composite-editor.component.spec.ts, packages/composite-editor-component/src/slick-composite-editor.component.ts, packages/excel-export/src/excelExport.service.spec.ts, packages/excel-export/src/excelExport.service.ts, packages/text-export/src/textExport.service.spec.ts, packages/text-export/src/textExport.service.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, packages/vanilla-bundle/src/services/__tests__/textExport.service.spec.ts, packages/vanilla-bundle/src/services/textExport.service.ts, test/containerServiceStub.ts
- also removed the `internalPubSubService` since it's no longer necessary because we can now get it from the container instead
=> feat(core): refactor code using the container service everywhere

examples/webpack-demo-vanilla-bundle/src/examples/example02.ts, packages/common/src/extensions/__tests__/contextMenuExtension.spec.ts, packages/common/src/extensions/__tests__/gridMenuExtension.spec.ts, packages/common/src/extensions/contextMenuExtension.ts, packages/common/src/extensions/gridMenuExtension.ts, packages/common/src/services/excelExport.service.ts, packages/common/src/services/textExport.service.ts, packages/excel-export/src/excelExport.service.ts, packages/text-export/src/textExport.service.ts
ref Angular-Slickgrid [issue #655](https://github.com/ghiscoding/Angular-Slickgrid/issues/655)
=> fix(exports): should be able to change export file name

examples/webpack-demo-vanilla-bundle/src/examples/example07.html, examples/webpack-demo-vanilla-bundle/src/examples/example07.ts, package.json, packages/common/src/filters/__tests__/autoCompleteFilter.spec.ts, packages/common/src/filters/__tests__/selectFilter.spec.ts, packages/common/src/filters/autoCompleteFilter.ts, packages/common/src/filters/selectFilter.ts, packages/common/src/index.ts, packages/common/src/services/__tests__/observers.spec.ts, packages/common/src/services/observers.ts, test/cypress/integration/example07.spec.js
=> feat(filters): add Autocomplete/Select Filters collection observers

packages/common/src/editors/dateEditor.ts, packages/common/src/filter-conditions/executeMappedCondition.ts, packages/common/src/filters/dateRangeFilter.ts, packages/common/src/formatters/formatterUtilities.ts, packages/common/src/services/filter.service.ts, packages/common/src/services/gridState.service.ts, packages/common/src/services/pagination.service.ts, packages/common/src/services/utilities.ts, packages/common/src/sortComparers/dateUtilities.ts, packages/excel-export/src/excelExport.service.ts, packages/vanilla-bundle/src/components/slick-footer.component.ts
- ES6 wants us to use `import moment` but in TypeScript it asks for `import * as moment`, if we do `const moment = moment_['default'] || moment_;` we will get either/or, whichever works first and that works on both side of the fence
=> fix(core): change moment/lodash imports so it works with ES6 module

packages/graphql/src/services/__tests__/graphql.service.spec.ts, packages/graphql/src/services/graphql.service.ts
- ref Angular-Slickgrid issue [#656](https://github.com/ghiscoding/Angular-Slickgrid/pull/656)
* Improved escaping/normalizing search terms for string/text/readonly fields.
* Invalid characters from integer/float/number fields with string search terms are now removed.
* Added support for range filter `..` to function without an upper bound. When for example `2..` is input then `field GE 2` or `field GT 2` is send to the backend, depending on the `defaultFilterRangeOperator`
* Added support for range filter `..` to function without a lower bound. When for example `..2` is input `field LE 2` or `field LT 2` is send, depending on the `defaultFilterRangeOperator`
=> fix(backend): GraphQL queries with input filter

packages/odata/src/services/__tests__/grid-odata.service.spec.ts, packages/odata/src/services/grid-odata.service.ts
- ref Angular-Slickgrid issue [#656](https://github.com/ghiscoding/Angular-Slickgrid/pull/656)
* Improved escaping/normalizing search terms for string/text/readonly fields.
* Invalid characters from integer/float/number fields with string search terms are now removed.
* Added support for range filter `..` to function without an upper bound. When for example `2..` is input then `field GE 2` or `field GT 2` is send to the backend, depending on the `defaultFilterRangeOperator`
* Added support for range filter `..` to function without a lower bound. When for example `..2` is input `field LE 2` or `field LT 2` is send, depending on the `defaultFilterRangeOperator`
=> fix(backend): OData queries with input filter

examples/webpack-demo-vanilla-bundle/src/main.ts, packages/common/src/editors/__tests__/dateEditor.spec.ts, packages/common/src/editors/dateEditor.ts, packages/common/src/filters/__tests__/compoundDateFilter.spec.ts, packages/common/src/filters/__tests__/dateRangeFilter.spec.ts, packages/common/src/filters/compoundDateFilter.ts, packages/common/src/filters/dateRangeFilter.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, test/cypress/screenshots/README.md
- we shouldn't use require(locale) because they all end up being part of the final bundle, it's better to let the user import whichever Flatpickr Locale he wants to use and that will end up being a much smaller bundle with only the locale we really need
=> fix(build): import Flatpickr Locale on demand via regular imports

packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/services/__tests__/filter.service.spec.ts, packages/common/src/services/filter.service.ts
- get the item data context from its parrent object when using row detail
=> fix(plugins): add missing Row Detail filtering code

packages/common/src/extensions/__tests__/columnPickerExtension.spec.ts, packages/common/src/extensions/__tests__/extensionUtility.spec.ts, packages/common/src/extensions/__tests__/gridMenuExtension.spec.ts, packages/common/src/extensions/columnPickerExtension.ts, packages/common/src/extensions/extensionUtility.ts, packages/common/src/extensions/gridMenuExtension.ts, packages/common/src/extensions/headerMenuExtension.ts
- when using ColumnPicker, GridMenu or hiding a column via HeaderMenu, it has to recalculate the frozenColumn index because SlickGrid doesn't take care of that and the previous fix that I implement sometimes become out of sync. This PR simplifies the frozenColumn index position, it will simply update it when the index is different, as simple as that.
=> fix(pinning): recalculate frozen idx properly when column shown changes

packages/excel-export/src/excelExport.service.spec.ts, packages/excel-export/src/excelExport.service.ts
- the custom width was not applied to the correct column, when user had a custom width on column 1 it was applied to column 2. The bug was that getGrouping() always return an array and we should check for its length instead (not just if it exist)
- fixes issue report in Aurelia-Slickgrid https://github.com/ghiscoding/aurelia-slickgrid/issues/511
=> fix(exports): Excel Export custom width applies the width to next column

packages/excel-export/tsconfig.json, packages/graphql/tsconfig.json, packages/odata/tsconfig.json, packages/text-export/tsconfig.json
- the build folder was incorrectly set in a few packages which was overriding the commonjs folder when running dev watch and also breaking Jest when run in parallel which requires commonjs when testing
=> fix(tsc): running dev watch was overriding commonjs folder

packages/common/src/formatters/__tests__/dateEuroFormatter.spec.ts, packages/common/src/formatters/__tests__/dateIsoFormatter.spec.ts, packages/common/src/formatters/__tests__/dateTimeEuroAmPmFormatter.spec.ts, packages/common/src/formatters/__tests__/dateTimeEuroFormatter.spec.ts, packages/common/src/formatters/__tests__/dateTimeIsoAmPmFormatter.spec.ts, packages/common/src/formatters/__tests__/dateTimeIsoFormatter.spec.ts, packages/common/src/formatters/__tests__/dateTimeShortEuroFormatter.spec.ts, packages/common/src/formatters/__tests__/dateTimeShortIsoFormatter.spec.ts, packages/common/src/formatters/__tests__/dateTimeShortUsFormatter.spec.ts, packages/common/src/formatters/__tests__/dateTimeUsAmPmFormatter.spec.ts, packages/common/src/formatters/__tests__/dateTimeUsFormatter.spec.ts, packages/common/src/formatters/__tests__/dateUsFormatter.spec.ts, packages/common/src/sortComparers/dateUtilities.ts
Here's a quick perf date sorting test before & after code change with 50k rows and 8 columns
_note: the date are all in ISO format (yyyy-mm-dd), it might be even bigger differences with non-ISO format_
sorting ASC: 2255.841064453125 ms
sorting DESC: 676.7099609375 ms
sorting ASC: 644.962646484375 ms
sorting DESC: 671.908935546875 ms
sorting ASC: 1981.27978515625 ms
sorting DESC: 692.999755859375 ms
sorting ASC: 673.643798828125 ms
sorting DESC: 670.118896484375 ms
sorting ASC: 1059.22802734375 ms
sorting DESC: 126.10400390625 ms
sorting ASC: 336.77685546875 ms
sorting DESC: 143.007080078125 ms
sorting ASC: 903.991943359375 ms
sorting DESC: 143.51708984375 ms
sorting ASC: 374.537109375 ms
sorting DESC: 117.73583984375 ms
=> feat(perf): improve date sorting speed

packages/common/src/services/__tests__/grid.service.spec.ts, packages/common/src/services/grid.service.ts
- calling `highlightRow(0)` was not highlighting the row when it should
- fixes Aurelia-Slickgrid [issue #527](https://github.com/ghiscoding/aurelia-slickgrid/issues/527)
=> fix(helpers): should be able to highlight first row (0)

examples/webpack-demo-vanilla-bundle/assets/i18n/en.json, examples/webpack-demo-vanilla-bundle/assets/i18n/fr.json, packages/common/src/constants.ts, packages/common/src/filter-conditions/__tests__/stringFilterCondition.spec.ts, packages/common/src/filter-conditions/stringFilterCondition.ts, packages/common/src/filters/__tests__/compoundInputFilter.spec.ts, packages/common/src/filters/compoundInputFilter.ts, packages/common/src/interfaces/locale.interface.ts, test/translateServiceStub.ts
- prefixing a text search with `<>` should be equivalent to "Not Contains" instead of "Not Equal", we can keep the `!=` as "Not Equal" so this way we have both available
=> fix(filters): string <> should be Not Contains instead of Not Equal

package.json, yarn.lock
- upgrading to latest version of Lerna 4.0.0 has a major side effect of NodeJS threads not being disposed after stopping the project
- see Lerna [issue #2841](https://github.com/lerna/lerna/issues/2841)
=> fix(lerna): downgrade Lerna to previous version to fix thread leaking

packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/interfaces/gridSize.interface.ts, packages/vanilla-bundle/src/services/resizer.service.ts
- fixes Aurelia-Slickgrid issue [#534](https://github.com/ghiscoding/aurelia-slickgrid/issues/534)
=> fix(resizer): allow gridHeight/gridWidth to be passed as string

examples/webpack-demo-vanilla-bundle/src/examples/example11.ts, packages/common/src/filters/__tests__/inputFilter.spec.ts, packages/common/src/filters/inputFilter.ts, packages/common/src/services/filter.service.ts
- a use case that we have with the text InputFilter is that if have a filter that includes an operator inside the search text (e.g.: ">=55") and we save the Grid State in Local Storage or anything else and then we reload them as Grid Presets, the operator won't be showing up (it would only show "55" while keeping the Operator hidden but still in play) that is because the FilterService is doing the split (this is an Operator and these are the SearchTerm) and the Grid State only keeps the split, so in that case this PR adds an extra step that if we're using the `setValues()` method, then we're probably using a Grid Preset or an UpdateFilters and we should display the operator as part of the final displayed search string inside the input value
=> feat(filters): display operator into input text filter from Grid Presets

examples/webpack-demo-vanilla-bundle/src/examples/example07.html, examples/webpack-demo-vanilla-bundle/src/examples/example07.ts, packages/common/src/filters/selectFilter.ts, packages/common/src/services/__tests__/filter.service.spec.ts, packages/common/src/services/filter.service.ts, test/cypress/integration/example07.spec.js, test/cypress/integration/example10.spec.js
- our filter conditions assume that values will always be treated as string when filtering but the grid presets was not doing the same assumptions, we can cast both the option value and the search term to string while comparing on what to show as pre-selected items
- also found that `searchTerms` were coming back even after calling `clearFilters` from the Filter Service and they shouldn't come back
=> fix(presets): Multiple Select Filter Grid Presets values should be shown

packages/common/src/services/filter.service.ts
- rolling back this change (in previous PR #288) since Aurelia-Slickgrid filter presets on Client Example was no longer working as expected
=> fix(filters): rollback a change made in PR #288 causing preset issues

packages/common/src/editors/selectEditor.ts, packages/common/src/services/filter.service.ts, packages/common/src/services/gridState.service.ts, packages/common/src/services/pagination.service.ts
- dequal/lite is a bit smaller and since we don't need to compare against Set/Map/Symbol, we can use, it even seems to be a bit faster
- this might help in supporting legacy browser like IE11
- ref issue #297
=> chore(build): use dequal/lite ref issue #297

examples/webpack-demo-vanilla-bundle/src/examples/example08.ts, packages/common/src/services/__tests__/export-utilities.spec.ts, packages/common/src/services/export-utilities.ts, packages/excel-export/src/excelExport.service.spec.ts, packages/excel-export/src/excelExport.service.ts, packages/text-export/src/textExport.service.spec.ts, packages/text-export/src/textExport.service.ts
- read each item metadata to evaluate if the row has any colspan defined and if so then export them accordingly (in Excel we would merge the cells but in regular text export then we would just return empty string)
- with Excel we should merge cells as per the colspan defined
- with Text Export, we should blank any cell not being the first colspan cell
=> fix(exports): grid with colspan should export accordingly

packages/common/src/global-grid-options.ts, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-plugins.scss, packages/vanilla-bundle/src/salesforce-global-grid-options.ts
- by using directly the unicode character we can make it monochrome instead of having a completely different styling between browsers (chrome was gray while firefox was previously colored, now they both look exactly the same monochrome icon)
=> fix(styling): add better search filter magnify glass icon placeholder

examples/webpack-demo-vanilla-bundle/src/examples/example05.html, examples/webpack-demo-vanilla-bundle/src/examples/example05.ts, examples/webpack-demo-vanilla-bundle/src/examples/example06.html, examples/webpack-demo-vanilla-bundle/src/examples/example06.ts, packages/common/src/formatters/__tests__/treeExportFormatter.spec.ts, packages/common/src/formatters/formatters.index.ts, packages/common/src/formatters/index.ts, packages/common/src/formatters/treeExportFormatter.ts, packages/common/src/formatters/treeFormatter.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/excelExportOption.interface.ts, packages/common/src/interfaces/filterCallback.interface.ts, packages/common/src/interfaces/treeDataOption.interface.ts, packages/common/src/services/__tests__/excelExport.service.spec.ts, packages/common/src/services/__tests__/filter.service.spec.ts, packages/common/src/services/__tests__/grid.service.spec.ts, packages/common/src/services/__tests__/sort.service.spec.ts, packages/common/src/services/__tests__/treeData.service.spec.ts, packages/common/src/services/filter.service.ts, packages/common/src/services/grid.service.ts, packages/common/src/services/sort.service.ts, packages/common/src/services/treeData.service.ts, packages/common/src/services/utilities.ts, packages/excel-export/src/excelExport.service.spec.ts, packages/excel-export/src/excelExport.service.ts, packages/excel-export/src/interfaces/excelExportOption.interface.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
1. initial sort not always working
2. tree level property should not be required while providing a `parentId` relation
3. tree data was loading and rendering the grid more than once (at least 1x time before the sort and another time after the tree was built) while it should only be rendered once
- fixes #307
- there was an issue in the demo because the demo also has a filter preset
=> fix(tree): few issues found with Tree Data, fixes #307

packages/common/src/extensions/__tests__/extensionUtility.spec.ts, packages/common/src/extensions/__tests__/gridMenuExtension.spec.ts, packages/common/src/extensions/extensionUtility.ts, packages/common/src/extensions/gridMenuExtension.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/compositeEditorOpenDetailOption.interface.ts, packages/common/src/interfaces/gridMenuLabel.interface.ts, packages/common/src/interfaces/gridMenuOption.interface.ts, packages/common/src/interfaces/index.ts, packages/vanilla-bundle/src/salesforce-global-grid-options.ts
- prior to the change, we couldn't change the label, we would only be able to change the translation key but we couldn't change the text when we're not using translations. This PR provides both way of customizing these labels, via its label and/or with a label translation key
=> feat(addon): provide grid menu labels for all built-in commands

examples/webpack-demo-vanilla-bundle/src/examples/example14.html, examples/webpack-demo-vanilla-bundle/src/examples/example14.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, packages/vanilla-bundle/src/services/resizer.service.ts
- in many cases doing a resize by content only the first time we get data is enough (default is true) and so this flag will handle that scenario or else if the user always want to resize anytime the data changes then the user could disable this new flag
=> feat(resizer): add `resizeByContentOnlyOnFirstLoad` grid option

packages/common/src/extensions/headerMenuExtension.ts, packages/common/src/services/__tests__/sort.service.spec.ts, packages/common/src/services/sort.service.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- with Tree Data only supporting single sort, I found out that we could bypass the single sort by using the header menu
- also found that sort presets with multiple columns were also loading as multiple sort even when the multiColumnSort is disabled and now it's fixed
=> fix(sorting): multi-column sort shouldn't work when option is disabled

examples/webpack-demo-vanilla-bundle/src/examples/example07.ts, packages/common/src/services/gridState.service.ts, packages/common/src/services/sort.service.ts, test/cypress/integration/example07.spec.js
- grid state should only be allowed to change row selection only when Pagination is enabled
- refactor some part of the code to use more optional chaining (?.) syntax for cleaner and smaller code
- move around some of the Cypress tests so that it makes sure that moving rows will keep row selections
=> fix(demo): we should be able to move row(s) and keep selections

.github/workflows/main.yml
- we shouldn't refresh (publish) GitHub demo page on every PR merge, we should instead only redeploy on a release of a new version
=> chore(ci): only deploy GitHub page demo on master & commit is a release

packages/common/src/services/__tests__/pagination.service.spec.ts, packages/common/src/services/pagination.service.ts, test/cypress/integration/example07.spec.js
- previous PR #352 that fixed row selection with row move actually caused a regression with toggling of pagination, when removing Pagination on the fly it will show all items in the grid and there is code in the Grid State Service that will take row selections from all page and reselect them when we toggle to No Pagination, and we need to change our `enablePagination` only after that Grid State Service is finished else we end up missing row selection from all other pages
=> fix(services): toggle pagination was not displaying all row selection

packages/common/src/filter-conditions/__tests__/filterUtilities.spec.ts, packages/common/src/filter-conditions/filterUtilities.ts
- fixes a bug reported in SlickGrid [issue 611](https://github.com/6pac/SlickGrid/issues/611)
with the fix, it now returns the correct rows in the grid, but without the fix this was returning nothing
=> fix(filters): filtering with IN_CONTAINS should also work with spaces

packages/common/src/formatters/__tests__/bsDropdownFormatter.spec.ts, packages/common/src/formatters/bsDropdownFormatter.ts, packages/common/src/formatters/formatters.index.ts, packages/common/src/formatters/index.ts
- add this missing Formatter that was available in Angular-Slickgrid
=> feat(formatters): add Bootstrap Dropdown Formatter

packages/common/src/editors/longTextEditor.ts
- the previous commit to convert jQuery to vanilla JS brought a small issue that was only noticeable when defining a fixed grid height, when that was set and user clicked on the textarea editor it will scrolling to the bottom of the page. This happened because the textarea must be created on the body instead of within the grid and we do a re-positioning of the DOM element to the position of the cell, and the issue was because we focus/select the text content right after it was created (before re-positioning it) and so it was going to the bottom for that reason, we simply need to re-position it BEFORE focusing/selecting the text content
=> fix(editors): longText Editor (textarea) was scrolling to page bottom

packages/common/src/styles/_private.scss, packages/common/src/styles/sass-utilities.scss, packages/common/src/styles/slick.layout.scss
- The latest version of Dart-Sass prints a bunch warnings when the division operator is used. These changes migrate us to the recommended `math.div` function and won't break users that aren't using latest Dart-Sass yet
- use the same technique as Angular UI from shown in this [PR](https://github.com/angular/components/commit/a4043f41f539ed910c80c780e1815f5625282b94) from them
=> chore(styling): add polyfill to latest dart-sass warnings with division

packages/common/src/interfaces/customFooterOption.interface.ts, packages/common/src/styles/slick-component.scss, packages/vanilla-bundle/src/components/__tests__/slick-footer.spec.ts, packages/vanilla-bundle/src/components/slick-footer.component.ts
- add option to provide optional right footer text
- also reworked the Custom Footer DOM tree to remove an extra `<div>` that wasn't necessary, we can just use the same right footer div to show/hide the metrics
=> feat(footer): add option to customize right footer text

packages/common/src/services/gridState.service.ts
- the issue found was with Row Selection when it is not at position 0, the previous code was always assuming that it was at column index 0 but sometime it's not (like our LIG project). Since Row Selection column is added dynamically, this code make sure that when we change dynamically the column position, we will still include the row selection column if it wasn't part of the array provided
=> fix(state): Grid View/Columns dynamically should work w/row selection

packages/common/src/extensions/__tests__/gridMenuExtension.spec.ts, packages/common/src/extensions/gridMenuExtension.ts
- when toggling the filter bar (on and off), the horizontal scroll could become out of sync (the alignment of the filters with the column and its data), this happen because the filters are recreated every time we toggle back the filter bar, for that issue we simply need to move the horizontal scroll back to top-left and that fixes the issue
- this bug was reported in Angular-Slickgrid over Stack Overflow
animated gif of the issue
=> fix(menu): toggle filter bar could be out of sync w/horizontal scroll

examples/webpack-demo-vanilla-bundle/src/examples/example07.ts, packages/common/src/extensions/checkboxSelectorExtension.ts, packages/common/src/extensions/rowMoveManagerExtension.ts, packages/common/src/services/__tests__/extension.service.spec.ts, packages/common/src/services/extension.service.ts
- providing columnIndexPosition should work regardless of when the extension (plugin) is created, basically the previous code was assuming that you will always want the checkbox before the row move plugin but that is not always true and the other way around wasn't possible while this PR fixes it
=> fix(addon): providing columnIndexPosition should always work

packages/common/src/styles/slick-grid.scss
- column header titles that are too long should show the "..." ellipsis and that was not working because it's a bit different with text over multiple lines
=> fix(styling): header title should show ellipsis if too long

packages/excel-export/src/excelExport.service.spec.ts, packages/excel-export/src/excelExport.service.ts, packages/text-export/src/textExport.service.spec.ts, packages/text-export/src/textExport.service.ts
- fixes #390 
- we'll simply totally skip expanded Row Detail panel from the export
=> fix(export): expanded Row Detail shouldn't be exported, fixes #390

examples/webpack-demo-vanilla-bundle/src/examples/example01.html, examples/webpack-demo-vanilla-bundle/src/examples/example01.ts, packages/common/src/services/__tests__/pagination.service.spec.ts, packages/common/src/services/backendUtility.service.ts, packages/common/src/services/pagination.service.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-pagination.component.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, test/cypress/integration/example01.spec.js
- we should be able to toggle Pagination and it should still work as expected after showing it again
- the previous code was disposing of the Pagination Service when hiding (disposing) the Pagination Component but that shouldn't be the case, disposing of the Service should strictly be handled by the Slick Vanilla Bundle
=> fix(pagination): should be able to toggle Pagination

packages/pagination-component/src/slick-pagination.component.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- also fix a small issue found where set pagination presets was being called more than once
- also dispose of slick empty component when disposing of vanilla bundle
=> fix(pagination): able to change translate pubsub event name in component

packages/common/src/styles/_variables.scss, packages/common/src/styles/jquery-ui.scss, packages/common/src/styles/slick-bootstrap.scss, packages/common/src/styles/slick-component.scss, packages/common/src/styles/slick-controls.scss, packages/common/src/styles/slick-default-theme.scss, packages/common/src/styles/slick-editors.scss, packages/common/src/styles/slick-grid.scss, packages/common/src/styles/slick-plugins.scss, packages/common/src/styles/slick-without-bootstrap-min-styling.scss, packages/common/src/styles/slickgrid-theme-material.lite.scss, packages/common/src/styles/slickgrid-theme-material.scss, packages/common/src/styles/slickgrid-theme-salesforce.lite.scss, packages/common/src/styles/slickgrid-theme-salesforce.scss, packages/common/src/styles/ui-autocomplete.scss
- add support to CSS Variables, however keep the original SASS styling and make the CSS Variable as first option with fallback to SASS. This approach will make both CSS Variables and SASS work and CSS Variables will have priority over SASS since SASS is a fallback (2nd argument to each CSS Variable is the fallback)
For example (see new [Wiki](https://github.com/ghiscoding/slickgrid-universal/wiki/SVG-Icons#using-css-variables-instead-of-sass)):
```css
:root {
--slick-header-menu-display: inline-block;
--slick-primary-color-dark: pink;
--slick-header-filter-row-border-bottom: 2px solid pink;
}
```
=> feat(styling): add support for CSS Variables

packages/common/src/services/__tests__/filter.service.spec.ts, packages/common/src/services/filter.service.ts
- also make sure DataView object exist before trying to get items array
- fixes a rare bug reported in Angular-Slickgrid
=> fix(filter): refreshTreeDataFilters only when Tree is enabled

packages/common/src/editors/dateEditor.ts, packages/common/src/filters/compoundDateFilter.ts, packages/common/src/filters/dateRangeFilter.ts
- while implementing this in Angular-Slickgrid, I found that the `currentLocale` ended up being an empty string when the Translater Service doesn't exist (it's optional) and user provides only a single Locale. If nothing is found, then we'll use English (`'en'`)
=> fix(filters): always find locale  even without TranslaterService

packages/binding/src/binding.service.ts, packages/common/src/filters/filterFactory.ts, packages/common/src/services/backendUtility.service.ts, packages/common/src/services/bindingEvent.service.ts, packages/common/src/services/collection.service.ts, packages/common/src/services/extension.service.ts, packages/common/src/services/grid.service.ts, packages/common/src/services/gridEvent.service.ts, packages/common/src/services/gridState.service.ts, packages/common/src/services/groupingAndColspan.service.ts, packages/common/src/services/pagination.service.ts, packages/common/src/services/resizer.service.ts, packages/common/src/services/shared.service.ts, packages/common/src/services/sort.service.ts, packages/common/src/services/treeData.service.ts, packages/custom-footer-component/src/slick-footer.component.ts, packages/empty-warning-component/src/slick-empty-warning.component.ts, packages/event-pub-sub/src/eventPubSub.service.ts, packages/excel-export/src/excelExport.service.ts, packages/graphql/src/services/graphql.service.ts, packages/graphql/src/services/graphqlQueryBuilder.ts, packages/odata/src/services/grid-odata.service.ts, packages/odata/src/services/odataQueryBuilder.service.ts, packages/pagination-component/src/slick-pagination.component.ts, packages/text-export/src/textExport.service.ts
- it was mentioned by a user of Angular-Slickgrid that it would be nice to extend some of the Services and so I decided to make them all extendable by using `protected` instead of `private`
=> feat(services): make everything extendable by using `protected`

packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-bootstrap.scss
- we can safely remove an unnecessary SASS/CSS variable that caused UX breakage, tested in 2 different framework
=> fix(styling): remove css variable on width causing UX problem

packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- the issue was found in our LIG project in the use case that the dataset being replaced by the dataset SETTER, it wasn't refreshing the entire Tree Data in the grid and because of that the UX seemed broken, so the fix is to use `dequal` to compare the dataset with all its properties (not just its length) and if anything changed then we call (force) a full Tree Data refresh
=> fix(tree): same dataset length but w/different prop should refresh Tree

packages/common/src/filter-conditions/stringFilterCondition.ts
- fix an issue was reported in Angular-Slickgrid
=> fix(filters): startsWith/endsWith operator should work

packages/common/src/formatters/__tests__/complexObjectFormatter.spec.ts, packages/common/src/formatters/complexObjectFormatter.ts
fixes a bug that was reported in this Stack Overflow question _[angular slick grid complex object with nullable string
](https://stackoverflow.com/questions/68449432/angular-slick-grid-complex-object-with-nullable-string)_
=> fix(formatters): Complex Object Formatter shouldn't throw with null data

packages/common/src/services/treeData.service.ts
- at some point in time the `exclude` got split and renamed into 2 new types to better identify if it's collapsed or expanded, so the 2 types are: `toggle-expand` and `toggle-collapse` but it seems that TypeScript is not able to identify when the type to exclude is valid or not.
=> fix(tree): exclude the correct type from interface argument

examples/webpack-demo-vanilla-bundle/package.json, examples/webpack-demo-vanilla-bundle/webpack.config.js, package.json, packages/vanilla-bundle/package.json, yarn.lock
- WebPack deprecated `file-loader` and `url-loader` and they simply got replaced by `asset/resource` which needs to be addressed to use latest major version of `css-loader`
=> chore: update few npm packages & address deprecated code with WebPack

packages/common/src/services/resizer.service.ts
- hopefully helps in fixing blank data shown in Angular-Slickgrid
=> refactor: add 10ms delay on 1st resize so it's after grid render

examples/webpack-demo-vanilla-bundle/src/examples/example09.html, examples/webpack-demo-vanilla-bundle/src/examples/example09.ts, examples/webpack-demo-vanilla-bundle/src/examples/example15.html, examples/webpack-demo-vanilla-bundle/src/examples/example15.ts, packages/common/src/services/__tests__/filter.service.spec.ts, packages/common/src/services/filter.service.ts, packages/event-pub-sub/src/eventPubSub.service.spec.ts, packages/event-pub-sub/src/eventPubSub.service.ts, test/cypress/integration/example09.spec.js, test/cypress/integration/example15.spec.js
- this enhancement idea came from this [Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions/337)
- in previous code, if an error happens on the backend server while querying, the search input values would still be changed and we had no clue of the previous value, this PR bring this functionality that if an error occurs it will rollback to previous filter input values.
- this PR also adds the option to prevent bubbling of `onBeforeSearchChange` (a new event) to optionally cancel the search query (the search input value would still be applied because you can't cancel that part but you can call `filterService.resetToPreviousSearchFilters()` to rollback the last search)
- for a demo, you can look at previous PR #463
=> feat(backend): add cancellable onBeforeSearchChange & revert on error

examples/webpack-demo-vanilla-bundle/src/examples/example09.html, examples/webpack-demo-vanilla-bundle/src/examples/example09.ts, examples/webpack-demo-vanilla-bundle/src/examples/example15.html, examples/webpack-demo-vanilla-bundle/src/examples/example15.ts, packages/common/src/services/__tests__/pagination.service.spec.ts, packages/common/src/services/backendUtility.service.ts, packages/common/src/services/pagination.service.ts, packages/pagination-component/src/slick-pagination.component.ts, test/cypress/integration/example09.spec.js, test/cypress/integration/example15.spec.js
- this enhancement idea came from this [Discussion](https://github.com/ghiscoding/slickgrid-universal/discussions/337)
- in previous code, if an error happens on the backend server while querying, the Pagination would still be changed and we had no clue of the previous page number (or page size change), this PR bring this functionality that if an error occurs it will rollback to previous Pagination
- when using a Backend Service, you can prevent the Pagination via `onBeforePaginationChange` while on a local (in-memory) it would be via the DataView `onBeforePagingInfoChanged` event
- for a demo, you can look at previous PR #463 
cancellable event code sample
```ts
// for a local (in-memory) grid, you need to use the DataView event …
```
=> feat(backend): add cancellable Pagination change & revert on error

examples/webpack-demo-vanilla-bundle/src/examples/example09.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/services/__tests__/filter.service.spec.ts, packages/common/src/services/filter.service.ts
- this PR enhanced the previous PR #465 and will reset (rollback) the search input value to its previous value when `onBeforeSearchChange` event is prevented, user can optionally cancel that behavior by disabling the flag `resetFilterSearchValueAfterOnBeforeCancellation`
=> refactor: reset to previous value when event cancelled enhanced #465

packages/common/src/filter-conditions/stringFilterCondition.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/filterConditionOption.interface.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/services/__tests__/utilities.spec.ts, packages/common/src/services/filter.service.ts, packages/common/src/services/utilities.ts
- closes #470
- add a Grid Option to filter text by ignoring any accent by normalizing the text, the option is set to false by default
with the option enabled and searching without accent
also works with accent
=> feat(filters): option to ignore accent while filtering text, closes #470

examples/webpack-demo-vanilla-bundle/src/examples/example03.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- fixes #469
- we should always use DataView `getFilteredItemCount()` since that is really the item count that we want to show in the footer
=> fix(footer): use `getFilteredItemCount` to show correct count, fix #469

packages/common/src/extensions/__tests__/contextMenuExtension.spec.ts, packages/common/src/extensions/__tests__/draggableGroupingExtension.spec.ts, packages/common/src/extensions/contextMenuExtension.ts, packages/common/src/extensions/draggableGroupingExtension.ts, packages/common/src/services/__tests__/gridState.service.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- if we call "Clear Grouping" from the Context Menu, it should automatically clear the Draggable Grouping pre-header, but for that to work we need to pub/sub with a separate event
=> fix(grouping): Draggable Grouping should clear preheader when called

packages/common/src/styles/slick-bootstrap.scss, packages/common/src/styles/slick-component.scss, packages/common/src/styles/slick-controls.scss, packages/common/src/styles/slick-plugins.scss
- fixes #487
- List bullet dots shouldn't show up in any framework (Material-UI was showing the bullet dots for that user)
=> fix(styling): List bullets shouldn't show in any frameworks, fixes #487

packages/common/src/services/__tests__/resizer.service.spec.ts, packages/common/src/services/resizer.service.ts
This fixes the bug/exception mentioned here https://github.com/ghiscoding/Angular-Slickgrid/issues/836 and is "PR 1".
Writing this comment I realize that just the `clearTimeout` would have been enough to fix the exception, but since `bindAutoResizeDataGrid` has this comment `Bind an auto resize trigger on the datagrid, if that is enable then it will resize itself to the available space` I think the added check on `this.gridOptions.enableAutoResize` should be done in `init` and is good.  Also when not using auto resize `resizeGrid` is called from `bindResizeHook` in Vanilla, Angular and Aurelia, so this change shouldn't cause noticeable side effects.
=> fix(resizer): only bind autoresize when enabled

packages/common/src/filter-conditions/__tests__/stringFilterCondition.spec.ts, packages/common/src/filter-conditions/stringFilterCondition.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/filterConditionOption.interface.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/services/filter.service.ts, packages/common/src/sortComparers/__tests__/stringSortComparer.spec.ts, packages/common/src/sortComparers/stringSortComparer.ts
@ghiscoding 
add a Grid Option to sort text by ignoring any accent by normalizing the text, the option is set to false by default
=> feat(sorts): option to ignore accent while sorting text

packages/common/src/filters/compoundSliderFilter.ts, packages/common/src/filters/sliderFilter.ts, packages/common/src/filters/sliderRangeFilter.ts, packages/composite-editor-component/src/compositeEditor.factory.spec.ts, packages/composite-editor-component/src/compositeEditor.factory.ts, packages/composite-editor-component/src/slick-composite-editor.component.ts, packages/custom-footer-component/src/slick-footer.component.ts
- revisit all `document.querySelector` and make sure that we use localized selector instead of querying against the entire DOM tree
=> chore: revisit all querySelector to prefer local element selector

packages/common/src/services/__tests__/sort.service.spec.ts, packages/common/src/services/sort.service.ts
- use case, if we have filtered data in the grid (any filter is applied and some items are filtered) and we then Sort a column, the item count shown in the Footer was showing the entire dataset count instead of the filtered count. This happens because internally the lib will Sort the hierarchical dataset and then overwrite the DataView flat dataset and when it does that it was changing the footer count.
- the fix is simply to force the `onRowCountChanged` event with the correct count so that it updates the Footer count correctly
=> fix(tree): when Tree Data is filtered then Sort, footer count is invalid

examples/webpack-demo-vanilla-bundle/src/examples/example14.html, examples/webpack-demo-vanilla-bundle/src/examples/example14.ts, packages/common/src/interfaces/resizerOption.interface.ts, packages/common/src/services/__tests__/resizer.service.spec.ts, packages/common/src/services/resizer.service.ts
This PR builds on top of https://github.com/ghiscoding/slickgrid-universal/pull/489 and adds the `ResizeObserver` mentioned here https://github.com/ghiscoding/Angular-Slickgrid/issues/836 and is the "PR 3" mentioned there.
This PR adds the `gridOptions.autoResize.resizeDetection`. It's `'window'` by default, when set to `'container'` it observes the set `gridOptions.autoResize.container` element for resize events. When a resize event is observed it resizes the grid with the available height/width based on that container's dimensions.
The `gridOptions.autoResize.container` got changed from `string` to `string | HtmlElement` so that it's possible to provide an element directly which saves me in my project for having to create a unique id. I think this change is backwards compatible. …
=> feat(resizer): add option to detect container resize

packages/common/src/extensions/contextMenuExtension.ts
- since the Context Menu Copy Cell command uses Export Formatter (when defined), it was including extra Tree/Grouping symbols that we don't want to see when doing a Copy Cell, so we should strip these symbols from the start of a string only.
=> fix(context): Copy Cell via Context Menu shouldn't include Tree symbols

packages/common/src/extensions/__tests__/contextMenuExtension.spec.ts, packages/common/src/extensions/__tests__/draggableGroupingExtension.spec.ts, packages/common/src/extensions/contextMenuExtension.ts, packages/common/src/extensions/draggableGroupingExtension.ts
- for our use case, we have an external CollapseAll/ExpandAll button that needs to be flipped even when user is using the toggle from the context menu instead of that external button (in other words, they both have to be in sync)
=> feat(context): expose 3 events for Tree/Grouping clear/collapse/expand

packages/composite-editor-component/src/slick-composite-editor.component.ts
- `append` and `prepend` aren't supported in IE/Salesforce, we can instead use a mixture of `appendChild` which is supported in every browser
=> fix(comp): replace `prepend` not supported in IE/Salesforce

packages/common/src/extensions/contextMenuExtension.ts
- we can just use `opacity: 0` (transparent) instead of `left: -1000px` because on computer with high resolution DPI, it might end up showing the temp element we use to copy and we wouldn't want to show it to the user
=> fix(context): when copying use opacity 0 on temp element

packages/common/src/extensions/draggableGroupingExtension.ts, packages/common/src/services/groupingAndColspan.service.ts, packages/common/src/services/resizer.service.ts, packages/common/src/services/treeData.service.ts
- in order to avoid memory leak, we need to make sure to unsubscribe every subscribed event when disposing (destroying) each services/components
=> fix(subscriptions): unsubscribe every subcriptions on dispose to avoid mem leak

packages/common/src/extensions/__tests__/slickRowMoveManager.spec.ts, packages/common/src/extensions/slickRowMoveManager.ts
- after merging the big controls/plugins PR #555 that rewrote all the plugins, I just found out this simple option got missed
=> fix(plugin): providing usability override via grid option should work

packages/common/src/extensions/__tests__/slickContextMenu.spec.ts, packages/common/src/extensions/slickContextMenu.ts
- when trying the feature on a number, I found out that the numbers weren't copied because previous code was calling string methods on every call but we shouldn't on types number/null/undefined
=> fix(plugin): Copy command from Context Menu should work with numbers

examples/webpack-demo-vanilla-bundle/src/examples/example07.scss, examples/webpack-demo-vanilla-bundle/src/examples/example07.ts, packages/common/src/services/__tests__/filter.service.spec.ts
- after opening Example 7 all filters modal and then going to another Example breaks the multiple-select filter (probably other filters too). The issue was caused by the DOMPurify option of `RETURN_DOM` which was caused by the creation of a second `body` within the current `body`
- also nit pick on code linting/styling
=> fix(demo): latest change with Filter container breaks other demos

packages/binding/src/__tests__/binding.service.spec.ts, packages/binding/src/binding.service.ts, packages/common/src/services/__tests__/bindingEvent.service.spec.ts, packages/common/src/services/bindingEvent.service.ts, packages/event-pub-sub/src/eventPubSub.service.ts
- when detecting binding on an input of type number, it will also parse the value to a number (prior to this PR, it was leaving the value as a string because html input are always string)
- also add possibility to provide multiple elements to the same binding (e,g, it allows to bind 1 or more element(s) to the same listener, a good example is a modal window which often has 2 close buttons, 1 is an "x" and typically also a "Close" button and they should both execute the same action)
=> feat(binding): make Binding Service a little smarter

packages/common/src/services/gridState.service.ts, packages/common/src/services/pagination.service.ts, packages/event-pub-sub/src/eventPubSub.service.spec.ts, packages/event-pub-sub/src/eventPubSub.service.ts, packages/pagination-component/src/slick-pagination.component.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- `subscribe` now returns a Subscription that user can now optionally call `unsubscribe` directly instead of just `unsubscribeAll`
- `unsubscribe` and `unsubscribeAll` should decrease the `subscribedEvents` array (it wasn't before, but now it does decrease its length)
- add Generics to `subscribe<T>` for easier type inference on the `data` argument
- add optional GETTER/SETTER on the `elementSource`
=> feat(services): add extra features to EventPubSub Service

packages/common/src/interfaces/slickEventHandler.interface.ts, packages/event-pub-sub/src/eventPubSub.service.ts, test/mockSlickEvent.ts
- no need to search and remove from array when we're already using array pop to get/remove from array
=> fix(services): unsubscribe shouldn't remove when poping out of array

packages/common/src/extensions/__tests__/slickCellSelectionModel.spec.ts, packages/common/src/extensions/__tests__/slickRowSelectionModel.spec.ts, packages/common/src/extensions/slickCellSelectionModel.ts, packages/common/src/extensions/slickRowSelectionModel.ts
- related to core SlickGrid issue [#661](https://github.com/6pac/SlickGrid/issues/661)
=> fix(selections): selected rows doesn't update when hidden column shown

packages/common/src/styles/slick-plugins.scss
- fixes wrong cursor shown on multiple-select filter when empty, original issue found in Angular-Slickgrid issue [#877](https://github.com/ghiscoding/Angular-Slickgrid/issues/877)
=> fix(styling): add pointer cursor on ms-filter, avoid Bootstrap override

packages/common/src/services/utilities.ts
dear @ghiscoding ,
I verified that after the compilation of the "slickgrid-vanilla-bundle.js" version, the line of code responsible for checking the existence of the "normalize" function is generated with wrong logic causing an error:
Original Code:
Generated code:
Code generated after correction:
=> fix(utilities): check if the normalize function exists

package.json, packages/binding/package.json, packages/common/package.json, packages/composite-editor-component/package.json, packages/custom-footer-component/package.json, packages/custom-tooltip-plugin/package.json, packages/empty-warning-component/package.json, packages/event-pub-sub/package.json, packages/excel-export/package.json, packages/pagination-component/package.json, packages/row-detail-view-plugin/package.json, packages/rxjs-observable/package.json, packages/text-export/package.json, packages/vanilla-bundle/package.json, packages/vanilla-force-bundle/package.json, yarn.lock
- original package does not seem to be updated anymore and `npm-run-all2` was created for that reason to be up to date
=> chore(build): replace `npm-run-all` with `npm-run-all2`

examples/webpack-demo-vanilla-bundle/package.json, examples/webpack-demo-vanilla-bundle/src/examples/example10.ts, examples/webpack-demo-vanilla-bundle/src/examples/example11.ts, examples/webpack-demo-vanilla-bundle/src/examples/example18.ts, examples/webpack-demo-vanilla-bundle/tsconfig.json, package.json, packages/common/package.json, yarn.lock
- previous Faker lib was destroyed by its own author and new recommentation is to use @faker-js/faker which is now driven by the community and is the new official lib
=> chore(deps): replace Faker by official @faker-js/faker

test/cypress.config.ts, test/cypress/e2e/example01.cy.js, test/cypress/e2e/example02.cy.js, test/cypress/e2e/example03.cy.js, test/cypress/e2e/example04.cy.js, test/cypress/e2e/example05.cy.js, test/cypress/e2e/example06.cy.js, test/cypress/e2e/example07.cy.js, test/cypress/e2e/example08.cy.js, test/cypress/e2e/example09.cy.js, test/cypress/e2e/example10.cy.js, test/cypress/e2e/example11.cy.js, test/cypress/e2e/example12.cy.js, test/cypress/e2e/example13.cy.js, test/cypress/e2e/example14.cy.js, test/cypress/e2e/example15.cy.js, test/cypress/e2e/example16.cy.js, test/cypress/e2e/example17.cy.js, test/cypress/e2e/example18.cy.js
- in order to stick with Cypress TypeScript interfaces, we shouldn't add any extra properties to the default options object
=> chore: use only available TS Types and `baseUrl` only

packages/common/src/services/__tests__/container.service.spec.ts, packages/common/src/services/container.service.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, packages/vanilla-bundle/src/services/universalContainer.service.ts
- add dispose method to container service to start with a blank array whenever we route to another page, this is to avoid reusing already disposed services that might still be in the container service
- the issue was found in Angular-Slickgrid and did not seem to show up as a problem in Slickgrid-Universal itself but better play safe and apply the same here
=> fix(composite): selected row count always 0 on mass-selected

packages/utils/src/utils.spec.ts, packages/utils/src/utils.ts
- prior to the fix, an array value was being transformed into an object and the array was lost, issue identified in this [SO](https://stackoverflow.com/questions/62423893/in-slick-grid-inline-edit-i-cant-able-to-get-the-entire-object/73153946#73153946)
=> fix(utils): setDeepValue should accept array properties

packages/common/src/services/__tests__/grid.service.spec.ts, packages/common/src/services/grid.service.ts
- even if an item is not showing in the grid, we should still be able to update it as long as it exists and is found in the DataView
=> fix(service): should be able to update dataview item not shown in grid

packages/utils/src/utils.spec.ts, packages/utils/src/utils.ts
- add full unit test coverage as well
=> fix(utils): able to use setDeepValue on undefined/empty object

packages/common/package.json, pnpm-lock.yaml, test/jest-pretest.ts
- the dependency "jquery-ui-dist" was added for convenience (all-in-one build) but that package wasn't managed by the jQuery team and it is now behind in version number, it is missing a security patch and so this PR removes the use of that external "jquery-ui-dist", we should rely solely on the official package "jquery-ui" which is maintained by the official jQuery team
=> feat(common): remove jquery-ui-dist from deps, use jquery-ui only

packages/common/src/editors/sliderEditor.ts, packages/common/src/filters/__tests__/compoundSliderFilter.spec.ts, packages/common/src/filters/__tests__/sliderFilter.spec.ts, packages/common/src/filters/compoundSliderFilter.ts, packages/common/src/filters/sliderFilter.ts
- whenever the slider value changes, we should update its title property with the new value so that we can see what the value is with the tooltip when hovering the slider
- also watch for extra `mouseup` and `touchend` events (not just `change` event) on the Slider Filter so that it works also properly with mobile devices (note that the Slider Editor already had these events and only the Slider Filters needed them)
=> feat(common): update title prop on change event for Slider Filter/Editor

packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- the output of the Fetch API Promise isn't always an `instanceof Response`, the better way of validating the Fetch resolved output is to check its status to be between 200-300 and also make sure that it has the `.json()` type to be a function
=> fix(bundle): fetch API isn't always an instance of Response

packages/common/src/filters/filterUtilities.ts
- same as previous PR #744, this one was found after
- the output of the Fetch API Promise isn't always an `instanceof Response`, the better way of validating the Fetch resolved output is to check its status to be between 200-300 and also make sure that it has the `.json()` type to be a function
=> fix(filters): fetch API isn't always an instance of Response

packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
Bug: Hidden column does not load edit field with selection options
The "this.slickGrid.getColumns()" method only returns the visible fields of the grid, so if the field that was configured to return a list of elements (collectionAsync) is hidden in the grid, it does not receive the list of elements.
note: Unfortunately after version 1.3.x I am no longer able to perform the "pnpm run build".
=> fix(collectionAsync): hidden column does not load edit field selection

packages/common/src/editors/autoCompleteEditor.ts, packages/common/src/editors/dualInputEditor.ts, packages/common/src/editors/floatEditor.ts, packages/common/src/editors/inputEditor.ts, packages/common/src/editors/integerEditor.ts, packages/common/src/filters/autoCompleteFilter.ts, packages/common/src/filters/compoundInputFilter.ts, packages/common/src/filters/inputFilter.ts
- the use of `role="presentation"` has a downside of disabling Aria which is not ideal, however we can simply use `autocomplete="none"` (the most often used "off" doesn't work in chrome but "none" does)
=> chore(common): use input autocomplete "none" instead of "presentation"

examples/webpack-demo-vanilla-bundle/src/examples/example07.ts, examples/webpack-demo-vanilla-bundle/src/examples/example14.ts, packages/common/src/extensions/__tests__/slickCheckboxSelectColumn.spec.ts, packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts, packages/common/src/extensions/__tests__/slickRowMoveManager.spec.ts, packages/common/src/extensions/slickCheckboxSelectColumn.ts, packages/common/src/extensions/slickRowMoveManager.ts, packages/common/src/services/extension.service.ts, packages/row-detail-view-plugin/src/slickRowDetailView.spec.ts, packages/row-detail-view-plugin/src/slickRowDetailView.ts, packages/vanilla-bundle/package.json, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, pnpm-lock.yaml
- for some extensions/plugins, that is RowDetail, RowMove, RowSelections, are adding extra columns dynamically when the grid is created and are not synced to the user, this PR will help with that but has to be implement differently in each lib wrappers (Angular, Aurelia, ...)
- this is related to this Angular-Slickgrid [issue](https://github.com/ghiscoding/Angular-Slickgrid/issues/1018)
=> feat(plugins): sync column definitions to user after plugin adds column

examples/webpack-demo-vanilla-bundle/src/examples/example14.ts, packages/common/src/constants.ts, packages/common/src/filters/__tests__/sliderRangeFilter.spec.ts, packages/common/src/filters/filters.index.ts, packages/common/src/filters/sliderRangeFilter.ts, packages/common/src/interfaces/index.ts, packages/common/src/interfaces/sliderOption.interface.ts, packages/common/src/styles/_variables-theme-salesforce.scss, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-filters.scss, packages/common/src/styles/slick-plugins.scss, packages/common/src/styles/slick-without-bootstrap-min-styling.scss, test/cypress/e2e/example14.cy.js
- this PR brings back a filter that was remove because of the jQueryUI drop, the filter is now written in pure JS without any external deps
- also created a new SliderOption & SliderRangeOption interfaces for better typing (instead of using filter `params` which was not typed) and deprecate the use of filter `params` (accept both in the meantime)
=> feat(filters): add back Slider Range filter in pure JS

packages/common/src/editors/sliderEditor.ts, packages/common/src/filters/compoundDateFilter.ts, packages/common/src/filters/compoundInputFilter.ts, packages/common/src/filters/compoundSliderFilter.ts, packages/common/src/filters/filterUtilities.ts, packages/common/src/filters/sliderFilter.ts
- instead of duplicating the same operator dropdown list into multiple compound filters, we can move the code into a common util
=> chore: move compound operator list to common area

examples/webpack-demo-vanilla-bundle/src/examples/example16.scss, examples/webpack-demo-vanilla-bundle/src/examples/example16.ts, packages/common/src/interfaces/customTooltipOption.interface.ts, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-plugins.scss, packages/custom-tooltip-plugin/src/__tests__/slickCustomTooltip.spec.ts, packages/custom-tooltip-plugin/src/slickCustomTooltip.ts
- a centered tooltip is sometime useful and wasn't available prior to this PR, this will be especially useful with a Slider Range Filter
=> feat(tooltip): add a new "center" position option to SlickCustomTooltip

packages/common/src/filters/__tests__/compoundSliderFilter.spec.ts, packages/common/src/filters/__tests__/sliderFilter.spec.ts, packages/common/src/filters/__tests__/sliderRangeFilter.spec.ts, packages/common/src/filters/compoundSliderFilter.ts, packages/common/src/filters/sliderFilter.ts, packages/common/src/filters/sliderRangeFilter.ts
- when using SlickCustomTooltip addon and changing slider value, it should update the tooltip value without having to leave the cell and rehovering to see the updated value, it turns out that calling `onHeaderRowMouseEnter` will have that effect as long as we add a small `setTimeout` delay
=> fix(filters): changing Slider value should update tooltip value

packages/common/src/filters/__tests__/compoundDateFilter.spec.ts, packages/common/src/filters/__tests__/compoundInputFilter.spec.ts, packages/common/src/filters/__tests__/compoundSliderFilter.spec.ts, packages/common/src/filters/__tests__/singleSliderFilter.spec.ts, packages/common/src/filters/compoundDateFilter.ts, packages/common/src/filters/compoundInputFilter.ts, packages/common/src/filters/sliderFilter.ts, packages/common/src/interfaces/columnFilter.interface.ts, packages/common/src/interfaces/gridOption.interface.ts
- new option `skipCompoundOperatorFilterWithNullInput` to skip filtering when the Operator is changed before the Compound Filter input value.
- For example, with a CompoundDate Filter it's probably better to wait until we have a date filled before filtering even if we start with the operator.
- Defaults to True **only** for the Compound Date Filter (all other compound filters will still filter right away even when operator is first changed without an input value provided).
[![enter image description here][1]][1]
[1]: https://i.stack.imgur.com/mfTIi.png
=> feat(filters): add grid option `skipCompoundOperatorFilterWithNullInput`

examples/webpack-demo-vanilla-bundle/src/examples/example02.scss, examples/webpack-demo-vanilla-bundle/src/examples/example02.ts, packages/common/src/filters/__tests__/compoundSliderFilter.spec.ts, packages/common/src/filters/__tests__/singleSliderFilter.spec.ts, packages/common/src/filters/__tests__/sliderRangeFilter.spec.ts, packages/common/src/filters/sliderFilter.ts, packages/common/src/interfaces/sliderOption.interface.ts
- add a new CSS variable to provide a 2nd way of configuring the slider track filled color `--slick-slider-filter-filled-track-color: lightblue;`
=> feat(filters): add Slider filter track filled track color

packages/common/src/services/__tests__/filter.service.spec.ts, packages/common/src/services/filter.service.ts
- add event target to the `onBeforeSearchChange` event so that we know if the filter was changed from the filter input or from the operator select dropdown
=> feat(filters): add "target" prop to `onBeforeSearchChange`

examples/webpack-demo-vanilla-bundle/src/examples/example03.ts, examples/webpack-demo-vanilla-bundle/src/examples/example11.ts, examples/webpack-demo-vanilla-bundle/src/examples/example12.ts, examples/webpack-demo-vanilla-bundle/src/examples/example14.ts, packages/common/src/commonEditorFilter/commonEditorFilterUtils.ts, packages/common/src/editors/__tests__/sliderEditor.spec.ts, packages/common/src/editors/autocompleterEditor.ts, packages/common/src/editors/dateEditor.ts, packages/common/src/editors/editorUtilities.ts, packages/common/src/editors/sliderEditor.ts, packages/common/src/filters/__tests__/sliderRangeFilter.spec.ts, packages/common/src/filters/filterUtilities.ts, packages/common/src/filters/sliderFilter.ts, packages/common/src/interfaces/autocompleterOption.interface.ts, packages/common/src/interfaces/columnEditor.interface.ts, packages/common/src/interfaces/flatpickrOption.interface.ts, packages/common/src/interfaces/index.ts, packages/common/src/interfaces/inputOption.interface.ts
- instead of using editor/filter `params` which aren't typed, we'll move most of these options into existing or new interfaces and warn user of deprecations of editorOptions/filterOptions instead of params.
=> feat(common): use editorOptions/filterOptions instead of params

packages/common/src/styles/slick-plugins.scss
- the new refactored code that added Slider Range no longer uses `form-control` CSS class and that created styling issues for some UI framework like Bootstrap in Angular-Slickgrid
=> fix(styling): new Slider not flexed correctly

examples/webpack-demo-vanilla-bundle/src/examples/example16.ts, packages/common/src/editors/__tests__/sliderEditor.spec.ts, packages/common/src/editors/sliderEditor.ts, packages/common/src/filters/__tests__/compoundSliderFilter.spec.ts, packages/common/src/filters/__tests__/singleSliderFilter.spec.ts, packages/common/src/filters/__tests__/sliderRangeFilter.spec.ts, packages/common/src/filters/sliderFilter.ts, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-editors.scss, packages/common/src/styles/slick-plugins.scss, packages/custom-tooltip-plugin/src/__tests__/slickCustomTooltip.spec.ts, packages/custom-tooltip-plugin/src/slickCustomTooltip.ts
- when dragging slider to a new value, it should update the tooltip (when using SlickCustomTooltip plugin) on the fly while dragging, that is whenever the Slider value changes it should reflect the new value instantly on the tooltip as well
=> fix(common): changing Slider value(s) should update Tooltip instantly

packages/common/src/extensions/__tests__/slickDraggableGrouping.spec.ts, packages/common/src/extensions/slickDraggableGrouping.ts
- recent feature to add sort icon in SlickDraggableGrouping did not look at the possibility that the column itself might not be `sortable`, however it has to be considered
for example, below we can see that the "Market" column is not sortable and should not have the sort icon in the preheader group
=> fix(plugin): do not show drag group sort when column is not sortable

packages/common/src/extensions/slickDraggableGrouping.ts, packages/common/src/filters/dateFilter.ts, packages/common/src/services/filter.service.ts
- the only place we should nullify the grid object should be in the lib itself (vanilla-grid-bundle, or other frameworks)
=> chore(core): we shouldn't have to nullify the grid object

packages/common/src/extensions/__tests__/slickDraggableGrouping.spec.ts, packages/common/src/extensions/slickDraggableGrouping.ts, packages/common/src/interfaces/draggableGrouping.interface.ts
- after rewriting all SlickGrid plugins into standalone  Slickgrid-Universal extensions (in commit  8e6eb488), it seems that the `onGroupChanged` function callback was forgotten and the new code was never executing it when it was defined as a function callback by the user, this PR fixes that. Note that the `onGroupChanged` can be both a function callback (defined by the user in its grid option) and a Slick Event that has notify/subscribe
=> fix(addons): onGroupChanged callback should be executed with Draggable

package.json, packages/common/src/services/__tests__/grid.service.spec.ts, packages/common/src/services/grid.service.ts
- the previous code called `clearPinning()` which also called a 2nd `setColumns` but with a different set of columns which was conflicting with the first set
=> fix(core): grid service `resetGrid` method wasn't always resetting

packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/sortComparers/dateUtilities.ts
- fixes bug mentioned in this Stack Overflow [question](https://stackoverflow.com/questions/74657131/slickgrid-header-menu-sorting-is-not-working-properly), opened an Angular-Slickgrid [issue](https://github.com/ghiscoding/Angular-Slickgrid/issues/1052) for this as well.
- for example if we had 10 lines with null values and 90 lines of valid dates, and we were sorting ascending multiple times, the dates were sorted correctly but the 10 null date lines were constantly being shuffled
Note that the new code is taking slightly more time to execute because we now create a temp dates to sort nullish values, however it seems negligeable 1240ms vs 1125ms on first sort of 50k unsorted rows (so about 100-150ms longer).
=> fix(common): calling Date Sorting multiple times was shuffling other lines

packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- when creating a grid without enabling the filtering and we use Pagination, the Grid Menu might show options related to filtering and the reason is because internally we have to enable filtering to create the Pagination and then disable back the filtering option and we do that only once, but in some cases it might do this check a little too early before the SharedService is available and that would cause the filtering option to remain half enabled, we should simply wait for SharedService to be available before doing this swap
=> fix: Grid Menu filtering options should be removed when option disabled

packages/common/src/enums/fieldType.enum.ts, packages/excel-export/package.json, packages/excel-export/src/excelExport.service.spec.ts, packages/excel-export/src/excelExport.service.ts, packages/excel-export/src/excelUtils.spec.ts, packages/excel-export/src/excelUtils.ts, pnpm-lock.yaml
- when using `Formatters.decimal`, the Excel export should automatically create custom format depending on decimal formatter options provided
- extending PR #843
=> fix(export): create custom Excel cell format with Formatters.decimal

examples/webpack-demo-vanilla-bundle/src/examples/example02.html, examples/webpack-demo-vanilla-bundle/src/examples/example02.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/column.interface.ts, packages/common/src/interfaces/excelExportOption.interface.ts, packages/excel-export/src/excelExport.service.spec.ts, packages/excel-export/src/excelExport.service.ts
I added this flag when I started the work on the auto-detection of Excel format but I realize that it should probably be enabled at all time, so no need for a flag
=> chore(exports): remove recent unnecessary exportWithExcelFormat flag

packages/common/src/extensions/slickCellRangeSelector.ts
- fixes issue reported in SlickGrid [issue 714](https://github.com/6pac/SlickGrid/issues/714)
=> fix(common): cell selection in Firefox not working

packages/common/src/styles/slick-bootstrap.scss
- we shouldn't change any styling that are not explicitely under CSS classes related to Slickgrid since these overrides user's styling which is unexpected and it is also hard for the user to override
=> fix(styling): do not remove ul>li bullet on html root, fixes #868

.vscode/launch.json, package.json, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/column.interface.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/services/__tests__/filter.service.spec.ts, packages/common/src/services/filter.service.ts, packages/graphql/src/services/__tests__/graphql.service.spec.ts, packages/graphql/src/services/graphql.service.ts, packages/odata/src/services/__tests__/grid-odata.service.spec.ts, packages/odata/src/services/grid-odata.service.ts, pnpm-lock.yaml
- Slickgrid-Universal is by default parsing some special characters (`<`, `>`, `=`, `*`) when found in filter input value but in some rare occasion the user might have data that includes these special chars and might want to disable the parsing, this PR provide a new flag `autoParseInputFilterOperator` that will disable parsing when set to `false` and search the value as it is
- this option is available from both the GridOption and the Column, the latter will always have precedence
- ref Stack Overflow [In angular slickgrid, the records with special characters "<" , "=" are not getting filtered](https://stackoverflow.com/questions/75155658/in-angular-slickgrid-the-records-with-special-characters-are-not-gett)
=> fix(filters): provide flag to disable special chars input filter parsing

packages/common/src/services/gridEvent.service.ts, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-plugins.scss, packages/row-detail-view-plugin/package.json, packages/row-detail-view-plugin/src/slickRowDetailView.spec.ts, packages/row-detail-view-plugin/src/slickRowDetailView.ts, packages/utils/src/utils.spec.ts, packages/utils/src/utils.ts, pnpm-lock.yaml
- this issue was brought up in a SO question that is now deleted, the main problem was that Row Detail was never tested with editable grids and was throwing an error
- while testing with editable grid, we should also collapse all row detail when clicking on an editable cell to avoid UI issues with active cell which was showing up over the row detail panel and causing UI weirdness
- also found that the SlickRowDetail wasn't always merging its internal options with a default set of options, it was only using the options defined by the user and omitting any default values which caused problem and that was caught with `useRowClick: false` that ended up not working as expected
=> fix(RowDetail): Row Detail extension should work with editable grid

packages/common/src/editors/autocompleterEditor.ts, packages/common/src/filters/autocompleterFilter.ts
- by default the Kraaden Autocomplete lib sets the drop container width to be the same as the input width but that isn't a good UX in a datagrid so we need to unset the width and let pure CSS use auto width
- ref https://github.com/kraaden/autocomplete/issues/102
=> fix(autocomplete): Autocomplete drop container should take content width

examples/webpack-demo-vanilla-bundle/package.json, examples/webpack-demo-vanilla-bundle/webpack.config.js, pnpm-lock.yaml
- addresses PR #894 which Renovate tried to upgrade to v3 but failed because it requires some small code changes as per breaking changes
=> chore(demo): upgrade to WebPack ESBuild-Loader v3.0

examples/webpack-demo-vanilla-bundle/src/examples/example12.ts, examples/webpack-demo-vanilla-bundle/src/examples/example16.ts, package.json, packages/common/src/formatters/__tests__/formatterUtilities.spec.ts, packages/common/src/formatters/formatterUtilities.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/columnExcelExportOption.interface.ts, packages/excel-export/src/excelExport.service.spec.ts, packages/excel-export/src/excelExport.service.ts, packages/excel-export/src/excelUtils.spec.ts, packages/excel-export/src/excelUtils.ts, packages/vanilla-force-bundle/src/salesforce-global-grid-options.ts, test/cypress/e2e/example16.cy.ts
- this PR will now auto-detect numbers even when using Formatters.multiple, it wasn't at all prior to this PR
- also improve parsing of numbers with formatter options, user might provide formatter options like `decimalSeparator: ','` and/or `thousandSeparator: ' '` and the Excel export should be able to parse this number even with these formatter options (it wasn't able to parse at all prior to this PR and was previously returning the string as is). It will now parse the number and make it a cell number in Excel but will also add a custom format to show the same way in Excel and the UI
- also change `sanitizeDataExport` defaults to `true` to avoid exporting html tags, most users wouldn't want to see html tags in their exports anyway
=> fix(export): Excel export auto-detect number with Formatters.multiple

examples/webpack-demo-vanilla-bundle/src/examples/example13.ts, package.json, packages/common/package.json, packages/common/src/services/__tests__/gridEvent.service.spec.ts, packages/common/src/services/gridEvent.service.ts, packages/vanilla-bundle/package.json, packages/vanilla-force-bundle/webpack.config.js, pnpm-lock.yaml, test/cypress/e2e/example11.cy.ts, test/cypress/e2e/example12.cy.ts
- when using Excel copy buffer to copy cell ranges, the cell loses its focus after the copy execution, so we need to reapply the focus on the active cell that the user clicked
=> fix(common): Excel copy cell ranges shouldn't lose its cell focus

packages/common/src/editors/selectEditor.ts, packages/vanilla-force-bundle/package.json
- the error came from ESbuild when trying to bundle the lib, the warning is the following
```sh
[WARNING] Comparison using the "===" operator here is always false [equals-new-object]
```
=> fix(editor): comparing select editor value against `['']` isn't valid

packages/custom-tooltip-plugin/src/__tests__/slickCustomTooltip.spec.ts, packages/custom-tooltip-plugin/src/slickCustomTooltip.ts
- the feature of that takes the cell content and displays a tooltip when the cell isn't showing the entire text should only be displayed on a slick-cell type, it shouldn't do this action when hovering on a slick header. This was an issue that was found when hovering a select dropdown that ended up showing up the entire list of select options values instead of the selected values
=> fix(tooltip): only create tooltip on header row/column from title attr

package.json, packages/common/src/editors/__tests__/autocompleterEditor.spec.ts, packages/common/src/editors/__tests__/checkboxEditor.spec.ts, packages/common/src/editors/__tests__/dateEditor.spec.ts, packages/common/src/editors/__tests__/dualInputEditor.spec.ts, packages/common/src/editors/__tests__/floatEditor.spec.ts, packages/common/src/editors/__tests__/inputEditor.spec.ts, packages/common/src/editors/__tests__/inputPasswordEditor.spec.ts, packages/common/src/editors/__tests__/integerEditor.spec.ts, packages/common/src/editors/__tests__/longTextEditor.spec.ts, packages/common/src/editors/__tests__/multipleSelectEditor.spec.ts, packages/common/src/editors/__tests__/selectEditor.spec.ts, packages/common/src/editors/__tests__/singleSelectEditor.spec.ts, packages/common/src/editors/__tests__/sliderEditor.spec.ts, packages/common/src/editors/autocompleterEditor.ts, packages/common/src/editors/checkboxEditor.ts, packages/common/src/editors/dateEditor.ts, packages/common/src/editors/dualInputEditor.ts, packages/common/src/editors/inputEditor.ts, packages/common/src/editors/longTextEditor.ts, packages/common/src/editors/selectEditor.ts, packages/common/src/editors/sliderEditor.ts, packages/common/src/extensions/__tests__/slickCellExcelCopyManager.spec.ts, packages/common/src/extensions/slickCellExternalCopyManager.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/services/__tests__/gridEvent.service.spec.ts, packages/common/src/services/gridEvent.service.ts, packages/composite-editor-component/src/compositeEditor.factory.spec.ts
- fixes a regression caused by previous PR #901 and identified in Angular-Slickgrid issue [1103](https://github.com/ghiscoding/Angular-Slickgrid/issues/1103), the previous PR #901 was put in place to fix cell external copy in a bug reported in Slickgrid-React issue [36](https://github.com/ghiscoding/slickgrid-react/issues/36)
- this bug actually came from a very old patch that was put in place via `suppressActiveCellChangeOnEdit: true` in SlickGrid [PR 243](https://github.com/6pac/SlickGrid/pull/243) and this flag was to avoid trigger an event when the active cell changes, this event was being listened by SlickCellSelectionModel and when triggered was then sending another event with the cell ranges that changed, which then sent another event onSelectedRangesChanged which was itself …
=> fix: Edit cell mouseout should save & excel copy buffer should still work

packages/common/src/extensions/slickDraggableGrouping.ts
- get latest reorderedColumns on each end event handler
=> fix: draggable grouping shouldn't throw error when dynamically changing columns

packages/common/src/extensions/__tests__/slickCheckboxSelectColumn.spec.ts, packages/common/src/extensions/__tests__/slickRowMoveManager.spec.ts, packages/common/src/extensions/slickCheckboxSelectColumn.ts, packages/common/src/extensions/slickRowMoveManager.ts, packages/row-detail-view-plugin/src/slickRowDetailView.spec.ts, packages/row-detail-view-plugin/src/slickRowDetailView.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- this PR fixes 2 issues
1. when Row Detail & Row Selection are used together, an extra checkbox appears in the filter section of the RowDetail column when it shouldn't, this was caused by both extensions using the same `field` name "sel" causing duplicate checkboxes (see print screen)
2. there are 3 dynamically created columns (RowMove, RowSelection & RowDetail) and all 3 should be auto-inserted when columns presets are used
=> fix(presets): dynamic columns should be auto-inserted with Grid Presets

package.json, pnpm-lock.yaml
- the breaking change in Lerna-Lite is that `publish` and `version` are now optional, however `version` is a strict dependency of `publish` so just installing the latter is enough
=> chore(deps): add missing Lerna-Lite publish as new requirement

packages/common/src/extensions/__tests__/slickDraggableGrouping.spec.ts, packages/common/src/extensions/slickDraggableGrouping.ts, packages/common/src/styles/slick-plugins.scss
- when dragging a column to a new group, it should hide all existing grouped elements
- also fixes an issue were the dropzone hovering wasn't working as it should
=> fix: SlickDraggableGrouping should hide group elms when dragging

packages/common/src/editors/floatEditor.ts, packages/common/src/editors/integerEditor.ts, packages/common/src/filters/inputFilter.ts, packages/common/src/filters/inputMaskFilter.ts
- this removes 3 out of 20 warnings (17 remainings), all the other ones are coming from SlickGrid core lib and will be fixed there
=> fix(core): set `wheel` event listener to passive for better perf

examples/vite-demo-vanilla-bundle/src/examples/example03.ts, packages/common/src/formatters/formatterUtilities.ts, packages/excel-export/src/excelUtils.spec.ts, packages/excel-export/src/excelUtils.ts
- fixes an issue identified in Angular-Slickgrid where the negative numbers were seeing negative numbers turned to positive numbers (ref: https://github.com/ghiscoding/Angular-Slickgrid/issues/1135)
- also improve perf of `exportWithFormatterWhenDefined` by analyzing `exportWithFormatter` only once instead of twice
=> fix(export): fix negative number exports to Excel

examples/vite-demo-vanilla-bundle/package.json, packages/common/build-watch.mjs
- when using Lerna-Lite watch, our `dev:watch` script in the root is already calling the `dev` script when a file changes so that tsc rebuilds all TS files, but we also had a `dev` script for Vite as well, so this was causing the Vite server to open another thread with a different port every time a file changed which wasn't correct. We don't need the `dev` script in the demo since we use `vite:dev` to start Vite and we only need to start it one time only
=> chore: do not recall Vite dev script since root package already does it

examples/vite-demo-vanilla-bundle/package.json, packages/common/package.json, packages/common/src/filters/selectFilter.ts, packages/common/src/services/domUtilities.ts, pnpm-lock.yaml
- fix a regression bug introduced by PR #976 when migrating from ms-select to ms-select-vanilla, the text should be encode only when `renderHtmlEnabled` is enabled and not encoded when it's the flag is disabled, basically the html encode was set on the wrong condition
- in other words and in a shorter description, we should only html encode text when `enableRenderHtml` is enabled
- regression [commit](https://github.com/ghiscoding/slickgrid-universal/commit/4e3e1d394247be75d1717feece833e200fce21dc#diff-b2a170f113dc78eb35a2c240a583d68a7a1d37bbfa04bc7e2ec0c89620caa147) ref
- there was an issue in both libs to fix this regression which came from v3.0 when we removed jQuery and start using the new ms-select-vanilla lib
- Multiple-Select-Vanilla [PR …
=> fix(common): Select Filter/Editor regular text shouldn't be html encoded

packages/common/src/services/__tests__/gridState.service.spec.ts, packages/common/src/services/gridState.service.ts
- the previous implementation was extending 3 defined properties but by doing so it was extending properly when a value was provided but it was returning an empty value instead of extending the original
- for example `{ ...gridCol, cssClass: currentCol }` would change the `cssClass` to undefined when `currentCol` doesn't have this `cssClass` and that is even when the original `gridCol` does have that same property. So instead of trying to extend specific properties we should just extend the entire objects, ie: `{ ...gridCol, ...currentCol }` would extend correctly whatever property is defined in `currentCol`
- also make sure to extend currentCol but without the `columnId` since that doesn't exist a regular Column property
=> fix(GridState): calling `getAssociatedGridColumns` should extend column

packages/common/src/extensions/extensionCommonUtils.ts, packages/common/src/extensions/slickDraggableGrouping.ts
- this fixes 2 issues identified in Angular-Slickgrid, https://github.com/ghiscoding/Angular-Slickgrid/issues/1180
- when leaving a SPA page and going back to it, it could throw a bunch of errors. We simply need to make sure that any sortable instances are destroyed before recreating any new ones
The error comes from SortableJS from this line
https://github.com/SortableJS/Sortable/blob/7af63fdc5d7512e7f0b8abb10970d473521b31a5/Sortable.js#L1115
=> fix(grouping): DraggableGrouping could throw when leaving page

packages/binding/package.json, packages/common/package.json, packages/composite-editor-component/package.json, packages/custom-footer-component/package.json, packages/custom-tooltip-plugin/package.json, packages/empty-warning-component/package.json, packages/event-pub-sub/package.json, packages/excel-export/package.json, packages/graphql/package.json, packages/odata/package.json, packages/pagination-component/package.json, packages/row-detail-view-plugin/package.json, packages/rxjs-observable/package.json, packages/text-export/package.json, packages/utils/package.json, packages/vanilla-bundle/package.json, packages/vanilla-force-bundle/package.json
- when defining the old CJS `main` and `module`, these properties should come after `exports` (new ESM prop) so that newer NodeJS will try `exports` first (we shouldn't try the fallback first), while for old NodeJS it will automatically use the fallbacks since `exports` won't work, see this TypeScript for more info (https://www.typescriptlang.org/docs/handbook/esm-node.html)
=> fix: CJS fallbacks should be at the end not at beginning

examples/vite-demo-vanilla-bundle/src/examples/example05.ts, examples/vite-demo-vanilla-bundle/src/examples/example07.ts, packages/common/src/interfaces/gridServiceInsertOption.interface.ts, packages/common/src/services/__tests__/grid.service.spec.ts, packages/common/src/services/grid.service.ts, test/cypress/e2e/example07.cy.ts, test/cypress/e2e/example17.cy.ts
- we should be able to disable the scroll into view if we don't want it
- also fixes an issue when inserting multiple items in a Tree Data grid, the previous default was to use the insert position to then scroll to top/bottom of the grid, however in a Tree Data grid it does not necessarily insert at the top/bottom it would rather insert the item in a defined group which could end up being in the middle of the grid so we shouldn't automatically
- fixes an issue opened in Angular-Slickgrid, https://github.com/ghiscoding/Angular-Slickgrid/issues/1201
=> feat(common): add optional `scrollIntoView` to GridService `addItems`

packages/common/src/extensions/__tests__/slickRowMoveManager.spec.ts, packages/common/src/extensions/slickRowMoveManager.ts
- when `usabilityOverride` returns false on some rows, we shouldn't add the `cssClass` on the parent div
This issue came up in SlickGrid example while using an override function that returns false on every odd rows and it caused UI issue shown below
=> fix(plugins): RowMoveManager shouldn't add cssClass when not usable

packages/common/src/services/sort.service.ts
- fixes issue found in Angular-Slickgrid https://github.com/ghiscoding/Angular-Slickgrid/issues/1215
- when `multiColumnSort` is disabled, the 3rd clicks will not provide a sortCol object and was throwing an error for that reason, so use optional chaining to make sure it's defined before reading its sort column id
=> fix(common): Sort Service could throw on 3rd with undefined columnId

packages/common/src/extensions/__tests__/slickCellExternalCopyManager.spec.ts, packages/common/src/extensions/slickCellExternalCopyManager.ts, pnpm-lock.yaml
- fix an issue where copying and pasting to multiple area only kept the last undo and reapplied it over and over and the cause was because the clipCommand was global to the class so it only kept the last undo, the fix is to make sure the clipCommand variable is local to the execution handler instead
=> fix: copying multiple times only kept last undo CellExternalCopyManager

packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- calling `datasetHierarchical` setter shouldn't cause scroll flickering, this was caused a call to the DataView `setItems` with an empty array which in terms always scroll back to top and that was meant to clear the dataset before recreating it, however this is certainly not needed since calling the `datasetHierarchical` setter will then trigger a new sort which will indirectly call DataView setItems anyway
=> fix: adding dataset hierarchical item shouldn't cause scroll flickering

packages/common/src/filter-conditions/index.ts
According to issue #1077 
- add `export * from './dateFilterCondition';` to `packages/common/src/filter-conditions/dateFilterCondition.ts`
=> fix(filters): update filter-conditions add dateFilterCondition to barrel, fixes #1077

examples/vite-demo-vanilla-bundle/src/examples/example06.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/columnExcelExportOption.interface.ts, packages/common/src/interfaces/excelExportOption.interface.ts, packages/excel-export/src/excelExport.service.spec.ts, packages/excel-export/src/excelExport.service.ts, packages/excel-export/src/excelUtils.ts, pnpm-lock.yaml
- prior to this PR, the auto-detect was always enabled especially when column has a number field type but sometime the auto-detection is wrong and we wish to disable it, so this PR is adding a flag that allow the user to disable the auto-detect cell format, it can be provided from either the grid options or from a column definition, but in both cases it has to be provided into the `excelExportOptions: { autoDetectCellFormat: false }`
=> feat(export): add `autoDetectCellFormat` flag to Excel Export Options

examples/vite-demo-vanilla-bundle/src/examples/example01.ts, examples/vite-demo-vanilla-bundle/src/examples/example06.html, examples/vite-demo-vanilla-bundle/src/examples/example06.ts, examples/vite-demo-vanilla-bundle/src/examples/example07.ts, packages/common/src/interfaces/treeDataOption.interface.ts, packages/common/src/services/__tests__/filter.service.spec.ts, packages/common/src/services/__tests__/treeData.service.spec.ts, packages/common/src/services/__tests__/utilities.spec.ts, packages/common/src/services/filter.service.ts, packages/common/src/services/treeData.service.ts, packages/common/src/services/utilities.ts, test/cypress/e2e/example01.cy.ts, test/cypress/e2e/example06.cy.ts
- add a new auto-recalc tree totals feature which is disabled by default, this new feature comes with 2 new properties
- `autoRecalcTotalsOnFilterChange` to enabled the feature
- `autoRecalcTotalsDebounce` to limit recalc execution when used with large tree dataset
- add more functionalities into Example 6 to not just add new file but also remove last inserted song
=> feat(TreeData): add auto-recalc feature for Tree Totals w/Aggregators

examples/vite-demo-vanilla-bundle/src/examples/example06.html, examples/vite-demo-vanilla-bundle/src/examples/example06.ts, packages/common/src/services/__tests__/utilities.spec.ts, packages/common/src/services/treeData.service.ts, packages/common/src/services/utilities.ts, test/cypress/e2e/example06.cy.ts
- remove previous `debounce` method since it doesn't work well when used within an event that can be triggered multiple times. The debounce method did work but we had to keep a copy of the debounced assignment and then also provide all arguments to the inner debounce which seems like a lot of work when in reality the setTimeout is only 3 lines of code which comes to about the same if we need to keep a debounced instantiation every time
=> chore: use settimeout for debouncing of tree totals auto-recalc

examples/vite-demo-vanilla-bundle/src/examples/example07.ts, packages/common/src/editors/__tests__/singleSelectEditor.spec.ts, packages/common/src/editors/selectEditor.ts, packages/common/src/filters/__tests__/selectFilter.spec.ts, packages/common/src/filters/selectFilter.ts
- fixes an issue identified in Angular-Slickgrid as per this issue https://github.com/ghiscoding/Angular-Slickgrid/issues/1240
- the problem was when I moved to the new multiple-select-vanilla lib, I used the wrong flag, we need to use `renderOptionLabelAsHtml` when we want text labels and `useSelectOptionLabelToHtml` when we want values to be rendered as HTML, so the issue was that the flags were inversed and that is why it was showing the values instead of the text labels
=> fix(common): Select Filter/Editor enableRenderHtml was wrong

packages/common/src/services/grid.service.ts
- GridService `highlightRowByMetadata()` method expect a delay to highlight and fade out (of course duh..), but when disposing (destroying) the GridService we should clear this highlight before leaving because in some cases it could try to highlight when we already left the page (i.e. this happened while running Cypress E2E tests since it goes faster than the fading which is ~2sec.)
=> fix(GridService): clear any opened highlight timers before disposing

examples/vite-demo-vanilla-bundle/src/examples/example02.ts, packages/common/src/services/__tests__/resizer.service.spec.ts, packages/common/src/services/resizer.service.ts, test/cypress/e2e/example02.cy.ts
as discussed here, this fixes the behavior if no autoresize.container option is defined
=> fix(resizer): resize without container

packages/row-detail-view-plugin/src/slickRowDetailView.spec.ts, packages/row-detail-view-plugin/src/slickRowDetailView.ts
- user can now prevent event and return false on `onBeforeRowDetailToggle` event to cancel opening certain Row Detail, for example the code below would block opening Row Detail when its id is `1`
```ts
detailView.onBeforeRowDetailToggle.subscribe(function(e, args) {
// you coud cancel opening certain rows
if (args.item.id === 1) {
e.preventDefault();
return false;
}
console.log('before toggling row detail', args.item);
});
```
=> feat: add option to cancel Row Detail opening

examples/vite-demo-vanilla-bundle/src/app-routing.ts, examples/vite-demo-vanilla-bundle/src/app.html, examples/vite-demo-vanilla-bundle/src/examples/example19.html, examples/vite-demo-vanilla-bundle/src/examples/example19.scss, examples/vite-demo-vanilla-bundle/src/examples/example19.ts, packages/common/src/extensions/__tests__/slickCellSelectionModel.spec.ts, packages/common/src/extensions/slickCellSelectionModel.ts, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-plugins.scss, test/cypress.config.ts, test/cypress/e2e/example19.cy.ts
- adding "pageUp/pageDown/home/end" to SlickCellSelection when using selection with "Shift+{key}"
- add new Example 19 demo to manually test updated Cell Selection feature w/wo Pagination
=> feat: add pageUp/pageDown/home/end to SlickCellSelection

packages/row-detail-view-plugin/src/slickRowDetailView.spec.ts, packages/row-detail-view-plugin/src/slickRowDetailView.ts
Reverts ghiscoding/slickgrid-universal#1125 since this is causing issues in external libs Angular-Slickgrid, ...
=> Revert "feat: add option to cancel Row Detail opening"

packages/common/src/interfaces/elementEventListener.interface.ts, packages/common/src/services/__tests__/bindingEvent.service.spec.ts, packages/common/src/services/bindingEvent.service.ts
- in order to bind and unbind a set of event listeners more easily, we can add an optional group name, for example this will be helpful to unbind all event related to sub-menus that gets closed while still keeping other event listeners in place when the parent menu remains open while sub-menus were closed
=> feat(common): add group name to `bind` and `unbindAll` methods

packages/common/src/services/__tests__/bindingEvent.service.spec.ts, packages/common/src/services/bindingEvent.service.ts
- previous PR #1150 brought this new feature but it came with a bug that is if the bounded events to unbind are at the end of the array and we called `unbindAll`, it wasn't removing all expected events because calling `splice` within the logic was reindexing the array causing an index offset and by doing so, it missed unbounding some of them
- the best approach is to loop in reverse order which has no consequences on the array indexes and will not cause any index offset
- also add possibility to call multiple group names with `unbindAll([...])`
=> fix(common): `unbindAll` with a group name should remove all tagged ones

examples/vite-demo-vanilla-bundle/src/examples/example01.ts, examples/vite-demo-vanilla-bundle/src/examples/example04.ts, examples/vite-demo-vanilla-bundle/src/examples/example06.ts, examples/vite-demo-vanilla-bundle/src/examples/example07.ts, packages/common/src/extensions/__tests__/slickCellMenu.plugin.spec.ts, packages/common/src/extensions/__tests__/slickContextMenu.spec.ts, packages/common/src/extensions/__tests__/slickGridMenu.spec.ts, packages/common/src/extensions/menuBaseClass.ts, packages/common/src/extensions/menuFromCellBaseClass.ts, packages/common/src/extensions/slickColumnPicker.ts, packages/common/src/extensions/slickContextMenu.ts, packages/common/src/extensions/slickGridMenu.ts, packages/common/src/interfaces/elementEventListener.interface.ts, packages/common/src/interfaces/gridMenu.interface.ts, packages/common/src/interfaces/gridMenuOption.interface.ts, packages/common/src/interfaces/menuCallbackArgs.interface.ts, packages/common/src/interfaces/menuOptionItem.interface.ts, packages/common/src/services/__tests__/bindingEvent.service.spec.ts, packages/common/src/services/bindingEvent.service.ts, test/cypress/e2e/example01.cy.ts, test/cypress/e2e/example04.cy.ts, test/cypress/e2e/example07.cy.ts
- currently only works by `click` event on sub-menus, the `mouseover` will be implemented in a future PR
=> feat: add sub-menu(s) to GridMenu plugin

packages/common/src/extensions/menuBaseClass.ts, packages/common/src/extensions/slickHeaderButtons.ts
- instead of having special HeaderButton code inside `menuBaseClass` file, we can simply move the code to where it belongs which is in the dedicate SlickHeaderButtons file
=> chore: move HeaderButton handler callback into SlickHeaderButton

packages/common/src/extensions/extensionCommonUtils.ts, packages/common/src/extensions/menuFromCellBaseClass.ts
just to reduce the use of `innerHTML`
=> fix(common): replace `innerHTML: '&times;'` with `textContent: '×'`

packages/common/src/services/__tests__/bindingEvent.service.spec.ts, packages/common/src/services/bindingEvent.service.ts
- another small issue found after implementing previous PR #1150, `groupName` was only added to single event `bind`, however it should also be supported by `.bind` with multiple events provided as an array
=> fix(common): calling `bind` with multiple events should add group name

examples/vite-demo-vanilla-bundle/src/examples/example14.scss, examples/vite-demo-vanilla-bundle/src/examples/example14.ts, packages/common/src/extensions/__tests__/slickCellMenu.plugin.spec.ts, packages/common/src/extensions/__tests__/slickContextMenu.spec.ts, packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts, packages/common/src/extensions/menuBaseClass.ts, packages/common/src/extensions/slickGridMenu.ts, packages/common/src/extensions/slickHeaderMenu.ts, packages/common/src/interfaces/headerMenuItems.interface.ts, packages/common/src/interfaces/headerMenuOption.interface.ts, test/cypress/e2e/example01.cy.ts, test/cypress/e2e/example04.cy.ts, test/cypress/e2e/example07.cy.ts, test/cypress/e2e/example09.cy.ts, test/cypress/e2e/example10.cy.ts, test/cypress/e2e/example11.cy.ts, test/cypress/e2e/example13.cy.ts, test/cypress/e2e/example14.cy.ts, test/cypress/e2e/example15.cy.ts
- currently only works by `click` event on sub-menus, the `mouseover` will be implemented in a future PR
=> feat: add sub-menu(s) to HeaderMenu plugin

examples/vite-demo-vanilla-bundle/src/examples/example10.ts, packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts, packages/common/src/extensions/slickHeaderMenu.ts, packages/common/src/interfaces/headerMenuItems.interface.ts, packages/common/src/services/filter.service.ts, packages/common/src/services/sort.service.ts
- to align with other Menu plugins, let's rename HeaderMenu `items` property to `commandItems`
=> fix: deprecate HeaderMenu `items` in favor of `commandItems`

packages/common/src/extensions/menuFromCellBaseClass.ts, packages/common/src/extensions/slickColumnPicker.ts, packages/common/src/extensions/slickHeaderMenu.ts
- prior to this PR, clicking a close button would close all type of menus but in theory it should only close the targeted Menu instead of all menus. This could caused issues and trigger unexpected events like `onGridMenuMenuClose` even if the Grid Menu was in fact closed
=> fix(common): clicking Menu close button should only close current menu

packages/common/src/extensions/__tests__/slickCellMenu.plugin.spec.ts, packages/common/src/extensions/__tests__/slickContextMenu.spec.ts, packages/common/src/extensions/__tests__/slickGridMenu.spec.ts, packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts, packages/common/src/extensions/menuBaseClass.ts, packages/common/src/extensions/menuFromCellBaseClass.ts, packages/common/src/extensions/slickCellMenu.ts, packages/common/src/extensions/slickContextMenu.ts, packages/common/src/extensions/slickGridMenu.ts, packages/common/src/extensions/slickHeaderMenu.ts, packages/common/src/interfaces/cellMenuOption.interface.ts, packages/common/src/interfaces/contextMenuOption.interface.ts, packages/common/src/interfaces/gridMenuOption.interface.ts, packages/common/src/interfaces/headerMenuOption.interface.ts, test/cypress/e2e/example01.cy.ts, test/cypress/e2e/example04.cy.ts, test/cypress/e2e/example07.cy.ts, test/cypress/e2e/example14.cy.ts
- when first implemented sub-menus, I thought it was complex to add open sub-menus via mouseover (not just click event) but it turns out to be quite easy with the latest code that was put in place for sub-menus. So this PR adds the mouseover option and does make it the default event (we have 2 options: `click` or `mouseover` and the latter is the default)
- this new mouseover will be the default but user could change it to work via click event only by changing the option to `subMenuOpenByEvent: 'click'` (instead of the default which is `subMenuOpenByEvent: 'mouseover'`)
=> feat: add `subMenuOpenByEvent` option to open sub-menus via mouseover

packages/common/src/extensions/__tests__/slickContextMenu.spec.ts, packages/common/src/extensions/__tests__/slickGridMenu.spec.ts, packages/common/src/extensions/__tests__/slickHeaderButtons.spec.ts, packages/common/src/extensions/slickCellMenu.ts, packages/common/src/extensions/slickColumnPicker.ts, packages/common/src/extensions/slickContextMenu.ts, packages/common/src/extensions/slickGridMenu.ts, packages/common/src/extensions/slickHeaderMenu.ts, test/cypress/e2e/example12.cy.ts
- prior to this PR, when opening a context menu in Example 19 and clicking another cell would not close the opened context menu and it should. It seems to be caused by potentially other body mousedown event listeners registered outside of the lib, what we can do is use `capture: true` to make sure our listener are being dispatched first before other external ones and that fixes our problem.
- apply this patch to all Menu extensions/plugins
=> fix(common): context menu should close when clicking another cell

packages/common/src/extensions/__tests__/slickColumnPicker.spec.ts, packages/common/src/extensions/slickColumnPicker.ts
- similarly to the updated GridMenu behavior, we should not create the Column Picker in the DOM when the grid gets created, instead we should create/recreate the picker every time we need to open it
=> feat(common): create ColumnPicker dynamically every time

packages/common/src/extensions/menuBaseClass.ts, packages/common/src/extensions/menuFromCellBaseClass.ts, packages/common/src/extensions/slickGridMenu.ts, packages/common/src/extensions/slickHeaderMenu.ts, packages/common/src/global-grid-options.ts
- the logic should be the same as the sub-menu click event, if the item is disabled (or is a didiver), then we shouldn't go further and not try to open it
=> fix(common): mouseover disabled sub-menu shouldn't open it

packages/common/src/extensions/slickCellMenu.ts, packages/common/src/extensions/slickContextMenu.ts, packages/common/src/extensions/slickGridMenu.ts, packages/common/src/extensions/slickHeaderMenu.ts
- enabling `capture` for event has the side effect of calling the listener multiple times instead of a single time like we want
=> fix(common): rollback PR #1163, event `capture` causes listener callback calls

packages/common/src/editors/autocompleterEditor.ts, packages/common/src/extensions/extensionCommonUtils.ts, packages/common/src/filters/autocompleterFilter.ts, packages/common/src/filters/filterUtilities.ts, packages/common/src/services/__tests__/domUtilities.spec.ts, packages/common/src/services/domUtilities.ts, packages/composite-editor-component/src/slick-composite-editor.component.ts, packages/custom-footer-component/src/slick-footer.component.ts, packages/custom-tooltip-plugin/src/slickCustomTooltip.ts
- to further improve CSP support (Content Security Policy), we need to move `innerHTML` as separate assignment and not use it directly within a `createDomElement`, so for example this line `const elm = createDomElement('div', { innerHTML: '' })` should be split in 2 lines `const elm = createDomElement('div'); elm.innerHTML = '';`
- add option `RETURN_TRUSTED_TYPE: true` to default sanitizer using DOMPurify to improve CSP
=> fix: move `innerHTML` as separate assignment to improve CSP trusted types

examples/vite-demo-vanilla-bundle/src/examples/example10.html, examples/vite-demo-vanilla-bundle/src/examples/example10.ts, packages/common/src/services/__tests__/pagination.service.spec.ts, packages/common/src/services/pagination.service.ts, packages/pagination-component/src/__tests__/slick-pagination.spec.ts, packages/pagination-component/src/slick-pagination.component.ts, test/cypress/e2e/example10.cy.ts
- when changing cursor based by calling  `setCursorBased` we should recreate the pagination component, we can simply add a `onPaginationSetCursorBased` event to subscribe and recreate pagination
=> fix(pagination): should recreate pagination on cursor based changed

examples/vite-demo-vanilla-bundle/src/examples/example01.ts, examples/vite-demo-vanilla-bundle/src/examples/example04.ts, examples/vite-demo-vanilla-bundle/src/examples/example07.ts, packages/common/src/styles/_variables-theme-material.scss, packages/common/src/styles/_variables-theme-salesforce.scss, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-plugins.scss
- add a `$slick-menu-icon-min-width` SASS/CSS variable to align icon containers so that they are always aligned with and without icons. The issue only showed when the user has both with & without command icon as shown below. Adding a `min-width` helps so that the container, which uses `flex` doesn't shrink the icon span when no icon is provided
=> fix(styles): menu command with & without icons aren't aligned

examples/vite-demo-vanilla-bundle/src/examples/example14.ts, packages/common/src/filters/__tests__/compoundDateFilter.spec.ts, packages/common/src/filters/__tests__/compoundInputFilter.spec.ts, packages/common/src/filters/__tests__/compoundSliderFilter.spec.ts, packages/common/src/filters/filterUtilities.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/interfaces/operatorDetail.interface.ts
- this new grid option `compoundOperatorAlternateTexts` will allow the user to override any, or all, texts shown in a Compound Filter `operator` select dropdown
For example, taking this sample code
```ts
this.gridOptions = {
compoundOperatorAltTexts: {
numeric: { '=': { operatorAlt: 'eq', descAlt: 'alternate numeric equal description' } },
text: { '=': { operatorAlt: 'eq', descAlt: 'alternate text equal description' } }
},
}
```
will produce the following for both categories (text or numeric) of filter values
=> feat(common): add `compoundOperatorAltTexts` grid option

packages/common/src/editors/checkboxEditor.ts, packages/common/src/editors/inputEditor.ts, packages/common/src/editors/sliderEditor.ts, packages/common/src/extensions/__tests__/slickCellRangeSelector.spec.ts, packages/common/src/extensions/slickCellRangeSelector.ts
- when opening an editor while clicking the cell is actually triggering the SlickCellRangeSelector dragInit which was cancelling event bubbling and was breaking editor input usability
- this issue was reported in Angular-Slickgrid [issue 1303](https://github.com/ghiscoding/Angular-Slickgrid/issues/1303)
=> fix(common): SlickCellRangeSelector shouldn't stop editor event bubbling

examples/vite-demo-vanilla-bundle/package.json, packages/binding/package.json, packages/common/package.json, packages/composite-editor-component/package.json, packages/custom-footer-component/package.json, packages/custom-tooltip-plugin/package.json, packages/custom-tooltip-plugin/src/__tests__/slickCustomTooltip.spec.ts, packages/empty-warning-component/package.json, packages/event-pub-sub/package.json, packages/excel-export/package.json, packages/graphql/package.json, packages/odata/package.json, packages/pagination-component/package.json, packages/row-detail-view-plugin/package.json, packages/rxjs-observable/package.json, packages/text-export/package.json, packages/utils/package.json, packages/vanilla-bundle/package.json, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-force-bundle/package.json, packages/vanilla-force-bundle/src/__tests__/vanilla-force-bundle.spec.ts, pnpm-lock.yaml
- previous implementation didn't pass all type exports as can be shown in [Are the types wrong?](https://arethetypeswrong.github.io/?p=%40slickgrid-universal%2Fcommon%403.5.0) website, already applied the changes in `multiple-select-vanilla` library with a much greater success
- better approach came from RxJS [package.json](https://github.com/ReactiveX/rxjs/blob/master/packages/rxjs/package.json) great implementation of it
=> fix: improve build & types exports for all targets, Node, CJS/ESM

packages/common/src/core/slickCore.ts, packages/common/src/core/slickGrid.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/columnPicker.interface.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, packages/vanilla-force-bundle/src/__tests__/vanilla-force-bundle.spec.ts
- remove leftover jQuery slide/fade animations in all toggle methods, use CSS animation instead. We are removing the last `animate` boolean argument on all methods
- `setTopPanelVisibility`
- `setHeaderRowVisibility`
- `setColumnHeaderVisibility`
- `setFooterRowVisibility`
- `setPreHeaderPanelVisibility`
=> chore: remove leftover jQuery animations in all toggle methods

packages/common/src/aggregators/countAggregator.ts, packages/common/src/core/__tests__/slickCore.spec.ts, packages/common/src/core/__tests__/slickDataView.spec.ts, packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/__tests__/slickInteractions.spec.ts, packages/common/src/core/slickCore.ts, packages/common/src/core/slickDataview.ts, packages/common/src/core/slickGrid.ts, packages/common/src/core/slickInteractions.ts, test/jest-global-mocks.ts, test/jest.config.ts
- add full test coverage for `slick.core` and `slick.interactions`
- I'm saying it's full coverage on  `slick.core` because all the Utils stuff that is uncovered by tests will be moved in a future PR, so `slick.core` is by that definition fully covered
- add test spec file templates with basic unit tests for `slick.grid` and `slick.dataview`
=> chore: add slickCore & slickInteractions full unit tests coverage

examples/vite-demo-vanilla-bundle/src/examples/example16.ts, packages/common/src/core/slickInteractions.ts
- the `onDragEnd` was called every time a cell was clicked even when user was not even dragging, we should make sure to only trigger `onDragEnd` if a drag actually started to avoid triggering too many events for no reasons
=> fix: Draggable shouldn't trigger dragEnd without first dragging

packages/common/src/extensions/__tests__/slickCellRangeSelector.spec.ts, packages/common/src/extensions/slickCellRangeSelector.ts
- issue was found when user has an Editor open and then click on a row checkbox and start dragging that row checkbox cell, then the cell range decorator appears but never goes away because checkbox plugin has prevents event bubbling when having an editor and in turns wasn't destroying the cell range decorator when it should, the cell range decorator isn't visible but it has a z-index of 9999 and even though it's invisible it was showing on top of everything else making the cell behind it unclickable for the size of the cell range decorator (usually about the size of 2-3 cells)
=> fix(common): cell range decorator should be hidden after onDragEnd

packages/common/src/core/slickGrid.ts, packages/common/src/extensions/__tests__/slickGroupItemMetadataProvider.spec.ts, packages/common/src/extensions/slickGroupItemMetadataProvider.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/excelCopyBufferOption.interface.ts, packages/common/src/interfaces/formatter.interface.ts, packages/common/src/services/__tests__/extension.service.spec.ts, packages/common/src/services/extension.service.ts, packages/empty-warning-component/src/slick-empty-warning.component.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- in order to depend less on the use of innerHTML, we should convert internal code that have Formatter to use native HTML element to be more CSP compliant. However please note that the user will have to convert themselve the GroupTotals Formatter to native element as well for full CSP compliance on that section of the code
=> feat: convert GroupItemMetadataProvider Formatter to native HTML for CSP

packages/common/src/services/__tests__/sort.service.spec.ts, packages/common/src/services/sort.service.ts
when the user does not make the column `sortable`, it will now throw. This was caught after having trouble with a Tree Data grid, the column holding the Tree needs to be sortable since that is how the Tree Data feature is built on top of, if user removes the sorting it breaks the feature, so throwing an error seems to be the best for easier troubleshooting of the problem occurring
=> fix(common): throw when trying to preset sort on non-sortable column

packages/graphql/src/interfaces/graphqlServiceOption.interface.ts, packages/graphql/src/services/__tests__/graphql.service.spec.ts, packages/graphql/src/services/graphql.service.ts
-- Background --
By default when using Graphql (Apollo), all network requests hit the same endpoint, and as such they all have the same name in the devtools. e.g: `graphql`.  This makes performance monitoring and diagnosing problematic queries difficult. To get around this, we append the operationName of a graphql query to the url. e.g `graphql?GetUsers`, `graphql?getUserData` so we can uniquely identify each query.
https://stackoverflow.com/questions/64642948/is-there-a-way-to-name-graphql-requests-in-the-devtool-network-tab
-- Problem --
The dynamically built query in slickgrid does not allow specifying an operationName and so all queries generated by slickgrid have an operationName of `undefined`
eg: `query { datasetName (....) } ` …
=> feat(GraphQL): Provide ability to specify operationName

packages/common/src/formatters/__tests__/iconBooleanFormatter.spec.ts, packages/common/src/formatters/formatters.index.ts, packages/common/src/formatters/iconBooleanFormatter.ts, packages/common/src/formatters/index.ts
- this formatter is meant to be generic to display any icon the user want to display any type of icon on a boolean truthy value. It was created to replace the `Formatters.checkmark` which was too restrictive since it only worked with Font-Awesome 4 and only 1 assigned icon. The new formatter allows you to use any CSS class you want to use on a truthy value.
- note that any of these values is considered falsy and will not show the icon: `false`, `undefined`, `null`, `0` or any negative number
=> feat(Formatters): add new `Formatters.iconBoolean` for icon w/truthy val

packages/common/src/core/slickCore.ts, packages/common/src/core/slickGrid.ts
- when calling `applyHtmlCode()` method and our target element is empty and we try to reapply empty, it should always be ok to simply skip this reassignment.
- this should also help with performance since trying to reapply empty using `innerHTML` will probably cause a canvas repaint but if we manage to skip this then a repaint will also be skipped
- this should also help with CSP too because we could write a Formatter with native element while still returning empty string when there's no value to return, that will then call `applyHtmlCode` and skip the assignment since the cell was already detected as empty
=> perf: skip reapplying empty html when target is already empty

examples/vite-demo-vanilla-bundle/src/examples/example18.ts, packages/common/src/extensions/slickGroupItemMetadataProvider.ts, packages/common/src/formatters/__tests__/formatterUtilities.spec.ts, packages/common/src/formatters/__tests__/maskFormatter.spec.ts, packages/common/src/formatters/__tests__/treeFormatter.spec.ts, packages/common/src/formatters/maskFormatter.ts, packages/common/src/formatters/treeFormatter.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/services/__tests__/domUtilities.spec.ts, packages/vanilla-force-bundle/src/salesforce-global-grid-options.ts
- it seems that DocumentFragment is not supported by all environment, e.g. Salesforce doesn't seem to support it yet
=> chore: add `preventDocumentFragmentUsage` grid option

packages/common/src/filters/__tests__/compoundDateFilter.spec.ts, packages/common/src/filters/__tests__/compoundInputFilter.spec.ts, packages/common/src/filters/__tests__/compoundInputNumberFilter.spec.ts, packages/common/src/filters/__tests__/compoundInputPasswordFilter.spec.ts, packages/common/src/filters/__tests__/compoundSliderFilter.spec.ts, packages/common/src/filters/dateFilter.ts, packages/common/src/filters/filterUtilities.ts, packages/common/src/filters/inputFilter.ts, packages/common/src/filters/sliderFilter.ts, packages/common/src/formatters/__tests__/treeFormatter.spec.ts, packages/common/src/formatters/treeFormatter.ts
- use `applyHtmlCode()` anywhere we can so that at the end there is only 1 place to modify if need be
=> chore: remove some more `innerHTML` assignment

examples/vite-demo-vanilla-bundle/src/examples/example02.ts, examples/vite-demo-vanilla-bundle/src/examples/example03.ts, examples/vite-demo-vanilla-bundle/src/examples/example04.ts, examples/vite-demo-vanilla-bundle/src/examples/example05.ts, examples/vite-demo-vanilla-bundle/src/examples/example06.ts, examples/vite-demo-vanilla-bundle/src/examples/example07.ts, examples/vite-demo-vanilla-bundle/src/examples/example08.ts, examples/vite-demo-vanilla-bundle/src/examples/example10.ts, examples/vite-demo-vanilla-bundle/src/examples/example11.ts, examples/vite-demo-vanilla-bundle/src/examples/example12.ts, examples/vite-demo-vanilla-bundle/src/examples/example14.ts, examples/vite-demo-vanilla-bundle/src/examples/example15.ts, examples/vite-demo-vanilla-bundle/src/examples/example16.ts, packages/common/src/extensions/slickContextMenu.ts, packages/common/src/extensions/slickGridMenu.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/custom-tooltip-plugin/README.md, packages/excel-export/README.md, packages/rxjs-observable/README.md, packages/text-export/README.md, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, packages/vanilla-force-bundle/src/__tests__/vanilla-force-bundle.spec.ts
- external resources can be provided through the grid options, but these options are sometime deep copied and that might have the side effect of losing the singleton ref of the instantiate services/resources, instead we can simply keep these singleton refs before any grid options merge can happen and that is in the constructor before the grid initializes and before the grid options are merged and sometime deep copied with global options
=> fix: registered external resouces should keep singleton ref

package.json, packages/common/package.json, packages/common/src/extensions/__tests__/slickCellSelectionModel.spec.ts, packages/common/src/extensions/slickCellSelectionModel.ts, packages/utils/src/utils.spec.ts, packages/utils/src/utils.ts, packages/vanilla-bundle/package.json, pnpm-lock.yaml, test/cypress/e2e/example17.cy.ts, test/cypress/e2e/example19.cy.ts, test/cypress/support/commands.ts, test/cypress/support/drag.ts
the previous key combo were incorrect, the new combo is the following
- `Shift+Home` will select from current cell position to first cell horizontally
- `Shift+End` will select from current cell position until the last cell horizontally
- `Ctrl+Shift+Home` will select everything that is on the left side of current cell position and everything on top current position (horizontally left until first cell & vertically left until first row)
- `Ctrl+Shift+End` will select everything that is on the right side of current cell position and everything on bottom current position (horizontally right until last cell & vertically right until last row)
The other key combos (with PageUp/PageDown/ArrowLeft/ArrowRight) remains the same
=> fix: cell selection range with key combos were incorrect

packages/common/src/core/__tests__/slickCore.spec.ts, packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickCore.ts, packages/common/src/core/slickDataview.ts, packages/common/src/core/slickGrid.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/event-pub-sub/src/eventPubSub.service.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- by modifying the SlickEvent class to also publish an event when a PubSub Service is provided to a SlickEvent, we can avoid having our previous monkey patch of subscribing to **all** SlickGrid/DataView events to then dispatch event, this acted like a middleware, we can avoid all of that middleware with this new approach and publish right away via the PubSub when provided
- also removed `defaultComponentEventPrefix`, `defaultSlickgridEventPrefix` grid options since they will not be used anymore
- more info below
With this PR, we merged the `SlickEvent` with our own PubSub Service (which uses a `CustomEvent`), this makes it easier to maintain and requires less monkey patch code. The reason we use our own PubSub is because it makes it easier to communicate with Component based frameworks …
=> feat: use PubSub Service singleton to subscribe to any SlickEvent

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/interfaces/gridOption.interface.ts
- copies implementation made in 6pac/SlickGrid repo at https://github.com/6pac/SlickGrid/pull/946
> as the title suggests this is meant to make unit/integration tests, e.g with testing-library, possible for apps using Slickgrid. In my specific case I'm making use of angular-slickgrid and would like to be able to test my app using angular-testing-library.
>
> The introduced devMode workarounds are in order to work around the following jsdom issues:
>
> [jsdom/jsdom#2310](https://github.com/jsdom/jsdom/issues/2310) (missing clientWidth) [jsdom/jsdom#992](https://github.com/jsdom/jsdom/issues/992) (missing ownerNode, even with a nice reference to Slickgrid ;) ) For additional conversations about this topic please refer to [ghiscoding/Angular-Slickgrid#1319](https://github.com/ghiscoding/Angul …
=> feat: introduce devMode to support nodejs based unit testing

packages/common/src/core/slickGrid.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts
- the previous code had 2 different `options` and `_options` that were not always in sync which caused issue when trying to update for example the `enableCellNavigation` option on the fly. With this new code change, there will no possibility to mix them up anywmore
=> fix: changing `enableCellNavigation` grid option not working

packages/composite-editor-component/src/slick-composite-editor.component.spec.ts, packages/composite-editor-component/src/slick-composite-editor.component.ts, test/cypress/e2e/example12.cy.ts
- fixes issues reported in Angular-Slickgrid: https://github.com/ghiscoding/Angular-Slickgrid/issues/1333
- prior to the fix, only the first item inserted had the correct `dataContext` argument provided to the `onSave`, any other inserts were resolving to another unrelated data context
- to fix this issue, we'll get the updated item right after it's been called by the `onAddNewRow` SlickEvent, which is the event being called after all editors are valid. Note however that an inserted item can also have an optional `insertNewId` which is taken care of with this fix as well
=> fix(composite): `onSave` always include last dataContext on few inserts

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/services/__tests__/grid.service.spec.ts, packages/common/src/services/grid.service.ts, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-bootstrap.scss, packages/composite-editor-component/src/slick-composite-editor.component.ts
- remove previous `highlightRowByMetadata()` method in GridService, we can avoid using ItemMetaData altogether by adding a simple `highlightRow()` method directly in the SlickGrid core lib and also add `rowHighlightCssClass` grid option which will be animated by default but user could also disable the animation and/or even disable the fade out (remain highlighted)
- this new approach simplifies the code a lot and doesn't require the use of ItemMetadata and calling multiple `updateItem()` and `render()` which is much better for performance
- also fixes an issue that was previously happening when inserting multiple items before the highlight timer had time to finish, that was leaving multiple row highlighted when they shouldn't. 
- also fix potential mem leak found on some `setTimeout` not …
=> feat(core): add `rowHighlightCssClass` & `highlightRow()` to SlickGrid

packages/common/src/core/slickGrid.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/styles/slick-bootstrap.scss
- the idea of having a permanent highlight is irrealistic since the highlight is applied to a temp slick-row, in other word this highlight would disappear as soon as we call any of: scroll, render, invalidate
=> chore: `highlightRow()` should always have default duration

packages/common/src/core/__tests__/slickCore.spec.ts, packages/common/src/core/slickCore.ts, packages/common/src/core/slickDataview.ts, packages/common/src/core/slickGrid.ts, packages/common/src/extensions/slickGroupItemMetadataProvider.ts, packages/common/src/services/filter.service.ts, packages/utils/src/__tests__/domUtils.spec.ts, packages/utils/src/__tests__/nodeExtend.spec.ts, packages/utils/src/domUtils.ts, packages/utils/src/index.ts, packages/utils/src/nodeExtend.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, packages/vanilla-force-bundle/src/vanilla-force-bundle.ts
the `extend` function that was added to SlickGrid core utils seems to be causing problems when Angular-Slickgrid are published on external website as per this issue: https://github.com/ghiscoding/Angular-Slickgrid/issues/1334
- the node-extend came from this popular npm package: https://github.com/justmoon/node-extend/blob/v1.2.0/test/index.js the reason, I reimplemented it in here is because the npm package is using old CJS syntax and is not ESM friendly, moving the code in here would be better with newer syntax and less CJS code, also less external dependencies
=> feat(utils): replace slick-core extend utils with `node-extend`

packages/common/src/core/slickGrid.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/services/grid.service.ts
Add a new `rowHighlightDuration` Grid Option to control the duration of the row highlight instead of using a default that was a little too long. The new default is 400 (previously 750 but that seemed too long).
=> fix(core): add missing option to control row highlight duration CRUD

packages/common/src/extensions/__tests__/slickCellExcelCopyManager.spec.ts, packages/common/src/extensions/slickCellExcelCopyManager.ts
Hey ho, when playing around with the Excel Copy Buffer I noticed that in my sample when copying and pasting multiple rows which overflow, new row creation failed with
`[SlickGrid DataView] Each data element must implement a unique 'id' property`
My example was using the OData Backend hence with a custom id column, set via `datasetIdPropertyName`.
It took me quite a while to figure out that this can be solved by overriding the following property in the options:
```
excelCopyBufferOptions: {
newRowCreator: (count) => { ... }
}
```
so I thought adding this feature to respect the `datasetIdPropertyName` should make it work out of the box.
See the added unit test for better clarification :)
=> feat: datasetIdPropertyName respected in newRowCreator

packages/row-detail-view-plugin/src/slickRowDetailView.spec.ts, packages/row-detail-view-plugin/src/slickRowDetailView.ts, packages/utils/src/__tests__/utils.spec.ts, packages/utils/src/nodeExtend.ts, packages/utils/src/utils.ts
- we can use `node-extend` which does the job and already has plenty of unit tests
- this also makes the build slightly smaller by removing a few lines of code
=> chore(utils): remove unnecessary `objectAssignAndExtend` method

packages/common/src/core/slickCore.ts, packages/common/src/core/slickDataview.ts, packages/common/src/core/slickGrid.ts, packages/common/src/extensions/slickCheckboxSelectColumn.ts, packages/common/src/extensions/slickRowSelectionModel.ts, packages/common/src/filters/nativeSelectFilter.ts, packages/common/src/services/collection.service.ts, packages/common/src/services/domUtilities.ts, packages/common/src/services/extension.service.ts, packages/common/src/services/filter.service.ts, packages/common/src/services/sort.service.ts, packages/common/src/services/treeData.service.ts, packages/common/src/services/utilities.ts, packages/composite-editor-component/src/slick-composite-editor.component.ts, packages/utils/src/domUtils.ts
- as per this article [Measuring Performance of Different JavaScript Loop Types](https://blog.bitsrc.io/measuring-performance-of-different-javascript-loop-types-c0e9b1d193ed), the `for...in` and `for...of` aren't the most optimized for loops, the `for` and `.forEach` are more the most optimized methods across all browser engine and the `for...in` seems to be the worst to use and should be avoided when dealing with large dataset which can often be the case with this project
=> perf: prefer `.forEach` over `for...in` and `for...of`

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts
- the legacy TreeColumns depth was removed in SlickGrid  [PR](https://github.com/6pac/SlickGrid/pull/775) but some functions were missed and should be removed, they are `getHeadersWidthL()` and `getHeadersWidthR()` that are no longer referenced
- found these unused functions while adding unit tests for SlickGrid
=> chore: remove unused functions from legacy TreeColumns depth code

packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-plugins.scss, packages/row-detail-view-plugin/package.json, packages/row-detail-view-plugin/src/slickRowDetailView.spec.ts, packages/row-detail-view-plugin/src/slickRowDetailView.ts, pnpm-lock.yaml
- calling sort should collapse all Row Detail, however this was only true when triggered by clicking on column header menu, however it wasn't being triggered when called from Header Menu and Grid Menu (clear all sorting)
=> fix(RowDetail): sort change should collapse all Row Detail

examples/vite-demo-vanilla-bundle/src/examples/example11.ts, examples/vite-demo-vanilla-bundle/src/examples/example12.ts, examples/vite-demo-vanilla-bundle/src/examples/example14.ts, examples/vite-demo-vanilla-bundle/src/examples/example21.ts, packages/common/src/core/__tests__/slickCore.spec.ts, packages/common/src/core/slickCore.ts, packages/common/src/services/__tests__/extension.service.spec.ts, packages/row-detail-view-plugin/src/slickRowDetailView.spec.ts, packages/row-detail-view-plugin/src/slickRowDetailView.ts
- I tried to implement this feature in a previous PR #1125 but that introduced a regression which is got fixed in this PR and reintroduces this feature without regressing this time.
=> feat: (re)add option to cancel Row Detail opening

docs/TOC.md, docs/column-functionalities/editors/Autocomplete-Editor-(Kraaden-lib).md, docs/developer-guides/csp-compliance.md, examples/vite-demo-vanilla-bundle/index.html, packages/common/src/core/__tests__/slickDataView.spec.ts, packages/common/src/core/slickDataview.ts
- this was the last piece of code requiring `unsafe-eval` or `unsafe-inline` (note the user is still required to enable `useCSPSafeFilter` to be fully CSP safe, it is an opt-in because it is a bit slower)
=> feat: make DataView Grouping `compileAccumulatorLoop` CSP safe

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/extensions/__tests__/slickGridMenu.spec.ts, packages/common/src/extensions/menuBaseClass.ts, packages/common/src/extensions/slickDraggableGrouping.ts, packages/common/src/extensions/slickGridMenu.ts, packages/common/src/extensions/slickHeaderMenu.ts, packages/composite-editor-component/src/slick-composite-editor.component.ts, packages/utils/src/__tests__/domUtils.spec.ts, packages/utils/src/domUtils.ts
Follows SlickGrid [PR 960](https://github.com/6pac/SlickGrid/pull/960)
> Extra spaces in class dom attribute are allowed in html (e.g. class="some-class  other-class "). SlickGrid should probably also behave the same way (or at least fail with some meaningfull validation error).
> 
> This commit just ignores all extra spaces in headerCssClass (between individual classes or leading / trailing).
>
=> fix: allow extra spaces in headerCssClass

examples/vite-demo-vanilla-bundle/src/examples/example19.ts, packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickCore.ts, packages/common/src/core/slickGrid.ts, packages/common/src/extensions/__tests__/slickCellExternalCopyManager.spec.ts, packages/common/src/extensions/__tests__/slickCellRangeSelector.spec.ts, packages/common/src/extensions/__tests__/slickCellSelectionModel.spec.ts, packages/common/src/extensions/__tests__/slickRowSelectionModel.spec.ts, packages/common/src/extensions/slickCellExternalCopyManager.ts, packages/common/src/extensions/slickCellRangeSelector.ts, packages/common/src/extensions/slickCellSelectionModel.ts, packages/common/src/extensions/slickColumnPicker.ts, packages/common/src/extensions/slickDraggableGrouping.ts, packages/common/src/extensions/slickGridMenu.ts, packages/common/src/extensions/slickRowMoveManager.ts, packages/common/src/extensions/slickRowSelectionModel.ts, packages/common/src/services/__tests__/extension.service.spec.ts, packages/row-detail-view-plugin/src/slickRowDetailView.ts
- it was already available for `SlickGrid` and `SlickDataView` `SlickEvent`s but it wasn't yet available for other plugin events
- add a `getPubSubService()` method in SlickGrid to be able to easily get PubSub instance from within any plugins or for the user themselves
- you can also cancel the event from bubbling **but this is only available** when it's a **`SlickEvent`** (because regular PubSub events do not include any native event), see example below
- Note: the internal PubSub can now deal with both regular PubSub events and SlickEvents but their structure are different
1. regular PubSub event have a structure of:: `((args: any) => ...`
- e.g. `onBeforeGridCreate` 
3. SlickEvent have a different structure of:: `((e: { eventData: SlickEventData; args: any; }) => ...`
- e.g. …
=> feat(core): expose all SlickEvent via internal PubSub Service

examples/vite-demo-vanilla-bundle/src/examples/example12.ts
- so it turns out that instead of subscribing to multiple events like (`onPaginationChanged`, `onSort`, `onFilterChanged`, ....), they all can be replaced with 1 event `onRowsOrCountChanged` from DataView which is triggered for all of these cases because that is the 1 event that tell the UI to rerender when anything changes
=> fix(demo): Unsaved Cell CSS Styling follow sort/filter/pagination

package.json, packages/common/src/formatters/__tests__/progressBarFormatter.spec.ts, packages/common/src/services/__tests__/resizer.service.spec.ts, packages/common/src/services/resizer.service.ts, pnpm-lock.yaml
- the latest JSDOM 23.2  switched their CSS selector engine from nwsapi to @asamuzakjp/dom-selector but that also broke some of my unit tests
=> chore(tests): fix more broken tests after update to JSDOM 23.2

packages/common/src/core/slickGrid.ts
duplicate code exist at line shown below, so there's no need to keep keydown keyCaptureList duplicate code. I found this duplicate code while adding unit tests and the piece of code that I'm removing seems unreachable, hence why I'm removing it
https://github.com/ghiscoding/slickgrid-universal/blob/801bd4ca62edc218b51b10602f0cfd4fd5483a4f/packages/common/src/core/slickGrid.ts#L4754-L4760
so we can remove duplicate code appearing with a slight different if condition
https://github.com/ghiscoding/slickgrid-universal/blob/801bd4ca62edc218b51b10602f0cfd4fd5483a4f/packages/common/src/core/slickGrid.ts#L4769-L4775
=> fix(core): remove editor keydown keyCaptureList duplicate code

examples/vite-demo-vanilla-bundle/src/examples/example12.ts, packages/common/src/editors/autocompleterEditor.ts, packages/common/src/editors/checkboxEditor.ts, packages/common/src/editors/dualInputEditor.ts, packages/common/src/editors/inputEditor.ts, packages/common/src/editors/longTextEditor.ts, packages/common/src/editors/sliderEditor.ts, packages/common/src/filters/sliderFilter.ts
- the previous code was to extend a SlickEventData with an Event but the correct way is to simply pass the Event to SlickEventData as the first argument and we're done
=> fix: Editors/Filters should create SlickEventData with event arg

packages/common/src/core/slickCore.ts, packages/common/src/core/slickDataview.ts, packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts, packages/common/src/interfaces/rowDetailView.interface.ts, packages/row-detail-view-plugin/src/slickRowDetailView.spec.ts, packages/row-detail-view-plugin/src/slickRowDetailView.ts
- continuation of previous PR #1327 to add proper types to SlickEventHandler arguments
=> fix(core): SlickEvent handler event should be type of ArgType

examples/vite-demo-vanilla-bundle/src/examples/example04.html, examples/vite-demo-vanilla-bundle/src/examples/example04.ts, packages/common/src/extensions/__tests__/slickCheckboxSelectColumn.spec.ts, packages/common/src/extensions/slickCheckboxSelectColumn.ts, packages/common/src/interfaces/checkboxSelectorOption.interface.ts, packages/common/src/services/__tests__/extension.service.spec.ts, packages/common/src/services/extension.service.ts, test/cypress/e2e/example04.cy.ts
- this will only work when the "Select All" checkbox is NOT shown in the column header titles row (`hideInColumnTitleRow: true`)
=> feat: add `name` option to CheckboxSelectColumn plugin on columDef

docs/migrations/migration-to-4.x.md, packages/common/src/core/slickGrid.ts, packages/common/src/extensions/__tests__/slickCheckboxSelectColumn.spec.ts, packages/common/src/extensions/__tests__/slickGroupItemMetadataProvider.spec.ts, packages/common/src/extensions/slickAutoTooltip.ts, packages/common/src/extensions/slickCellExternalCopyManager.ts, packages/common/src/extensions/slickCheckboxSelectColumn.ts, packages/common/src/extensions/slickColumnPicker.ts, packages/common/src/extensions/slickGridMenu.ts, packages/common/src/formatters/__tests__/treeFormatter.spec.ts, packages/common/src/formatters/formatterUtilities.ts, packages/common/src/interfaces/column.interface.ts, packages/common/src/interfaces/columnPicker.interface.ts, packages/common/src/interfaces/excelCopyBufferOption.interface.ts, packages/common/src/interfaces/gridMenuOption.interface.ts, packages/composite-editor-component/src/slick-composite-editor.component.ts, packages/excel-export/src/excelExport.service.ts, packages/graphql/src/services/graphql.service.ts, packages/odata/src/services/grid-odata.service.ts, packages/text-export/src/textExport.service.ts, packages/utils/src/__tests__/domUtils.spec.ts, packages/utils/src/domUtils.ts, packages/utils/src/stripTagsUtil.ts
- change Column interface `name` to also accept `DocumentFragment`
- change `headerColumnValueExtractor` to also accept `DocumentFragment`
- add `getHtmlStringOutput()` util to get HTML from any type of input (string, number, HTMLElement or DocumentFragment), which is especially useful with `DocumentFragment` which doesn't return HTML by default
I think (hope) this is the last piece to convert to native element for CSP safe approach
=> feat: convert CheckSelectColumn plugin to native HTML for CSP safe code

packages/common/src/core/slickGrid.ts
- since we always assign `cell = 0` at the start, the `cell < -1` is technically unreachable, so there's no need to keep it
=> chore: remove `getCellFromPoint()` unreachable code

packages/common/src/core/slickGrid.ts
- this PR replicates an old SlickGrid PR (except the focus which can cause other issues) https://github.com/mleibman/SlickGrid/pull/616 
- it also adds the `tabIndex: -1` on the cell which was mentioned in the issue and it seems to work the same as Ag-Grid does, with keyboard navigation so it looks ok to me
- fixes an issue on SlickGrid project, but maybe just partially, I'm not sure since I'm a newbie with these accessibility stuff and nobody wants to help much so... pushing this PR and closing the ref issue
=> fix: add grid & cell `role` for screen ready accessibility

packages/common/src/core/slickInteractions.ts
- when `onResizeStart` returns `false`, for example when editor `commitCurrentEdit()` fails, then the column resize shouldn't be allowed
https://github.com/ghiscoding/slickgrid-universal/blob/bc4402a1ee53de0e4333a8900e95207ec9b39cde/packages/common/src/core/slickGrid.ts#L1906-L1910
=> fix: when `onResizeStart` return false it should stop

packages/common/src/extensions/__tests__/slickCellSelectionModel.spec.ts, packages/common/src/extensions/__tests__/slickRowSelectionModel.spec.ts, packages/common/src/extensions/slickCellSelectionModel.ts, packages/common/src/extensions/slickRowSelectionModel.ts
- a regression was introduced when dropping jQuery, the SlickEvent structure changed in the `notify` function. Previously a SlickEvent would accept a CustomEvent directly and the previous code was expecting that event to exists and override its CustomEvent `detail`, however the newer approach is to always use a SlickEventData and no longer use the CustomEvent directly and this caused the regression since the SlickEventData doesn't have a `detail` property but rather something like this `SlickEventData { event: { detail } }`
- the fix is to simply create a CustomEvent with `{ detail: caller }` which we then pass to the `SlickEventData` constructor so that our `caller` isn't lost and rather reused later when triggered by `onSelectedRowsChanged`
=> fix: regression `onSelectedRowsChanged` not receiving correct `caller`

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/services/resizer.service.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- when loading a new grid, we are calling `grid.autosizeColumns()` to resize the columns and while adding tests for that method I incidently discovered that it was being called multiple times on a page load (up to 6-8x times) but in reality there is no need to call it more than once or twice.
- there is also no need to call the `autosizeColumns` if the grid dimension calculated by the Resizer Service are the same as the previously calculated dimensions
- the updated code will never call `autosizeColumns` more than twice on a page load, however note that the method will always be called whenever the grid dimensions or columns get updated
=> perf(resizer): `autosizeColumns` is called too many times on page load

packages/common/src/core/slickGrid.ts, packages/utils/src/domUtils.ts
- using the `classNameToList()` util, we can permit any amount of spaces to css classes like Formatter `addClasses`
- also cleanup and simplify some code around other css classes, `classNameToList` returns an array of string and we can take advantage of iterator available in DOM `classList.add()` and `.remove()`
=> fix(core): allow extra spaces to be striped to any css classes

examples/vite-demo-vanilla-bundle/src/examples/example11.ts, test/cypress/e2e/example11.cy.ts
- there was a condition check in the Cypress tests to assume that the first few rows have their value greater than x, but with a limited dataset that test was flaky and failing from time to time, doublding the dataset size will remove the flakiness
=> chore(tests): add more rows to dataset to fix Cypress flakiness

.github/workflows/main.yml, test/jest.config.ts
- codecov seems to fail quite often and it requires to retry the entire workflow to republish the test results, adding a retry plugin seems like a good fit
=> chore: add codecov publish retries since it often fails

packages/common/src/styles/_variables.scss
It looks a little weird that the locked (unorderable) columns have different background-color especially when our grid doesn't have any borders around the headers. So I think it's better to remove it and fix the styling discrepancy by using the same bg-color for all column headers but keeping the SASS variable in case the user still want to change it
=> fix(styling): remove different bg-color on unorderable column

examples/vite-demo-vanilla-bundle/src/translate.service.ts, packages/common/src/extensions/extensionUtility.ts, packages/common/src/services/__tests__/extension.service.spec.ts, packages/common/src/services/extension.service.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
found a couple of places in the code where it was translating the same things more than once
- `translateAllExtensions()` is calling translate on all extensions including a call to `translateColumnHeaders()` but that one was also calling GridMenu translates which was already translated, instead we can expect that `translateColumnHeaders()` should also indirectly translate both ColumnPicker/GridMenu only once inside `renderColumnHeaders()` when reassigning translated `columns`
- also `translateColumnHeaders()` will indirectly call a `grid.invalidate()` so I think this call should be made last in `translateAllExtensions()` so that everything else had a chance to be translated prior to reaching the invalidate
- `onLanguageChange` is calling `translateAllExtensions()` but was also calling …
=> perf(plugins): decrease number of calls to translate all extensions only once

packages/common/src/editors/__tests__/autocompleterEditor.spec.ts, packages/common/src/editors/__tests__/selectEditor.spec.ts, packages/common/src/services/__tests__/grid.service.spec.ts, packages/common/src/services/grid.service.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, packages/vanilla-force-bundle/src/__tests__/vanilla-force-bundle.spec.ts, test/cypress/e2e/example17.cy.ts, test/translateServiceStub.ts
- with the previous implementation when dataset was provided through the constructor, it was internally calling `dataView.setItems(data)` twice, this PR will now only call it once and is much closer to the other repos implementation which didn't have this issue (like Angular-Slickgrid is fine, or actually it's calling twice but the first time is always empty so it doesn't have any impact)
- remove unnecessary calls to `grid.invalidate()`
- remove unnecessary calls to `grid.render()` when `grid.invalidate()` is called just before, it is unnecessary since that the invalidate already calls the render internally, so no need to do the same thing twice
=> perf: decrease calls to setItems & grid invalidate

packages/common/src/extensions/slickRowBasedEdit.ts
- when adding console logs to see why some of the buttons weren't translated, I discovered that it was calling the translate function on every single dataset row because of the Formatter, however once we have the translation we shouldn't have to retranslate the same tooltip texts over and over
=> perf(plugins): Row Base Editing tooltip title translate only once

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/filter-conditions/__tests__/filterUtilities.spec.ts, packages/common/src/filter-conditions/filterUtilities.ts, packages/row-detail-view-plugin/src/slickRowDetailView.ts
- as mentioned in this [Stack Overflow](https://stackoverflow.com/a/43446317/1212166), `Object.keys().forEach` are quicker than `for..in` because the latter also loops through prototype chain.
=> perf(core): convert `for..in` to `Object.keys().forEach` for better perf

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts
- follows SlickGrid PR which fixes an issue identified in SlickGrid demo with frozen column and hidding a column
- the `hidden` property will completely remove the column from the DOM
- ref SlickGrid [PR](https://github.com/6pac/SlickGrid/pull/985)
=> fix(core): frozen grid w/hidden column should remove from DOM

.github/workflows/cypress.yml, .github/workflows/main.yml, .github/workflows/publish-npm-latest.yml, .github/workflows/publish-npm-prerelease.yml, .github/workflows/publish-npm-prompt.yml
- latest pnpm action is using Node 20 and drops Node 16 which is EOL
=> chore(deps): update to latest pnpm action v3

.github/workflows/publish-npm-latest.yml, .github/workflows/publish-npm-prerelease.yml, .github/workflows/publish-npm-prompt.yml
- as per issue identified in this [comment](https://github.com/ghiscoding/slickgrid-universal/pull/1385#issuecomment-1940388130)
- Husky that was added recently and caused an issue with the last release, the typical `chore(release)` commit was completely missing in today's release, possibly because of a racing condition or a prompt that cannot be answered in a CI environment
- as per Husky [docs](https://typicode.github.io/husky/how-to.html#ci-server-and-docker) we can disable Husky via 
```sh
env:
HUSKY: 0
```
=> fix(ci): disable Husky when pushing new release

examples/vite-demo-vanilla-bundle/src/material-styles.scss, packages/common/src/styles/_variables.scss
- this is a very small border color difference (`#aaa` instead of `#ccc` for all other filters, so ms-select were standing out because their border were slightly darker). The filled ms-select filter(s) also had a background gray color that was merging with the primary box shadow color (green below) which was not a pure color, now it's all good.
=> fix(styling): ms-select filter should use same color as other filters

examples/vite-demo-vanilla-bundle/src/examples/example07.ts, examples/vite-demo-vanilla-bundle/src/material-styles.scss, packages/common/src/styles/_variables-theme-material.scss, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-plugins.scss
- the ms-select icon+text label was never fully aligned in the middle, this PR fixes that by taking more advantage of flexbox. See print screen below, note that it wasn't by much, just an offset of a pixel or 2 (icon was slightly lower than the text position) but with this PR change, they are perfectly aligned 
- improve Material theme by increasing ms-select icon size 
- also fix wrong Material theme color used in demo for ms-select
_icon was slightly lower than text_
=> fix(styling): properly align flexbox ms-select icon+text vertically

examples/vite-demo-vanilla-bundle/package.json, packages/common/package.json, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-plugins.scss, pnpm-lock.yaml, test/jest-global-mocks.ts
- see `multiple-select-vanilla` [v2](https://github.com/ghiscoding/multiple-select-vanilla/releases/tag/v2.0.0) release for more info.
- the main difference is mostly a UX change that switches from `tabIndex` to arrow navigation highlight. Except the UX changes, the upgrade is mainly transparent for most users.
=> feat(common): upgrade `multiple-select-vanilla` to v2

packages/binding/package.json, packages/common/package.json, packages/composite-editor-component/package.json, packages/custom-footer-component/package.json, packages/custom-tooltip-plugin/package.json, packages/empty-warning-component/package.json, packages/event-pub-sub/package.json, packages/excel-export/package.json, packages/graphql/package.json, packages/odata/package.json, packages/pagination-component/package.json, packages/row-detail-view-plugin/package.json, packages/rxjs-observable/package.json, packages/text-export/package.json, packages/utils/package.json, packages/vanilla-bundle/package.json, packages/vanilla-force-bundle/package.json
- we no longer need to specify TypeScript >=4.2 min version since at this point v4.2 is 3 years old, so most users have already upgraded. The TS builds changed after TypeScript v3.7 which is even older and even then the prior code was simply throwing anyway when using a version below 4.2 since it had no Types exports associated
=> feat(deps): simplify package TS Types exports

packages/common/src/extensions/__tests__/slickRowMoveManager.spec.ts, packages/common/src/extensions/slickRowMoveManager.ts
- cell that aren't selectable are not styled with bg-color when selecting full row
=> fix(plugin): the RowMove plugin cell should be selectable

examples/vite-demo-vanilla-bundle/src/examples/example12.ts, packages/common/src/interfaces/compositeEditorOpenDetailOption.interface.ts, packages/composite-editor-component/src/slick-composite-editor.component.spec.ts, packages/composite-editor-component/src/slick-composite-editor.component.ts
- with the new Dark Mode, we needed a way to add attributes to the composite modal element when using Bootstrap, this new lifecycle is to help with that
=> feat(editor): add Composite Editor `onRendered` lifecycle callback option

docs/events/Available-Events.md, packages/common/src/core/slickGrid.ts, packages/common/src/extensions/__tests__/slickCheckboxSelectColumn.spec.ts, packages/common/src/extensions/slickCheckboxSelectColumn.ts, packages/common/src/interfaces/gridEvents.interface.ts
- when using Row Selections grid option, the Select All checkbox was disappearing after toggling Dark Mode, that was caused by the fact that calling `grid.setOptions()` is recreating the header columns and the Select All itself is not being recreated
- also the same issue happened whenever reordering a column to another position because again it called the grid set columns and that again rerendered all column headers without the Select All
- to fix both issue, I added a new `onAfterSetColumns` SlickEvent which we subscribe to inside the SlickCheckboxSelectColumn plugin, and whenever triggered, we reevaluate the Select All which in term recreates it
below are the 2 problems identified that were fixed by this PR
=> fix(common): Select All checkbox shouldn't disappear w/Dark Mode toggle

packages/common/src/core/slickGrid.ts, packages/common/src/interfaces/column.interface.ts, packages/common/src/interfaces/editor.interface.ts, packages/common/src/interfaces/editorArguments.interface.ts, packages/common/src/interfaces/gridOption.interface.ts
as per SlickGrid [PR 995](https://github.com/6pac/SlickGrid/pull/995)
> editor and editor factory do not return an Editor Object but a typeof Editor to be constructed with new (...) Otherwise it is impossible to implement an Editor Factory in TypeScript
=> fix: `column.editor` and `gridOptions.editorFactory` type changed

packages/common/src/filters/autocompleterFilter.ts, packages/common/src/filters/compoundDateFilter.ts, packages/common/src/filters/compoundInputFilter.ts, packages/common/src/filters/compoundInputNumberFilter.ts, packages/common/src/filters/compoundInputPasswordFilter.ts, packages/common/src/filters/compoundSliderFilter.ts, packages/common/src/filters/dateFilter.ts, packages/common/src/filters/dateRangeFilter.ts, packages/common/src/filters/inputFilter.ts, packages/common/src/filters/inputMaskFilter.ts, packages/common/src/filters/inputNumberFilter.ts, packages/common/src/filters/inputPasswordFilter.ts, packages/common/src/filters/multipleSelectFilter.ts, packages/common/src/filters/nativeSelectFilter.ts, packages/common/src/filters/selectFilter.ts, packages/common/src/filters/singleSelectFilter.ts, packages/common/src/filters/singleSliderFilter.ts, packages/common/src/filters/sliderFilter.ts, packages/common/src/filters/sliderRangeFilter.ts, packages/common/src/interfaces/columnFilter.interface.ts, packages/common/src/interfaces/filter.interface.ts
- add a `FilterConstructor` type on the `model` prop of a Column filter, this is similar to the recently added `EditorConstructor` type for Editor
=> fix(common): add missing Filter `model` Type of `FilterConstructor`

packages/binding/package.json, packages/common/package.json, packages/composite-editor-component/package.json, packages/custom-footer-component/package.json, packages/custom-tooltip-plugin/package.json, packages/empty-warning-component/package.json, packages/event-pub-sub/package.json, packages/excel-export/package.json, packages/graphql/package.json, packages/odata/package.json, packages/pagination-component/package.json, packages/row-detail-view-plugin/package.json, packages/rxjs-observable/package.json, packages/text-export/package.json, packages/utils/package.json, packages/vanilla-bundle/package.json, packages/vanilla-force-bundle/package.json
- a recent commit made the `exports` a bit simpler but displays 1 unexpected syntax error on [are the types wrong](https://arethetypeswrong.github.io/?p=%40slickgrid-universal%2Fcommon%404.6.0)
- use the same `exports` that we use in `multiple-select-vanilla` since that one doesn't display that error
=> fix: revisit package `exports` to pass "are the types wrong"

examples/vite-demo-vanilla-bundle/src/examples/example12.ts, packages/common/src/core/__tests__/slickCore.spec.ts, packages/common/src/core/slickCore.ts, packages/event-pub-sub/src/eventPubSub.service.spec.ts, packages/event-pub-sub/src/eventPubSub.service.ts, packages/event-pub-sub/src/types/basePubSubService.interface.ts, packages/row-detail-view-plugin/src/slickRowDetailView.spec.ts
- add a way to externalize the Custom Event used internally by the PubSub Service so that the user could call `preventDefault()` on the SlickEventData as well, for example the CompositeEditor demo has the event `onBeforeEditCell` and if the user calls the `preventDefault` even on the SlickEventData (e.g. with Aurelia or Angular), then the SlickGrid `.notify` should receive a `returnValue` of `false` because when the PubSub calls the `dispatchEvent` with an event that was prevented, then the `returnValue` will be `false`, see MDN for reference: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent#return_value
- this fixes an issue that I've opened on Aurelia project via this issue [comment](https://github.com/aurelia/aurelia/pull/1926#issuecomment-2017270871) and …
=> fix(pubsub): externalize PubSub event to SlickEventData to stop bubbling

docs/events/Available-Events.md, examples/vite-demo-vanilla-bundle/src/examples/example11.ts, examples/vite-demo-vanilla-bundle/src/examples/example12.ts, examples/vite-demo-vanilla-bundle/src/examples/example16.scss, examples/vite-demo-vanilla-bundle/src/examples/example16.ts, examples/vite-demo-vanilla-bundle/src/examples/example22.ts, packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/interfaces/customTooltipOption.interface.ts, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-plugins.scss, packages/custom-tooltip-plugin/src/__tests__/slickCustomTooltip.spec.ts, packages/custom-tooltip-plugin/src/slickCustomTooltip.ts, test/cypress/e2e/example11.cy.ts, test/cypress/e2e/example12.cy.ts, test/cypress/e2e/example16.cy.ts, test/cypress/e2e/example22.cy.ts, test/mockSlickEvent.ts
- prior to this PR, we could only have 1 tooltip per cell, but in some occasions, we might have a cell with multiple icons & tooltips, if that happens then we should have separate tooltips (with their dedicated & different tooltipt text) positioned on that inner icon
- this actually requires new SlickEvents because the existing events for header/headerRow are using `mouseenter` but we need `mouseover` to differentiate multiple tooltip within the same header (`mouseenter` only gets triggered once while `mouseover` gets triggered multiple times while hovering any of element within container). So instead of possible chaning the previous behavior, I decided to duplicate `onHeaderMouseEnter` to `onHeaderMouseOver` and the same goes for `onHeaderRowMouseEnter` and also `...MouseOut` for both …
=> fix(tooltip): allow multiple tooltips per grid cell

packages/common/package.json, packages/common/src/commonEditorFilter/commonEditorFilterUtils.ts, packages/common/src/editors/autocompleterEditor.ts, packages/common/src/filters/autocompleterFilter.ts, packages/common/src/interfaces/autocompleterOption.interface.ts, pnpm-lock.yaml
- migrate to a temp package `autocompleter-es` until my opened PR on `autocompleter` is merged and hopefully release sometime in the future.
- the goal of this switch is to have an ESM build so that we can remove it from `allowedCommonJsDependencies` (`angular.json`) for Angular-Slickgrid to have 1 less CJS dependency
=> fix(common): switch to `autocompleter-es` to get ESM build

packages/common/package.json, packages/common/src/commonEditorFilter/commonEditorFilterUtils.ts, packages/common/src/editors/autocompleterEditor.ts, packages/common/src/filters/autocompleterFilter.ts, packages/common/src/interfaces/autocompleterOption.interface.ts, pnpm-lock.yaml
- the PR that I've opened on the `autocompleter` repo got merged and released, so I can switch back to the original repo and take advantage of the new ESM build
=> fix(common): switch back to `autocompleter` with ESM build

packages/common/src/services/resizer.service.ts
- when calculating cell content width, we parse the cell data to its Formatter if it exists but if it doesn't then in some cases it could return the entire dataContext and that would then throw when passed to `stripTags()` method, for these cases we can simply assume that the cell width is not calculable since the cell data is not a primitive result (not text, boolean,, number nor HTML)
=> fix(common): don't try to strip tags on object input to calc cell width

packages/common/src/core/__tests__/slickDataView.spec.ts, packages/common/src/core/slickDataview.ts
as per original SlickGrid [PR 1007](https://github.com/6pac/SlickGrid/pull/1007)
> It would be very handy for developers to have ability to receive extra arguments of filter function. For example when filter is applyed we can:
> 
> * write a custom date editor which can suggest a year for user, relying on the selected year filter;
> * fill cell values automatically when adding a new row, otherwise the row will not be displayed;
> * and much more.
> 
> Previously there was ability to receive extra arguments of filter function by using `dataView.filters` property and much featers have already been written by using it. Now we need a way to keep these features working.
=> feat(core): add `getFilterArgs()` to `SlickDataView`

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/interfaces/editor.interface.ts
as per original SlickGrid [PR 1006](https://github.com/6pac/SlickGrid/pull/1006)
> The 'keyCaptureList' variable of the Editor class is an array of numbers.
=> fix(core): Editor.keyCaptureList is an array of numbers

packages/graphql/src/services/__tests__/graphql.service.spec.ts, packages/graphql/src/services/graphql.service.ts, packages/odata/src/services/__tests__/grid-odata.service.spec.ts, packages/odata/src/services/grid-odata.service.ts
this fixes the wrong operator comparison, causing FieldTypes.date in OData to be always checked with the `eq` operator, regardless of the users definition
=> fix: wrong operator comparison

examples/vite-demo-vanilla-bundle/src/examples/example12.ts, examples/vite-demo-vanilla-bundle/src/examples/example22.ts, package.json, packages/common/src/extensions/__tests__/slickCellExternalCopyManager.spec.ts, packages/common/src/extensions/slickCellExternalCopyManager.ts, pnpm-lock.yaml, test/cypress/e2e/example22.cy.ts, test/cypress/support/commands.ts, test/tsconfig.json
this is both a new feature and a bug fix.
Now when pasting if the target cell has an editor with a validator, and that one returns invalid, the onValidationError event will be triggered.
But far more sever is that the paste on target cells with editors was currently broken.
See when going to https://ghiscoding.github.io/slickgrid-universal/#/example22, setting any row into edit mode, and pasting a number from Excel lets say into the column Completion. (check the devtools).
This regression somewhat was related to this PR https://github.com/ghiscoding/slickgrid-universal/pull/1429
=> feat: notify onValidationError on paste if validation failed

.github/workflows/main.yml, packages/common/src/editors/sliderEditor.ts, packages/common/src/extensions/slickCellExternalCopyManager.ts, packages/common/src/interfaces/editorArguments.interface.ts, packages/composite-editor-component/src/compositeEditor.factory.ts
- this is extends previous PR #1462 which is now using `editorClass` but was missing the correct type of `EditorConstructor` and we should use it whenever possible (instead of `any` to get rid of the typing issue)
=> chore(common): add `EditorConstructor` type whenever possible

packages/common/src/core/slickGrid.ts
- fixes issue #1475
- when unselecting any column from ColumnPicker/GridMenu it was causing columns created from native HTML element to disappear, I'm not exactly sure why but it looks like if I clone the node before calling `.appendChild` then the problem no longer exists. For reference, the issue is from these lines https://github.com/ghiscoding/slickgrid-universal/blob/185b6f9e44400bec2f1d79568905ca79e4b338a5/packages/common/src/core/slickGrid.ts#L1615-L1616
=> fix(core): col name from HTML shouldn't disappear in picker, fixes #1475

packages/common/src/core/slickGrid.ts
- this follows original SlickGrid [PR 1016](https://github.com/6pac/SlickGrid/pull/1016) to address a bug found in that repo
=> fix: tweak setupColumnSort() to fix exception when col no longer exists

docs/column-functionalities/editors/Select-Dropdown-Editor-(single,multiple).md, docs/column-functionalities/filters/Select-Filter.md, docs/migrations/migration-to-5.x.md, examples/vite-demo-vanilla-bundle/src/examples/example10.ts, examples/vite-demo-vanilla-bundle/src/examples/example11.ts, examples/vite-demo-vanilla-bundle/src/examples/example12.ts, packages/common/src/filters/__tests__/selectFilter.spec.ts, packages/common/src/index.ts, packages/common/src/interfaces/columnEditor.interface.ts, packages/common/src/interfaces/columnFilter.interface.ts, packages/common/src/interfaces/gridOption.interface.ts
- re-exporting is typically discouraged by the TypeScript team, so let's stop doing that and ask the user to import it directly from the ms-select external lib
=> chore: don't re-export ms-select interface

examples/vite-demo-vanilla-bundle/src/examples/example07.scss, examples/vite-demo-vanilla-bundle/src/examples/example07.ts, examples/vite-demo-vanilla-bundle/src/examples/example12.ts, examples/vite-demo-vanilla-bundle/src/examples/example14.ts, examples/vite-demo-vanilla-bundle/src/examples/example16.ts, examples/vite-demo-vanilla-bundle/src/styles.scss, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-grid.scss
- add new `--slick-cell-display` CSS variable to optionally change `display` to `flex` for aligning middle but keep `block` as default
=> chore(styling): add CSS variable for .slick-cell optional flex

packages/common/src/styles/slick-component.scss, packages/empty-warning-component/src/slick-empty-warning.component.ts, packages/empty-warning-component/src/slick-empty-warning.spec.ts, packages/vanilla-force-bundle/src/salesforce-global-grid-options.ts
- the previous code was using the `:before` pseudo and we were able to add text to the same div but that is no longer feasible with the new pure CSS icons since the div is the icon and nothing else, so the text has to be in a separate div
- also use flex to align the text and icon in the middle
=> fix(styling): empty warning should separate icon & text

examples/vite-demo-vanilla-bundle/package.json, package.json, packages/common/package.json, packages/common/src/styles/_variables.scss, packages/common/src/styles/slickgrid-theme-bootstrap.scss, packages/common/src/styles/slickgrid-theme-material.scss, packages/common/src/styles/slickgrid-theme-salesforce.scss, packages/vanilla-bundle/package.json, pnpm-lock.yaml
- we should have only 1 import and for it to be properly imported in SASS, we need to remove the file externsion when importing
- fixes invalid import and missing CSS when tested in Salesforce
=> fix(styling): properly import Vanilla-Calendar CSS and only once

examples/vite-demo-vanilla-bundle/package.json, examples/vite-demo-vanilla-bundle/src/examples/example05.scss, examples/vite-demo-vanilla-bundle/src/examples/example06.scss, examples/vite-demo-vanilla-bundle/src/examples/example21.scss, packages/common/package.json, packages/common/src/styles/slick-component.scss, packages/common/src/styles/slick-editors.scss, packages/common/src/styles/slick-plugins.scss, pnpm-lock.yaml
- when using flex on `.slick-cell` like in Example 7, a couple of small issues came up mostly with flex alignment
- also fix some flex issues directly in ms-select lib and update it here to get fixes, also remove some now duplicate CSS
- we should use `column-gap` instead of `gap` to only change the gap horizontally but not vertically
=> fix(styling): couple of small alignment issues when using flex

packages/common/src/core/slickGrid.ts, packages/custom-tooltip-plugin/src/slickCustomTooltip.ts
- the previous code was having a simple check of the final output text, however when using DOMPurify it returns a TrustedHTML object which is considered defined even though it could be empty.
- we can fix the issue via 2 changes (1. sanitize only string value, 2. check tooltip value against `toString()`
=> fix(tooltip): only show tooltip that has value

examples/vite-demo-vanilla-bundle/package.json, packages/common/package.json, packages/common/src/editors/__tests__/multipleSelectEditor.spec.ts, packages/common/src/editors/longTextEditor.ts, packages/common/src/editors/selectEditor.ts, pnpm-lock.yaml
- the issue was fixed in upstream lib ms-select-vanilla
=> fix(common): Select Editor should always close with Escape key

examples/vite-demo-vanilla-bundle/package.json, packages/common/package.json, packages/common/src/editors/__tests__/selectEditor.spec.ts, packages/common/src/editors/selectEditor.ts, pnpm-lock.yaml
- add reason to `onClose(reason)` feature in external repo
- Escape key should cancel any edit change (that would mostly only happen when multiple selection since single select would close after single selection
- when clicking outside the select (body click), wouldn't call a save either
=> fix(editors): body click or Escape key should cancel Select Editor

packages/common/src/services/filter.service.ts, packages/composite-editor-component/src/slick-composite-editor.component.ts, packages/excel-export/src/excelExport.service.ts, packages/text-export/src/textExport.service.ts, packages/utils/src/nodeExtend.ts, packages/utils/src/utils.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- I created `deepCopy` before adding node-extend, I think that we no longer need the implementation of `deepCopy()`, however to avoid breaking users of the function, I'll keep it in place but simply call `extend()` behind the scene. However, there are 2 simple checks that need to be performed before calling node-extend.
- node-extend has the exact same usage as jQuery.extend(), you can see jQuery's doc for more demos
=> chore: use node-`extend()` from within `deepCopy`

examples/vite-demo-vanilla-bundle/src/examples/example08.ts, packages/common/src/extensions/slickGridMenu.ts, packages/common/src/interfaces/gridMenuOption.interface.ts
- add `iconButtonContainer: 'preheader' | 'header'` grid option (default to `'header'`). For example, the Grid Menu is shown in the Draggable Grouping drop zone but it should really be in the Column Header section, we'll change the default to `'header'` but let's add a grid option to let the user choose either `'preheader'` or `'header'`
=> fix(plugin): Grid Menu shouldn't be displayed in preheader by default

examples/vite-demo-vanilla-bundle/package.json, packages/common/package.json, pnpm-lock.yaml, test/cypress/e2e/example15.cy.ts
- when Row Selection in combo with single click open Editor, it was selecting the row and conflicting with the ms-select open, the issue was caused by a 0ms delay to open the ms-select editor and by the time it was calling open (after delay), the ms-select was in fact destroyed already because of the row selection causing a phantom select in top left corner that wasn't being removed and became an orphan element
=> fix(editors): only open ms-select drop when exists

examples/vite-demo-vanilla-bundle/src/examples/example14.ts, test/cypress/e2e/example14.cy.ts
- improves SQL LIKE filter predicate demo by using Regex, I'm not exactly sure why `.match()` doesn't return all matches while `.matchAll()` does, but anyway that is what works so let's go with that even it's more bulky (it's just for demo purposes anyway).
=> chore(demo): improve SQL LIKE filter predicate example

examples/vite-demo-vanilla-bundle/src/examples/example14.ts, packages/common/src/services/filter.service.ts, test/cypress/e2e/example14.cy.ts
- the previous PR to implement `filterPredicate` regressed with a new issue and that was not caught in the original PR. It had the indirect effect of breaking the other filter columns (I forgot to test that in the original PR), the issue was caused by the fact that calling a `return` within the `for` loop of all filters was cancelling all other filters in the loop because a `return` breaks the entire loop.
- So the fix is to only call `return` when the `filterPredicate` returns `false` which mean that at point the row data context is officially filtered out and so stopping inspection of further filters does make sense at that point in time.
- also improve SQL LIKE with filter of `Ta%30%`, it wasn't working correctly before and it is now equivalent to: StartsWith "Ta" and Contains "30" …
=> fix(filters): new `filterPredicate` shouldn't break other column filters

examples/vite-demo-vanilla-bundle/src/examples/example09.ts, examples/vite-demo-vanilla-bundle/src/examples/example15.ts, packages/common/src/services/__tests__/pagination.service.spec.ts, packages/common/src/services/pagination.service.ts
- in the OData example, we have a Grid Preset of page number 2 and that demo also uses local storage, if we keep the Gender filter and also add a Name filter like "G", it results to a total of 9 items and it works fine unless we refresh the page. After a page refresh, and when our page size is set to 20, we are now out of bound and the 9 items weren't showing up because the system thought it was on page 2 even though we shouldn't... So let's make sure to never be out of boundaries and reset to first page when that happens (or page 0 when no items found)
- a side note, I the issue described above and shown below would probably never happened with a real server since the OData server would never return a page number that is outside of boundaries, which is probably why no one ever reported …
=> fix(pagination): out of boundaries page Grid Preset should be unset

packages/common/src/core/__tests__/slickInteractions.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/core/slickInteractions.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/interfaces/interactions.interface.ts
- the issue was brought in discussion #1537, the root cause was the mouse drag sometime kicks in when the user selects a few row by using the Ctrl+click combo, however in rare occasion the user might move by even a single pixel and that sends an onDrag event which the SlickCellRangeSelector picks up when then sends a new event `onCellRangeSelecting` and then the SlickRowSelectionModel assumes it's a new range from a mouse drag and override the previous range. However we should really prevent this mouse drag from happening when the user is pressing the Ctrl/Shift keys to avoid having the issue brought in #1537
=> feat(core): add new `preventDragFromKeys` grid option, fixes #1537

docs/column-functionalities/filters/compound-filters.md, packages/common/src/filters/__tests__/compoundDateFilter.spec.ts, packages/common/src/filters/__tests__/compoundInputFilter.spec.ts, packages/common/src/filters/__tests__/compoundSliderFilter.spec.ts, packages/common/src/filters/dateFilter.ts, packages/common/src/filters/filterUtilities.ts, packages/common/src/filters/inputFilter.ts, packages/common/src/filters/sliderFilter.ts
- instead of applying the Compound Operator alternate texts from `compoundOperatorNumeric` or `compoundOperatorString` only, we should instead apply the alt texts after either a custom list or a fixed list from mentioned functions.
=> fix(filters): Compound Operator alt texts should work with custom list

packages/common/src/core/slickGrid.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/gridOption.interface.ts
- also use `auto` instead of `100%` to take full width but without being wider than its actual container
=> chore(plugin): move `preHeaderPanelWidth` to SlickGrid core defaults

docs/grid-functionalities/Export-to-Excel.md, examples/vite-demo-vanilla-bundle/src/app-routing.ts, examples/vite-demo-vanilla-bundle/src/app.html, examples/vite-demo-vanilla-bundle/src/examples/example23.html, examples/vite-demo-vanilla-bundle/src/examples/example23.scss, examples/vite-demo-vanilla-bundle/src/examples/example23.ts, packages/common/src/interfaces/columnExcelExportOption.interface.ts, packages/excel-export/src/excelExport.service.spec.ts, packages/excel-export/src/excelExport.service.ts, packages/excel-export/src/excelUtils.spec.ts, packages/excel-export/src/excelUtils.ts, test/cypress/e2e/example23.cy.ts
- the `excelExportOptions.valueParserCallback` was missing the dataContext which can be useful when the exported data is not the current cell value but another cell value, for example our cell is Total but is a calculated value from 2 other column dataContext (Price & Qty)
- fix a bug found with new demo, the `excelExportOptions.style` wasn't being applied on regular data cell
- add a new Example 23 to demo Excel Export with Formula
- the new demo was created with the following logic (there are 3 calculated fields: SubTotal, Taxes & Total)
- (in UI) - use Custom Formatters for calculated fields
- (Excel Export) - use Excel Formula for calculated fields (via `excelExportOptions.valueParserCallback`)
- I forgot that for Groups, we actually have `groupTotalsExcelExportOptions` which I had to …
=> feat(export): add missing `valueParserCallback` dataContext & new demo

docs/backend-services/graphql/GraphQL-Filtering.md, docs/grid-functionalities/Export-to-Excel.md, examples/vite-demo-vanilla-bundle/src/examples/example10.html, examples/vite-demo-vanilla-bundle/src/examples/example10.ts, examples/vite-demo-vanilla-bundle/src/examples/example23.ts, packages/graphql/src/interfaces/graphqlFilteringOption.interface.ts, packages/graphql/src/interfaces/graphqlServiceOption.interface.ts, packages/graphql/src/services/__tests__/graphql.service.spec.ts, packages/graphql/src/services/graphql.service.ts, test/cypress/e2e/example10.cy.ts
- similar approach to PR #1536 but for GraphQL Service
- adds a custom `filterQueryOverride` which provides a way for the user to override default filter operator and GraphQL query
=> feat(GraphQL): add `filterQueryOverride` to GraphQL Service

packages/common/src/services/filter.service.ts, packages/common/src/services/pagination.service.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- the `setTimeout` in some cases were used as a way to execute certain things after all other tasks are finished, but some cases we `queueMicrotask(f)`, see this article: https://javascript.info/event-loop#macrotasks-and-microtasks
- I tested a Tree Data grid that we have in Salesforce and it's still working as expected, most of the code change in here is related to Tree Data
=> chore: migrate some `setTimeout` to `queueMicrotask`

packages/common/src/extensions/__tests__/slickDraggableGrouping.spec.ts, packages/common/src/extensions/extensionCommonUtils.ts, packages/common/src/extensions/slickDraggableGrouping.ts
- Draggable Grouping reimplements `enableColumnReorder` grid option and also the `onColumnsReordered` SlickEvent, the later one was missing the `impactedColumns` argument needed by Slickgrid-Universal to reorder and/or freeze columns
Fixes issue shown in animated gif below
=> fix(Grouping): Draggable Grouping cols reorder missing `impactedColumns`

docs/grid-functionalities/grouping-aggregators.md, examples/vite-demo-vanilla-bundle/src/examples/example03.ts, packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/extensions/__tests__/slickDraggableGrouping.spec.ts, packages/common/src/extensions/slickDraggableGrouping.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/services/groupingAndColspan.service.ts, packages/common/src/styles/slick-grid.scss, packages/common/src/styles/slick-plugins.scss, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, packages/vanilla-force-bundle/src/__tests__/vanilla-force-bundle.spec.ts, packages/vanilla-force-bundle/src/vanilla-force-bundle.ts, test/cypress/e2e/example02.cy.ts, test/cypress/e2e/example03.cy.ts
- prior to this PR, we could not use Draggable Grouping & Header Grouping because both features were using the pre-header and it would have conflict, now to avoid this I am adding an extra Top-Header that will show over all header and pre-header.
- NOTE: Draggable Grouping can now be displayed in either the new Top-Header OR the Pre-Header. However, the users who do want to use both features will need to explicitely enable both top/pre headers.
- I was getting a little out of ideas to get a name (since "pre" is already taken), so I decided to go with Top-Header which is completely on the top and even before the pre-header. 
- Another note is that this new Top-Header is not following the frozen columns (like header & pre-header do) and is rather always the same width as the grid. I …
=> feat(core): add optional Top-Header for Drag Grouping & Header Grouping

examples/vite-demo-vanilla-bundle/src/examples/example05.html, examples/vite-demo-vanilla-bundle/src/examples/example05.ts, packages/common/src/services/__tests__/grid.service.spec.ts, packages/common/src/services/__tests__/treeData.service.spec.ts, packages/common/src/services/grid.service.ts, packages/common/src/services/treeData.service.ts, test/cypress/e2e/example12.cy.ts
- prior to this PR, calling `addItem()`, or `addItems()`, was always resorting using the Tree Data initial sort because the method being called is the same for the first build of the Tree Data and/or adding an item. So when we're adding an item, we should really reuse any existing sort that may exist when resynching the flat/hierarchical and resorting them (we always need to resort whenever it changes because by SlickGrid doesn't support Tree Data, we only support it by keeping copies of both flat & hierarchical and then resort them whenever something changes)
=> fix(TreeData): addItem should keep current sorted column

packages/common/src/styles/slick-plugins.scss
- the Column Picker & Grid Menu, cols picker list labels were not center aligned and were also not taking full width
- all the commands above already take full width, so it makes sense to also make picker list behave the same
=> fix(styling): Grid Menu, Col Picker labels should take full width

examples/vite-demo-vanilla-bundle/src/examples/example12.ts, packages/common/src/filters/__tests__/compoundDateFilter.spec.ts, packages/common/src/filters/__tests__/compoundInputFilter.spec.ts, packages/common/src/filters/dateFilter.ts, packages/common/src/filters/inputFilter.ts
- when enabling `skipCompoundOperatorFilterWithNullInput` it was only working the first time and if the user clicked on the input (or type something and then erases it), it no longer undefined and was no longer skipping null input like it should. So we simply need to compare against not just `undefined` but also against empty string `''` and if so then skip it filtering
- note however that we should only skip null value when previous value was not null so that we get full list back
=> fix(filters): skipCompoundOperatorFilterWithNullInput skip empty string

packages/common/src/filters/dateFilter.ts, packages/common/src/filters/sliderFilter.ts
- review Compound Date & Compound Slider Filters to be more aligned with Compound Input Text Filter after PR #1566
=> fix(filters): skipCompoundOperatorFilterWithNullInput skip undefined

docs/column-functionalities/filters/input-filter.md, examples/vite-demo-vanilla-bundle/src/examples/example11.ts, packages/common/src/filter-conditions/__tests__/stringFilterCondition.spec.ts, packages/common/src/services/__tests__/filter.service.spec.ts, packages/common/src/services/filter.service.ts, test/cypress/e2e/example11.cy.ts
- note that `!=` is "not equal" and is not equivalent to `<>` which is "not contains". So only the `!= ` will return non-blanks while `<> ` will often return no data at all when the data includes white spaces.
- partially fixes a problem highlighted in issue #1569 on how to return non-blanks rows for a local JSON dataset
=> fix(filters): filters with `!= ` (not equal empty) should return non-blanks

packages/common/src/services/__tests__/utilities.spec.ts, packages/common/src/services/utilities.ts, packages/graphql/src/services/__tests__/graphql.service.spec.ts
- while investigating for issue #1569, I found out that the GraphQL `<>` was set to be the equivalent of `!=` but this is in fact false, since the `<>` is meant to represent `Not_Contains` while `!=` is meant to represent `Not_Equals` and they both work differently since `<>` is for a substring but the `!=` is for the entire string
- it is also related to the PR #1570
- Note that OData doesn't have a "Not Contains" query filter and so I only made the modification for GraphQL (OData has its own switch case for each operator)
=> fix(GraphQL): filter `<>` is `Not_Contains` instead of `Not_Equal`

packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts, packages/common/src/extensions/menuBaseClass.ts
- the `action` callback arguments should always include the column definition which it was triggered from, but in the case of sub-menu it was missing because it wasn't propagated properly
=> fix(common): Header Menu missing columnDef in sub-menu action callback

docs/column-functionalities/filters/compound-filters.md, docs/column-functionalities/filters/input-filter.md, docs/column-functionalities/filters/range-filters.md, docs/column-functionalities/filters/select-filter.md, examples/vite-demo-vanilla-bundle/public/i18n/en.json, examples/vite-demo-vanilla-bundle/public/i18n/fr.json, examples/vite-demo-vanilla-bundle/src/examples/example10.html, examples/vite-demo-vanilla-bundle/src/examples/example10.ts, examples/vite-demo-vanilla-bundle/src/examples/example11.ts, packages/common/src/constants.ts, packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts, packages/common/src/extensions/slickHeaderMenu.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/columnFilter.interface.ts, packages/common/src/interfaces/headerMenuOption.interface.ts, packages/common/src/interfaces/locale.interface.ts, packages/common/src/styles/slick-plugins.scss, packages/utils/src/__tests__/utils.spec.ts, packages/utils/src/utils.ts, test/cypress/e2e/example10.cy.ts, test/cypress/e2e/example11.cy.ts, test/translateServiceStub.ts
closes #1569
- user will be able to declare some Filter Shortcuts that will be added to the Column Header Menu that the shortcuts were defined, it can be declared via an array that must include at least a `title` (or `titleKey`) and a `searchTerms` array, lastly an optional `operator` can also be provided
- the available properties of these shortcut is a merge of Header Menu Item (except `command` and `action` which are reserved) and an addition of our required props which are the extra `searchTerms` and `operator` (which as you can guess are the same props as a Column Filter for example what we use in `preset`)
- here's a code sample of it
```ts
this.columnDefinitions = [{
id: 'country', name: 'Country of Origin', field: 'country',
filter: {
model: Filters.inputText,
filterShortcuts: [
{ …
```
=> feat(filters): add new optional `filterShortcuts` to Column Filter

examples/vite-demo-vanilla-bundle/src/app-routing.ts, examples/vite-demo-vanilla-bundle/src/app.html, examples/vite-demo-vanilla-bundle/src/examples/example20.ts, examples/vite-demo-vanilla-bundle/src/examples/example24.html, examples/vite-demo-vanilla-bundle/src/examples/example24.ts, examples/vite-demo-vanilla-bundle/src/styles.scss, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-grid.scss, test/cypress/e2e/example24.cy.ts
- this new demo was mainly doable before but this PR also includes CSS styling fixes for the footer totals to show up correctly including fixes for the Dark Mode as well
=> feat(footer): add Footer Totals Row and fix footer styling

eslint.config.mjs, packages/binding/src/bindingEvent.service.ts, packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/extensions/__tests__/slickColumnPicker.spec.ts, packages/common/src/extensions/slickColumnPicker.ts, packages/common/src/interfaces/gridEvents.interface.ts, packages/common/src/services/__tests__/extension.service.spec.ts, packages/common/src/services/groupingAndColspan.service.ts, pnpm-lock.yaml, test/cypress/e2e/example03.cy.ts
- adding new events `onPreHeaderContextMenu` and `onPreHeaderClick` which is mostly to be able to open the Column Picker from either the regular column headers OR the Column Group from the Pre-Header when defined
- also works with/without frozen column
- Note: before calling the column picker, we need to make sure that the pre-header target element is in fact a column group, because if it's anything then we shouldn't open the column picker (e.g. draggable grouping dropzone)
=> feat(grouping): add onPreHeaderContextMenu for Column Picker usage

packages/custom-tooltip-plugin/src/__tests__/slickCustomTooltip.spec.ts, packages/custom-tooltip-plugin/src/slickCustomTooltip.ts
- slider tooltip is more useful when its tooltip is updated while sliding, the `onHeaderRowMouseEnter` was missing as a Custom Tooltip listener
=> fix(tooltip): Slider Filter should auto update tooltip whenever sliding

examples/vite-demo-vanilla-bundle/src/app-routing.ts, examples/vite-demo-vanilla-bundle/src/app.html, examples/vite-demo-vanilla-bundle/src/examples/example21.html, examples/vite-demo-vanilla-bundle/src/examples/example25.html, examples/vite-demo-vanilla-bundle/src/examples/example25.ts, packages/common/src/filters/dateFilter.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, test/cypress/e2e/example25.cy.ts
- calling Clear Filters, then Set Filters dynamically only worked once but not afterward
- create a new Example 25 Filter Ranges example that displayed the bug found in downstream repos
=> fix(filters): set date filter dynamically not always setting input value

examples/vite-demo-vanilla-bundle/src/material-styles.scss, packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts, packages/common/src/extensions/slickHeaderMenu.ts, packages/common/src/styles/_variables-theme-material.scss, packages/common/src/styles/_variables-theme-salesforce.scss, packages/common/src/styles/_variables.scss
- Header Menu wasn't always picking up dark mode styling especially when having multiple dark themes like in Slickgrid-Universal Material/Salesforce
=> fix(styling): add Dark Mode CSS class to Header Menu

examples/vite-demo-vanilla-bundle/src/examples/example14.ts, packages/common/src/filters/__tests__/sliderRangeFilter.spec.ts, packages/common/src/filters/sliderFilter.ts
- goes with previous commit 124cb96, right OR left value should never be above right OR left value a Slider Range filter
=> fix(filters): Slider Filter left value should never be above left value

examples/vite-demo-vanilla-bundle/src/examples/example12.ts, packages/common/src/extensions/slickCellMenu.ts, packages/common/src/interfaces/cellMenuOption.interface.ts, test/cypress/e2e/example12.cy.ts
- by default Cell Menu are preventing event bubbling and this causes the Cell Menu to not activate the active cell and this causes the Composite Editor to not receive the correct row number, let's add a `cellMenu.preventEventBubbling` to keep the default but offer the option to disable the default and fix Composite Editor
=> fix(editor): Composite Editor should work with Cell Menu

examples/vite-demo-vanilla-bundle/src/examples/example12.ts, packages/common/src/extensions/slickCellMenu.ts, packages/common/src/interfaces/cellMenuOption.interface.ts
- this rename the new Cell Menu option introduced in previous PR #1591 to fix Composite Editor Cell Menu not using correct row index
=> chore(editors): use better Cell Menu option name activateCellOnMenuClick

docs/TOC.md, docs/localization/localization-i18n.md, docs/localization/localization-single-locale.md, docs/localization/localization-translate-service.md
closes #1595
- add docs for using translations in 3 different ways:
1. single Locale (other than English)
2. with I18Next
3. with custom Translate Service
=> docs: add missing Localization docs, closes #1595

packages/common/src/core/slickGrid.ts
this fixes a limitation of jsdom which caused unit tests with vitest/jsdom to fail in components using the slickgrid-universal component
fixes #1601
=> chore: workaround for jsdom limitation when unit testing

packages/binding/package.json, packages/common/package.json, packages/composite-editor-component/package.json, packages/custom-footer-component/package.json, packages/custom-tooltip-plugin/package.json, packages/empty-warning-component/package.json, packages/event-pub-sub/package.json, packages/excel-export/package.json, packages/graphql/package.json, packages/odata/package.json, packages/pagination-component/package.json, packages/row-detail-view-plugin/package.json, packages/rxjs-observable/package.json, packages/text-export/package.json, packages/utils/package.json, packages/vanilla-bundle/package.json, packages/vanilla-force-bundle/package.json
- I don't think we need the `exports.node` since it's not a package meant to be used in NodeJS but rather in a browser, so let's remove it
- also move `module` to be after the `exports` since order might matter (not entirely sure but that is what `rimraf` does and it's a package made a NodeJS member, so it should be a good indication)
- related to issue #1601
=> chore: remove `exports.node` from all packages

examples/vite-demo-vanilla-bundle/src/examples/example02.ts, packages/common/src/core/slickGrid.ts, packages/common/src/extensions/__tests__/slickColumnPicker.spec.ts, packages/common/src/extensions/slickColumnPicker.ts, packages/common/src/extensions/slickGridMenu.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/column.interface.ts, test/cypress/e2e/example02.cy.ts
fixes #1605 
- fixes by reverting #1476 but also make sure that it doesn't regress the older issue #1475
- also add a `columnPickerLabel` option in the Column interface, because in some cases the default header column extractor (defined in the global grid options) will return all text it finds (via `.textContent` as mentioned in this [comment](https://github.com/ghiscoding/slickgrid-universal/issues/1605#issuecomment-2229387474)) and that might not be ideal given that an HTML element with extra button will also extract and append the button text in both ColumnPicker/GridMenu
=> feat: add `columnPickerLabel` for custom label, also fix #1605

packages/common/src/formatters/__tests__/iconFormatter.spec.ts, packages/common/src/formatters/iconFormatter.ts
adds the possibility to define tooltips via the title tag on icon formatters
=> feat: support tooltips on icon formatters

packages/composite-editor-component/src/compositeEditor.factory.ts, packages/composite-editor-component/src/slick-composite-editor.component.ts
I just tried to integrate the composite editor and it failed with the error that `[data-editor=1234]` is an invalid selector. Guess what, my column ids are numeric strings :)
=> fix: queryselector should support numeric ids

examples/vite-demo-vanilla-bundle/src/examples/example09.ts, examples/vite-demo-vanilla-bundle/src/examples/example10.ts, packages/common/src/interfaces/backendServiceOption.interface.ts, packages/graphql/src/services/graphql.service.ts, packages/odata/src/services/grid-odata.service.ts
meh there was an issue where suddenly on multi-selects I didn't get the value of the second and onwards selection
=> fix: provide all search values

packages/common/src/extensions/slickCheckboxSelectColumn.ts
Salesforce does not supoort DocumentDefragment, so add condition preventDocumentFragmentUsage for checkboxSelectorColumn.
=> fix: don't use Document Fragment in SlickCheckbox for Salesforce Usage

packages/common/src/core/slickGrid.ts
- follows SlickGrid PR: https://github.com/6pac/SlickGrid/pull/1039
=> fix(core): pinning 1st column could caused the header to get misaligned

examples/vite-demo-vanilla-bundle/src/examples/example21.html, examples/vite-demo-vanilla-bundle/src/examples/example21.ts, packages/common/src/interfaces/extensionModel.interface.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/services/__tests__/extension.service.spec.ts, packages/common/src/services/extension.service.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, test/cypress/e2e/example21.cy.ts
- provide a new `preRegisterExternalExtensions()` callback in the grid options to help multiple extensions to work together.
- add Row Selection + Row Detail to Example 21
- that will mostly help only Slickgrid-Universal (and won't help Angular/Aurelia projects but it might be useful in the future, who knows)
=> feat: add `preRegisterExternalExtensions` to help external RowDetail

packages/common/src/core/slickGrid.ts, packages/common/src/editors/__tests__/longTextEditor.spec.ts, packages/common/src/editors/longTextEditor.ts, packages/common/src/extensions/menuFromCellBaseClass.ts, packages/common/src/extensions/slickCellRangeSelector.ts, packages/common/src/extensions/slickGridMenu.ts, packages/common/src/extensions/slickHeaderMenu.ts, packages/common/src/extensions/slickRowMoveManager.ts, packages/common/src/services/__tests__/resizer.service.spec.ts, packages/common/src/services/resizer.service.ts, packages/composite-editor-component/src/compositeEditor.factory.ts, packages/custom-tooltip-plugin/src/__tests__/slickCustomTooltip.spec.ts, packages/custom-tooltip-plugin/src/slickCustomTooltip.ts, packages/utils/src/__tests__/domUtils.spec.ts, packages/utils/src/domUtils.ts
- prior to the code change, we could provide an undefined/null element which would have returned an undefined result, but I think it's better to always return and if the element is really null then we should check it before calling the method
- this code change is also simplifies the code a lot too
=> chore: change `getOffset()` to always return (never null)

packages/graphql/src/services/__tests__/graphql.service.spec.ts, packages/graphql/src/services/graphql.service.ts, packages/odata/src/services/__tests__/grid-odata.service.spec.ts, packages/odata/src/services/grid-odata.service.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- as per this [comment](https://github.com/ghiscoding/slickgrid-universal/pull/1609#issuecomment-2268745793) suggestion, the Infinite Scroll logic shouldn't be in any Backend Services, it should rather be moved to the vanilla component (for other repos, that would be within Angular-Slickgrid, ...)
=> chore: move Infinite Scroll logic to vanilla component

packages/common/package.json, pnpm-lock.yaml
`@types/trusted-types` must be installed in order to use `TrustedHTML` interface (for CSP)
=> fix(common): add missing dependency `@types/trusted-types`

docs/column-functionalities/editors/date-editor-(vanilla-calendar).md, docs/migrations/migration-to-5.x.md, packages/common/package.json, packages/common/src/commonEditorFilter/commonEditorFilterUtils.ts, packages/common/src/editors/__tests__/dateEditor.spec.ts, packages/common/src/editors/dateEditor.ts, packages/common/src/editors/editors.index.ts, packages/common/src/filters/__tests__/compoundDateFilter.spec.ts, packages/common/src/filters/__tests__/dateRangeFilter.spec.ts, packages/common/src/filters/dateFilter.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/vanillaCalendarOption.interface.ts, packages/common/src/styles/_variables.scss, pnpm-lock.yaml, test/cypress/e2e/example10.cy.ts, test/cypress/e2e/example11.cy.ts
- migrate to [`vanilla-calendar-pro`](https://github.com/uvarov-frontend/vanilla-calendar-pro) and drop the custom fork `vanilla-calendar-picker` (which was always meant to be temporary) that I had created until all features I needed were going to be merged into the original project Vanilla-Calendar-Pro and we are just about to be there.
- it's very close to be ready but it's still missing a couple of small fixes
- NOTE: the Types are not imported the same way, they must be imported `from 'vanilla-calendar-pro/types'` instead of the default import
=> feat: migrate back to Vanilla-Calendar-Pro

packages/common/src/extensions/__tests__/slickCellExternalCopyManager.spec.ts, packages/common/src/extensions/slickCellExternalCopyManager.ts, packages/common/src/services/__tests__/dataWrapperService.spec.ts, packages/common/src/services/__tests__/extension.service.spec.ts, packages/common/src/services/dataWrapperService.ts, packages/common/src/services/index.ts
- while investigating for issue #1634, I found the problems shown below
- so it's a bit surprising that we didn't catch this earlier but the plugin was only coded for SlickGrid usage to get read/write data and without the DataView, but Slickgrid-Universal is all built with the DataView usage only and so we should really fix this to support both
- add a new `DataWrapperService` to make it easier to call the correct functions depending on our usage SlickGrid or SlickDataView
=> fix: SlickCellExternalCopyManager should use DataView

packages/common/src/services/__tests__/extension.service.spec.ts, packages/common/src/services/extension.service.ts
- calling `preRegisterExternalExtensions` should be added to the `extensionList` array so that it will later be dispose off when looping through the array when it is time to dispose each extension
=> fix: calling `preRegisterExternalExtensions` should be added to ext list

examples/vite-demo-vanilla-bundle/src/examples/example03.html, packages/common/src/core/slickGrid.ts, packages/common/src/interfaces/gridOption.interface.ts, test/cypress/e2e/example03.cy.ts
- see SlickGrid [comment](https://github.com/6pac/SlickGrid/issues/219#issuecomment-1630077429) for more info
- a lower thottling delay (10ms instead of previously 50ms) will show blank area for a much shorter period whenever we scroll to an uncached scroll position (for example completely scroll to bottom of large grid)
- NOTE: a throttling of 0ms causes flickering and/or other issues in some cases, but 5ms seems like a good number to use
=> perf: decrease virtual scroll render throttling to 10ms

examples/vite-demo-vanilla-bundle/src/examples/example02.ts, packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/interfaces/gridOption.interface.ts, test/cypress/e2e/example02.cy.ts
- related to this original SlickGrid [issue 1044](https://github.com/6pac/SlickGrid/issues/1044), provide a new grid option to allow the possibility to use top offset CSS style via `transform` instead of `top` to fix some UI rendering issue on large dataset
- for example each `.slick-row` have a top offset to represent which which row it is, let say our `rowHeight` is 25px, then the 2nd row typically has a CSS style of `top: 50px`, the 3rd row has `top: 75px`, and so on... this new grid option would use `transform: translateY(25px)` instead, there's benefit in doing this as shown in the article below
- this might improve perf as well as per this article: [Why Moving Elements With Translate() Is Better Than Pos:abs Top/left](https://www.paulirish.com/2012/why-moving-elements-with-translate- …
=> perf: add new `rowTopOffsetRenderType` grid option to use "transform"

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/extensions/__tests__/slickCellExternalCopyManager.spec.ts, packages/common/src/extensions/slickCellExternalCopyManager.ts, packages/common/src/extensions/slickCellSelectionModel.ts
fixes #1634 
- prior to this PR, the hidden columns were being counted as column indexes when pasting and also when starting a cell selection
=> fix: SlickCellExternalCopyManager should work w/hidden cols fixes #1634

packages/common/package.json, packages/common/src/interfaces/columnExcelExportOption.interface.ts, packages/common/src/interfaces/excelExportOption.interface.ts, packages/excel-export/package.json, pnpm-lock.yaml
- since `excel-builder-vanilla` is an optional dependency (when user decides to install and use `@slickgrid-universal/excel-export` separately), we should only import its types in the `@slickgrid-universal/common` package and no need to download/install the entire library since we only need its types.
- So to deal with that, I created a separate types only package. The new package [`@excel-builder-vanilla/types`](https://github.com/ghiscoding/excel-builder-vanilla/tree/main/packages/excel-builder-vanilla-types) only includes `d.ts` files so that we still have correct interface in the grid options but doesn't install the entire lib for the users who aren't installing Excel Export
=> fix: only import `@excel-builder-vanilla/types` for optional dep

packages/common/src/services/__tests__/utilities.spec.ts, packages/common/src/services/utilities.ts
fixes #1657
- calling the function `unflattenParentChildArrayToTree` multiple times should always produce the same result
- prior to this fix, calling the same function multiple times was duplicating items every time it ran which is obviously an incorrect behavior
=> fix(tree): unflattening tree->flat array multiple times, fixes #1657

packages/common/src/interfaces/treeDataOption.interface.ts, packages/common/src/services/__tests__/treeData.service.spec.ts, packages/common/src/services/__tests__/utilities.spec.ts, packages/common/src/services/treeData.service.ts, packages/common/src/services/utilities.ts
- to be DRY
- we had code that was doing the same thing over and over to get Tree Data prop names, since we already had `getTreeDataOptionPropName()`, why not move it to a common place (utilies) and use it in both places
- also separate all Tree Data prop names into a separate interface so that we can call it anywhere instead of redeclaring the same props everywhere
=> chore(tree): move & reuse `getTreeDataOptionPropName()`

packages/common/src/extensions/__tests__/slickCellExternalCopyManager.spec.ts, packages/common/src/extensions/slickCellExternalCopyManager.ts, packages/composite-editor-component/src/slick-composite-editor.component.ts
I guess this feature was actually never properly tested but when pasting new rows at the bottom, with the defined `newRowCreator`, the previously auto created empty rows were not having an individual unique id, causing the subsequent actions to fail.
This changes it so that the burden is on the dev to provide the actual new row addition. At least that way he/she can control the newly created ids.
If you see this ok I would actually also update the docs to desribe the `newRowCreator` behavior.
=> fix: pasting multiple new rows

package.json, pnpm-lock.yaml, test/vitest.config.mts
- also keep watch as Vitest's default and pass `--no-watch` for the test with coverage
=> chore: upgrade to latest Vitest v2.1.0-beta.7

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/editors/__tests__/autocompleterEditor.spec.ts, packages/common/src/editors/autocompleterEditor.ts, packages/common/src/interfaces/editorArguments.interface.ts
- when grid options are set to `{ autoEdit: true, autoCommitEdit: false }` the Autocomplete Editor was executing navigate down twice because when we choose an item from the autocomplete with ENTER key, it also executes a navigate down
=> fix(core): Autocomplete Editor shouldn't navigate down twice on enter

packages/common/src/core/slickDataview.ts
fixes #1668
Optimize getAllSelectedFilteredItems and preSelectedRowIdsChangeFn with Set lookup and reducing time complexity from O(n square) to O(n)
=> perf: Reduce iterative time complexity in Tree Data, fixes #1668

packages/common/src/services/utilities.ts
- previous and recent commit 67edd1e was referencing the row data with `id` but in reality it's not always set as `id`, we should reference the `identifierPropName` in the method `unflattenParentChildArrayToTree()`
=> fix(TreeData): identifier is not always "id" when unflattening

examples/vite-demo-vanilla-bundle/src/examples/example07.ts, packages/common/src/editors/selectEditor.ts
- similar to PR #1670, we can use a `Set` to improve perf by using O(n) instead of O(n square)
=> perf: use Set to improve perf when read current Select Editor values

packages/common/src/core/slickCore.ts, packages/common/src/services/dateUtils.ts, packages/common/src/services/utilities.ts, packages/utils/src/nodeExtend.ts
fixes #1657 again
Recreate the children array from scratch everytime instead of entity lookups.
There were some lint errors which I had to fix to be able to commit this.
=> fix(TreeData): Reset the childrens prop when unflattening dataset in case it is being reused

examples/vite-demo-vanilla-bundle/src/examples/example02.ts, examples/vite-demo-vanilla-bundle/src/examples/example03.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
fixes #1678
- see this [comment](https://github.com/ghiscoding/slickgrid-universal/issues/1678#issuecomment-2349071503) for more details
=> perf: don't invalidate grid rows more than once, fixes #1678

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/extensions/slickCellSelectionModel.ts
I needed a new project to get to know the react wrapper of Slickgrid Universal better. So why not build a whole VSCode extension right ? ;)
Also, I used that as the first time to try out the darkMode in more detail and noticed this little gotcha when selecting cells via mouse (at the end of the gif). This PR fixes it.
=> feat: matching border color for range selector in darkmode

packages/common/src/services/__tests__/treeData.service.spec.ts, packages/common/src/services/treeData.service.ts
Another perf optimization that is probably O(n square) if not more. 
When collapsing/expanding items in the grid, we also need to update the hierarchical (tree) dataset and the previous code was searching for the item in the tree and then was toggling its collapse prop. When we have a single item that we collapse, searching in the tree is relatively quick, but when we toggle thousand of items and we search them one-by-one then this becomes extremely costly to execute (search+toggle for every row). What we can do to decrease the time is to keep doing the toggle of the collapse prop on the flat array BUT instead of searching each item in the tree, we can simply recreate the hierarchical (tree) only once and we're done (40x decrease as shown below).
---
tree collapse/expand: …
=> perf(treeData): decrease Tree Grid expandAll/collapseAll time by 40x

docs/grid-functionalities/grouping-aggregators.md, examples/vite-demo-vanilla-bundle/package.json, examples/vite-demo-vanilla-bundle/src/material-styles.scss, packages/common/package.json, packages/common/src/styles/_variables-theme-material.scss, packages/common/src/styles/_variables-theme-salesforce.scss, packages/common/src/styles/_variables.scss, packages/common/src/styles/colors.scss, pnpm-lock.yaml
- another deprecation from SASS which is again displaying a load of console warnings
- more info on SASS website: https://sass-lang.com/documentation/breaking-changes/color-functions/
=> fix(styling): SASS deprecated `lighten` and `darken` methods

docs/column-functionalities/editors/date-editor-(vanilla-calendar).md, examples/vite-demo-vanilla-bundle/src/examples/example11.ts, packages/common/src/editors/__tests__/dateEditor.spec.ts, packages/common/src/editors/dateEditor.ts, packages/common/src/interfaces/columnEditor.interface.ts, packages/common/src/interfaces/vanillaCalendarOption.interface.ts, test/cypress/e2e/example11.cy.ts
So this is a general idea of how I thought of tackling the realted issue https://github.com/ghiscoding/slickgrid-universal/issues/1684
No tests or docs yet as I first would like to validate what you think about the feature request @ghiscoding
=> feat: allow overriding readOnly behavior of dateEditor

packages/common/src/editors/__tests__/autocompleterEditor.spec.ts, packages/common/src/editors/__tests__/dateEditor.spec.ts, packages/common/src/editors/__tests__/dualInputEditor.spec.ts, packages/common/src/editors/__tests__/floatEditor.spec.ts, packages/common/src/editors/__tests__/inputEditor.spec.ts, packages/common/src/editors/__tests__/inputPasswordEditor.spec.ts, packages/common/src/editors/__tests__/integerEditor.spec.ts, packages/common/src/editors/autocompleterEditor.ts, packages/common/src/editors/dateEditor.ts, packages/common/src/editors/dualInputEditor.ts, packages/common/src/editors/inputEditor.ts
closes https://github.com/ghiscoding/slickgrid-universal/issues/1686
=> fix: home and end keys stop propagation on input based editors, closes #1686

packages/common/src/formatters/formatterUtilities.ts, packages/common/src/services/__tests__/dateUtils.spec.ts, packages/common/src/services/dateUtils.ts
- before switching to Tempo, we were using MomentJS and with MomentJS if we were passing "YYYY-MM-DD" as input format it wasn't stripping the time if it had any, however with Tempo it was stripping the time and assuming midnight which wasn't the same as MomentJS.... to overcome this, we can simply pass ISO8601 as input format, I added `withDefaultIso8601` option for use case
- also fix a parsing format for short format (like dateUsShort), it should work with both with/without zero padding
- fixes a problem detected while implementing PR #1691 but I think it should be created as a separate PR
=> fix: Date parsing shouldn't fail & dateIso type should accept time

packages/common/src/extensions/__tests__/extensionUtility.spec.ts, packages/common/src/extensions/__tests__/slickAutoTooltip.spec.ts, packages/common/src/extensions/__tests__/slickCellMenu.plugin.spec.ts, packages/common/src/extensions/__tests__/slickColumnPicker.spec.ts, packages/common/src/extensions/__tests__/slickContextMenu.spec.ts, packages/common/src/extensions/__tests__/slickDraggableGrouping.spec.ts, packages/common/src/extensions/__tests__/slickGridMenu.spec.ts, packages/common/src/extensions/__tests__/slickHeaderButtons.spec.ts, packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts, packages/common/src/services/__tests__/extension.service.spec.ts, packages/common/src/services/__tests__/grid.service.spec.ts, packages/common/src/services/__tests__/gridState.service.spec.ts, packages/common/src/services/__tests__/shared.service.spec.ts, packages/common/src/services/shared.service.ts, packages/pagination-component/src/__tests__/slick-pagination-without-i18n.spec.ts, packages/pagination-component/src/__tests__/slick-pagination.spec.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts
I previously overcomplicated things by using all Getters/Setters in the Shared Service, when in reality regular public props would suffice
=> chore: refactor SharedService, only use Getters/Setters when necessary

packages/common/src/services/__tests__/sort.service.spec.ts, packages/common/src/services/sort.service.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- the previous warning wasn't always showing up when dataset is assigned later (i.e., it wasn't showing in Angular-Slickgrid), we should really move this warning in each framework whenever the dataset is assigned
=> chore: move no pre-parse date warning to vanilla grid comp

packages/common/src/services/__tests__/groupingAndColspan.service.spec.ts, packages/common/src/services/groupingAndColspan.service.ts
- Header Grouping requires us to subscribe to a few events to make sure that the Header Grouping are always rendered properly and that they follow the width of all columns that are contained in each group. However the `grid.onRendered` is already being called by many use cases, so there's no need to subscribe to so many events when we know that the `onRendered` will be called anyway, so we can get rid of many of these events
- for example `onColumnsResized`, `onColumnsReordered`, `onColumnPickerColumnsChanged`, .... will all trigger the `onRendered`, so there's really no need to duplicate the work when we can subscribe to a lot less events to do the same work
- tested locally by trying to cover all these use case via the UI
=> fix: remove unnecessary events to re-render Header Grouping

packages/common/src/services/__tests__/groupingAndColspan.service.spec.ts, packages/common/src/services/groupingAndColspan.service.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- it seems that after PR #1702, there's no more need for the PubSub DI, so let's remove it from the argument list (note that this will require changes in the downstream repos as well for the same DI removal)
=> chore: remove unused PubSub refs after PR #1702

packages/common/src/extensions/__tests__/slickColumnPicker.spec.ts, packages/common/src/extensions/slickColumnPicker.ts
- similar to what we've done with the Header Menu, then the Column Picker should also auto-position itself to the left if doesn't have enough space on the right and vice-versa
=> fix: Column Picker should auto-position left/right with available space

packages/common/src/interfaces/pagination.interface.ts, packages/pagination-component/src/__tests__/slick-pagination-without-i18n.spec.ts, packages/pagination-component/src/__tests__/slick-pagination.spec.ts, packages/pagination-component/src/slick-pagination.component.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- refactor the SlickPagination Component and add a basic abstract BasePaginationComponent that will eventually be used by external user to create their own Custom Pagination (future PR)
- also try to align the constructor with the SlickFooter Component
=> chore: refactor Pagination Component in preparation of Custom Comp

docs/grid-functionalities/pagination.md, examples/vite-demo-vanilla-bundle/src/examples/example30-pager.scss, examples/vite-demo-vanilla-bundle/src/examples/example30-pager.ts, examples/vite-demo-vanilla-bundle/src/examples/example30.html, examples/vite-demo-vanilla-bundle/src/examples/example30.ts, packages/common/src/interfaces/pagination.interface.ts, packages/pagination-component/src/__tests__/slick-pagination-without-i18n.spec.ts, packages/pagination-component/src/__tests__/slick-pagination.spec.ts, packages/pagination-component/src/slick-pagination.component.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, test/cypress/e2e/example30.cy.ts
- after giving it a try in Angular/Aurelia-Slickgrid, I discovered that it was better to avoid using any DI, we can simply move them to an `init()` function
=> fix: move DI to init() to make Pagination Comp working with all ports

examples/vite-demo-vanilla-bundle/src/examples/example07.ts, examples/vite-demo-vanilla-bundle/src/examples/example10.ts, examples/vite-demo-vanilla-bundle/src/examples/example22.ts, examples/vite-demo-vanilla-bundle/src/examples/example25.ts, examples/vite-demo-vanilla-bundle/src/examples/example27.ts
- we weren't resetting the locale to English when routing to a new example and in some cases running all Cypress tests locally could pollute the next Example test suite (ie, leaving previous example with French and routing to new example would show up in French when test assumes English)
=> chore: fix Cypress flaky tests by always setting English locale

test/cypress/e2e/example12.cy.ts, test/cypress/e2e/example14.cy.ts
- we never had any tests to verify that a date editor with `minDate: 'today'` option defined would not allow dates older than today to be clickable, this PR adds such test
=> chore: add missing Cypress tests for calendar editor minDate

packages/common/src/commonEditorFilter/commonEditorFilterUtils.ts, packages/common/src/editors/__tests__/dateEditor.spec.ts, packages/common/src/editors/dateEditor.ts, packages/common/src/filters/dateFilter.ts, test/cypress/e2e/example12.cy.ts
- add `resetDatePicker()` to correctly reset date picker and reset to today's date
=> fix: date editor clear/reset not working in composite editor

examples/vite-demo-vanilla-bundle/src/examples/example07.html, examples/vite-demo-vanilla-bundle/src/examples/example07.ts, packages/common/src/interfaces/hideColumnOption.interface.ts, packages/common/src/services/__tests__/grid.service.spec.ts, packages/common/src/services/grid.service.ts, test/cypress/e2e/example07.cy.ts
fixes #1728 
- we should only ever call `setColumn()` once when hiding multiple columns to avoid perf issues
- also add `showColumnByIds()` to align with `hideColumnByIds()`
=> fix: hideColumnByIds() should call setColumn() only once, fix #1728

examples/vite-demo-vanilla-bundle/src/examples/example09.ts, packages/common/src/services/__tests__/gridState.service.spec.ts, packages/common/src/services/gridState.service.ts, test/cypress/e2e/example09.cy.ts
hiding columns is triggering an event which was maybe an array of columns in the past but it probably changed to an object of shape `{ columns, hiddenColumn }` later on, however the Grid State subscribing to this event was never updated causing the Grid State to return incorrect data in its metadata
=> fix: hiding column(s) returned incorrect Grid State changes data

packages/common/src/extensions/__tests__/slickGridMenu.spec.ts, packages/common/src/extensions/extensionCommonUtils.ts, packages/common/src/services/grid.service.ts
tested a bit more after previous PR #1736 and found couple of small issues
- calling `hideColumnByIds()` for multiple columns wasn't working correctly
- also the options `hideFromColumnPicker` and `hideFromGridMenu` were incorrectly tied together meaning that when `hideFromColumnPicker` was enabled, it was also hiding them in the GridMenu as well which is wrong
- lastly I've done a refactor to remove duplicate code of calling some grid commands when options `autoResizeColumns` and `triggerEvent` are enabled.
=> fix: hideColumnByIds wasn't hiding columns properly

packages/common/src/editors/__tests__/dateEditor.spec.ts, packages/common/src/editors/dateEditor.ts, test/cypress/e2e/example12.cy.ts
- when the input date wasn't ISO date format, the form reset wasn't reapplying the original date and was lost
=> fix: Composite Editor should reapply original date when exist & form is reset

packages/common/src/extensions/slickCellExternalCopyManager.ts
- using SlickExternalCopyManager plugin shouldn't change scroll position when copy/pasting values in the grid
- issue was identified in SlickGrid with a fix published in that repo as well
=> fix: ExternalCopyManager shouldn't change body scroll pos when pasting

examples/vite-demo-vanilla-bundle/package.json, examples/vite-demo-vanilla-bundle/vite.config.mts, packages/vanilla-force-bundle/package.json, packages/vanilla-force-bundle/vite.config.mts, pnpm-lock.yaml
- Vite 6 made SASS modern-compiler the default so we can remove unnecessary option
=> chore: upgrade to Vite 6 and remove modern compiler

examples/vite-demo-vanilla-bundle/src/examples/example03.html, examples/vite-demo-vanilla-bundle/src/examples/example03.ts, packages/common/src/styles/slick-plugins.scss
- when setting filters dynamically, the calendar picker is appended to the body without being repositioning which is making the body taller and unnecessary scrollable
- to fix this issue, we can simply preset hidden calendar picker at position 0,0
=> fix: setting filter dynamically shouldn't make body taller

packages/common/src/extensions/slickCellExternalCopyManager.ts, packages/common/src/filters/autocompleterFilter.ts, packages/common/src/filters/dateFilter.ts, packages/common/src/filters/inputFilter.ts, packages/common/src/filters/sliderFilter.ts, packages/common/src/services/filter.service.ts
- some changes made in PR #917 caused a small issue but only when `enableExcelCopyBuffer` is set, which only happen after these 2 steps
1. click on a cell to open an editor
2. focus on a filter then start typing, the filter will lose focus because it was sent to the grid 
- the issue can be reproduced in Slickgrid-Universal Example 13 (or Angular-Slickgrid Example 3 as shown below)
=> fix: input filter loses focus after edit+filtering with `enableExcelCopyBuffer`

packages/common/src/core/slickGrid.ts
- this change was implemented in this SlickGrid [PR](https://github.com/6pac/SlickGrid/pull/1085) and I'm not sure that it will make any differences in here since SlickGrid has its own (different) auto-resizer and part of the code doesn't exists in here (only a small portion of the code was copied over), so this change might or not help at all.
=> fix: ensure DOM alterations during initialization are always cleaned up

packages/common/src/core/slickGrid.ts, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-grid.scss
- prior to this PR, we needed to add frozen broder style on last header/columns, this was not only hard to style, it also wasn't styled correctly in the UI. by adding the "frozen" class directly on every left pane (when frozen column is enabled) makes it much easier to style the UI correctly
- NOTE: since we can now style the frozen pane with 1 line, I deleted a bunch of SASS/CSS variables that are no longer necessary 
- `$slick-frozen-preheader-row-border-right`
- `$slick-frozen-header-row-border-right`
- `$slick-frozen-filter-row-border-right`
=> fix: add "frozen" class to all slick-pane for easier styling

examples/vite-demo-vanilla-bundle/src/examples/example07.ts, packages/common/src/filters/autocompleterFilter.ts, packages/common/src/filters/selectFilter.ts, packages/common/src/services/__tests__/observers.spec.ts, packages/common/src/services/index.ts, packages/common/src/services/observers.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- our collection observer should provide a `disconnect()` method to avoid calling callback indifinitely
- we should also call this disconnect when disposing each filters that were using this observer
- finally also add the missing barrel export
=> fix: add missing Collection Observer disconnect method

demos/vue/src/components/Example03.vue, demos/vue/src/components/Example16.vue, frameworks/slickgrid-vue/src/components/SlickgridVue.vue
use our custom collection observer to watch for column definitions changes push/pop since that is not observed by default in the Vue watch (not without deep watch anyway)
=> fix: add missing collection observer in Vue grid implementation

demos/vue/src/App.vue, demos/vue/src/main.ts, frameworks/slickgrid-vue/docs/getting-started/quick-start.md, frameworks/slickgrid-vue/docs/localization/localization-with-custom-locales.md, frameworks/slickgrid-vue/docs/localization/localization.md, frameworks/slickgrid-vue/src/components/SlickgridVue.vue, frameworks/slickgrid-vue/src/index.ts, frameworks/slickgrid-vue/src/services/index.ts, frameworks/slickgrid-vue/src/services/translaterI18Next.service.ts
⚠️ this is a breaking change compare to previous implementation since the user now needs to be `provide` the I18Next instance themselves. However the benefit is that I18Next is now totally optional making build smaller in size for users who don't need I18N
=> feat(vue): make I18Next totally optional in Slickgrid-Vue

demos/vue/package.json, demos/vue/src/components/Example30.vue, examples/vite-demo-vanilla-bundle/package.json, examples/vite-demo-vanilla-bundle/src/examples/example12.ts, frameworks/slickgrid-vue/package.json, package.json, pnpm-lock.yaml, test/cypress/e2e/example12.cy.ts
- latest `vue-tsc` fixed the issue they had with updating to latest TypeScript v5.7.x
- also for good the Composite example flaky Cypress test which failed a lot recently
=> chore(deps): update `vue-tsc` to allow latest TypeScript update & fix flaky E2E test

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/extensions/__tests__/slickCellSelectionModel.spec.ts, packages/common/src/extensions/slickCellSelectionModel.ts, test/cypress/e2e/example19.cy.ts
- add a few missing key shortcuts to navigate in the grid
- Ctrl+Home will now go to top left (coord 0, 0)
- Ctrl+End will now go to bottom right of the grid
- add a few missing key shortcuts for cell selection
- Shift+Ctrl+ArrowLeft, now same as Shift+Home, to select cells from current cell until starting index on same row
- Shift+Ctrl+ArrowRight, now same as Shift+End, to select cells from current cell until end index on same row
- Shift+Ctrl+ArrowUp to select cells from current cell up to first row on same column
- Shift+Ctrl+ArrowDown to select cells from current cell down to last row on same column
- Ctrl+a (or A) to select all cells in the grid
=> fix(core): add missing key shortcuts for navigation & cell selections

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts
- certain nav commands are navigating away from current viewport and when re-navigating back to another cell that is in the same viewport (like 0,0 with Ctrl+Home) then it sometimes has 2 active cells instead of never more than 1.
- this can probably occur a little more after recent PR #1788
=> fix: remove "active" CSS classes before navigating to another cell

packages/common/src/core/__tests__/slickDataView.spec.ts, packages/common/src/core/slickDataview.ts, packages/common/src/extensions/slickGroupItemMetadataProvider.ts, packages/common/src/interfaces/groupItemMetadataProviderOption.interface.ts
- allow providing a custom global item metadata provider by passing it through the `groupItemMetadataProvider` DataView constructor option
- implementation copied from https://github.com/GerHobbelt/SlickGrid fork
=> feat: add Custom Global Item Data Provider

examples/vite-demo-vanilla-bundle/package.json, examples/vite-demo-vanilla-bundle/vite.config.mts, pnpm-lock.yaml
- Bulma fixed all their SASS warnings with their recent version, so we can remove the SASS warning silencing
=> chore: remove unnecessary SASS quiet warnings

packages/common/src/core/slickGrid.ts, packages/common/src/extensions/__tests__/slickDraggableGrouping.spec.ts, packages/common/src/extensions/slickDraggableGrouping.ts
- we should add the CSS class `slick-column-header-active` to the Header Cell **only** when we start dragging that header, otherwise we shouldn't and that wasn't the case before which showed a the active header and a flickering especially in Dark Mode
=> fix: opening Header Menu shouldn't add Active Header Cell

packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts, packages/common/src/extensions/slickHeaderMenu.ts, test/cypress/e2e/example14.cy.ts
- when a Header slot is provided within the slickgrid component of any framework (Angular-Slickgrid, Slickgrid-Vue, ...) then the Header Menu position had the wrong top offset and the header slot height was being added to the calculation when it shouldn't. The fix was simply to make our top offset calculation relative to the SlickGrid container without the header slot, basically the real slickgrid container that holds the slick-header-columns and everything else (which is the one highlighted in blue below)
here's the real `.slickgrid-container` that we should be making our "relative to" offset calculation
=> fix: Header Menu was offset when header/footer slots provided

packages/common/src/core/slickGrid.ts
while working on another PR #1820 I found a bug in core SlickGrid file, when using `setOptions()` it was overriding a complete object property instead of merging (or extending it). For my use case, the grid option prior to using the `setOptions` was `autoResize` with about 10 other props under it but after I use the `setOptions` it took the only 2 options I had define in my grid and overrode my previous 10 props (global defaults) and that broke my Cypress tests. The problem is that `node-extend` is a perfect copy of `jQuery.extend` and when we're not doing a deep copy of an object, the behavior seems to be to override existing object props, however if we pass `true` to make a deep copy then the behavior changes to be a object props merge. So my quick fix is to use the deep copy, even if …
=> fix(core): using SlickGrid `setOptions()` was overriding object prop

.gitattributes, demos/vue/src/components/Example28.vue, frameworks/slickgrid-vue/src/components/SlickgridVue.vue, frameworks/slickgrid-vue/src/global-grid-options.ts, packages/common/src/core/slickDataview.ts, packages/common/src/core/slickGrid.ts, packages/common/src/global-grid-options.ts, packages/common/src/interfaces/autoResizeOption.interface.ts, packages/common/src/services/__tests__/resizer.service.spec.ts, packages/common/src/services/resizer.service.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
The auto-resize is great but it had a flaw that always bothered me but wasn't sure on how to fix it. The problem is that it always resized the grid with all available viewport space regardless of the dataset and in some cases when the dataset was small, it showed a full size grid in the UI with in some cases a rather large empty whitespace area at the bottom of the grid. This PR fixes it once and for all. We always had the grid option `autoHeight` which was good when the user knows its dataset is small, but most of the time we don't know dataset length at all, it could be small today but large next month, so we can't use `autoHeight` grid option for that reason.... this PR adds the grid option `autoResize.autoHeight` (yes it's the same flag name but it's not under the same property), it's …
=> fix(resizer): add `autoResize.autoHeight` to resize by dataset length

demos/vanilla/src/examples/example32.html, demos/vue/src/components/Example43.vue, packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts
compare with previous codecov test coverage report (lines: 5177, 6671)
https://app.codecov.io/gh/ghiscoding/slickgrid-universal/pull/1798
=> chore: add more rowspan test coverage

packages/common/src/services/resizer.service.ts
- previous PR #1820 brought `autoHeight` to `autoResize` but it wasn't, and it should, resize the grid even when the dataset is an empty array
=> fix: `autoResize.autoHeight` should resize grid height even dataset is empty

packages/common/build-watch.mjs, packages/common/package.json, pnpm-lock.yaml
the package [copyfiles](https://www.npmjs.com/package/copyfiles) isn't supported anymore (hasn't been for a few years), though we can use simple NodeJS native API to rewrite the whole thing as [native-copyfiles](https://www.npmjs.com/package/native-copyfiles) which is much simpler and only has 1 single dependency to `tinyglobby`.
=> chore: replace copyfiles with an in-house native package

frameworks/slickgrid-vue/src/extensions/slickRowDetailView.ts
- before (re)creating a new Vue app/component inside the Row Detail, we need to make sure to properly dipose/unmount any previous ones
=> fix(vue): Row Detail were not unmounted correctly before recreating them

packages/event-pub-sub/src/eventPubSub.service.spec.ts, packages/event-pub-sub/src/eventPubSub.service.ts
- this side effect is causing issues in a new feature that I'm working on (Row Detail with inner grid) and I'm pretty sure that event bubbling is completely unnecessary when used as a simple PubSub Service and that fixes the new feature issue
=> fix: internal PubSub Service shouldn't need event bubbling

.vscode/launch.json, packages/common/src/services/__tests__/resizer.service.spec.ts, packages/common/src/services/resizer.service.ts
- problem detected in Slickgrid-Vue, for unknown reason the `autoResize.autoHeight` wasn't calculating the height correctly on the initial load because the grid is not always available at that time. Subscribing to `grid.onAutosizeColumns` event seems like the best option, I also tried `grid.onRendered` but that event was triggered too early and too many times.
=> fix: auto-resize with autoHeight should use all grid section heights

packages/common/src/editors/__tests__/longTextEditor.spec.ts, packages/common/src/editors/longTextEditor.ts, packages/common/src/interfaces/longTextEditorOption.interface.ts
as windows users, my customers argue the save/cancel button order is super important ... *sigh*
=> feat: allow overriding the position of the textarea savebutton

.github/renovate.json5, package.json, pnpm-lock.yaml
- latest Vitest v3.0.6 and higher seem to cause regression issues, need to investigate further but for now let's use a fixed version that still works
=> chore: use older Vitest v3.0.5 to avoid regression in tests

packages/common/src/styles/slick-grid.scss
- frozen lines (pinning) shouldn't overflow outside the grid container
=> fix: frozen lines overflowing outside the grid

frameworks/slickgrid-vue/src/extensions/slickRowDetailView.ts
all event subscriptions in Row Detail plugin are wrapped into if condition even though we know for sure that they are defined so... let's just remove these if wrappers
=> chore: remove unneeded event if condition wrappers

package.json, packages/row-detail-view-plugin/src/slickRowDetailView.spec.ts, pnpm-lock.yaml, test/vitest.config.mts
Vitest reintroduced a breaking change that they had originally put in v3.0 but reverted and now reintroduced which broke my unit tests. The breaking change is in this Vitest [commit](https://github.com/vitest-dev/vitest/commit/167a98d77c8095288fcf193f8dfff0dd5cd44fa1) which is that `['setTimeout', 'setInterval', 'queueMicrotask']` are no longer mocked and must be added manually in our Vitest config. This PR fixes this so that I can keep up again with latest Vitest version
=> chore(deps): fix Vitest failing because of a recent breaking change

.github/renovate.json5, frameworks/slickgrid-vue/package.json, pnpm-lock.yaml
- an older version of vite-plugin-dts was causing the build to fail which it partially reversed in v4.5.3, so it's ok to update to latest version again
=> chore(deps): update vite-plugin-dts with fix

frameworks/slickgrid-vue/src/components/SlickgridVue.vue, frameworks/slickgrid-vue/src/models/gridOption.interface.ts, frameworks/slickgrid-vue/src/models/i18next.interface.ts, frameworks/slickgrid-vue/src/models/index.ts, frameworks/slickgrid-vue/src/services/translaterI18Next.service.ts
- we shouldn't rely on the `i18next` dependency since it's optional, let's just create a very basic `I18Next` interface that provides the minimal list of functions & props that we use in Slickgrid-Vue
=> fix(vue): don't rely on `i18next` interface since dep is optional

packages/common/src/services/__tests__/utilities.spec.ts, packages/common/src/services/utilities.ts
=> fix(tree): findItemInTreeStructure() shouldn't throw w/large dataset, fix #1885

demos/vanilla/package.json, demos/vanilla/src/translate.service.ts, docs/localization/localization-translate-service.md, package.json, packages/vanilla-bundle/README.md, packages/vanilla-bundle/package.json, packages/vanilla-force-bundle/README.md, packages/vanilla-force-bundle/package.json, pnpm-lock.yaml, pnpm-workspace.yaml, test/vitest-pretest.ts
- `whatwg-fetch` polyfill is no longer necessary since Fetch is now native in Node 20
=> chore(deps): remove unnecessary `whatwg-fetch`

packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-plugins.scss
importing the stylesheet in angular with
`@import '@slickgrid-universal/common/dist/styles/css/slickgrid-theme-default.css';`
throws an error
`✘ [ERROR] Missing closing } at .slickgrid-container .search-filter .operator.input-group-addon select [plugin angular-css]`
the `_variables.scss` included `!important` which caused the error, moved `!important` to the `.scss` file where the variable is used.
=> Fix: error in CSS

demos/react/src/examples/slickgrid/Example30.tsx, demos/vanilla/src/examples/example03.ts, demos/vanilla/src/examples/example04.ts, demos/vanilla/src/examples/example11.ts, demos/vanilla/src/examples/example12.ts, demos/vue/src/components/Example30.vue, docs/events/Available-Events.md, frameworks/angular-slickgrid/docs/events/Available-Events.md, frameworks/angular-slickgrid/src/demos/examples/grid-composite-editor.component.html, frameworks/aurelia-slickgrid/docs/events/available-events.md, frameworks/slickgrid-react/docs/events/available-events.md, frameworks/slickgrid-react/docs/grid-functionalities/composite-editor-modal.md, frameworks/slickgrid-react/src/components/slickgridReactProps.ts, frameworks/slickgrid-vue/docs/events/available-events.md, frameworks/slickgrid-vue/docs/grid-functionalities/composite-editor-modal.md, frameworks/slickgrid-vue/src/components/slickgridVueProps.interface.ts, packages/common/src/interfaces/gridServiceDeleteOption.interface.ts, packages/common/src/interfaces/gridServiceInsertOption.interface.ts, packages/common/src/interfaces/gridServiceUpdateOption.interface.ts, packages/common/src/services/__tests__/grid.service.spec.ts, packages/common/src/services/__tests__/pagination.service.spec.ts, packages/common/src/services/__tests__/sort.service.spec.ts, packages/common/src/services/grid.service.ts, packages/common/src/services/pagination.service.ts, packages/common/src/services/sort.service.ts
Our GridService has CRUD event that was sometime returning a single item or sometime multiple items and for that reason we had to rely on code like `onItemAdded.subscribe(item => { const items = Array.isArray(item) ? item : [item] }`, but if we always return an array then we know exactly the shape of items.
=> feat(services): pluralize CRUD events (ie: onItemsAdded, ...)

frameworks/angular-slickgrid/src/demos/examples/grid-colspan.component.ts, frameworks/angular-slickgrid/src/library/components/__tests__/angular-slickgrid.component.spec.ts, frameworks/angular-slickgrid/src/library/components/angular-slickgrid.component.ts, frameworks/aurelia-slickgrid/src/custom-elements/aurelia-slickgrid.ts, frameworks/slickgrid-react/src/components/slickgrid-react.tsx, frameworks/slickgrid-vue/src/components/SlickgridVue.vue, packages/common/src/interfaces/gridOption.interface.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
This option was deprecated when `globalItemMetadataProvider` was added with the new recent RowSpan feature, just use `gridOptions = { dataView: { globalItemMetadataProvider: { getRowMetadata: (item, row) => any }}}` instead
=> feat!: remove deprecated `colspanCallback` grid option

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/extensions/__tests__/slickCellExternalCopyManager.spec.ts, packages/common/src/extensions/__tests__/slickContextMenu.spec.ts, packages/common/src/extensions/slickContextMenu.ts, packages/common/src/formatters/formatterUtilities.ts
- when using Ctrl+C on an active cell, it should copy its content but only when the grid options `enableCellNavigation` is enabled but `enableExcelCopyBuffer` is disabled. We simply shouldn't use it when Excel Copy Buffer is enabled because it could conflict with each others. 
- also remove `navigator.clipboard` API instead of using a temp `textarea` to copy the value
=> feat: Ctrl+C to copy active cell to clipboard

.github/workflows/main.yml, .github/workflows/test-angular.yml
Add codecov flags to show coverage and separation for both Angular & Vanilla folders which are the only 2 that have unit tests
=> chore: add Angular-Slickgrid codecov

demos/vanilla/src/examples/example16.html, demos/vanilla/src/examples/example16.ts, demos/vanilla/src/styles.scss, demos/vue/src/components/Example33.vue, demos/vue/src/styles.scss, demos/vue/test/cypress/e2e/example33.cy.ts, docs/column-functionalities/editors/Select-Dropdown-Editor-(single,multiple).md, docs/column-functionalities/filters/select-filter.md, frameworks/slickgrid-vue/docs/column-functionalities/filters/select-filter.md, packages/common/src/commonEditorFilter/commonEditorFilterUtils.ts, packages/common/src/editors/selectEditor.ts, packages/common/src/filter-conditions/__tests__/filterUtilities.spec.ts, packages/common/src/filters/__tests__/selectFilter.spec.ts, packages/common/src/filters/autocompleterFilter.ts, packages/common/src/filters/filterUtilities.ts, packages/common/src/filters/selectFilter.ts, packages/common/src/interfaces/columnFilter.interface.ts, packages/common/src/services/__tests__/utilities.spec.ts, packages/common/src/services/domUtilities.ts, packages/common/src/services/utilities.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, test/cypress/e2e/example16.cy.ts
as discussed in #1922
- when user has lots of columns, it could be useful to load the ms-select collection only when opening the select dropdown via a new `collectionLazy` callback
- this new `collectionLazy` option is only available and implemented for Single/MultipleSelect Filter
- a loading/spinner might be implemented in ms-select library in a future release
=> feat(filter): add `collectionLazy` callback to Column Filter

docs/column-functionalities/editors/Autocomplete-Editor-(Kraaden-lib).md, docs/column-functionalities/editors/Select-Dropdown-Editor-(single,multiple).md, docs/column-functionalities/editors/date-editor-(vanilla-calendar).md, docs/column-functionalities/filters/select-filter.md, frameworks/slickgrid-vue/docs/column-functionalities/editors/autocomplete-editor-kraaden.md, frameworks/slickgrid-vue/docs/column-functionalities/editors/date-editor-vanilla-calendar.md, frameworks/slickgrid-vue/docs/column-functionalities/editors/select-dropdown-editor.md, frameworks/slickgrid-vue/docs/column-functionalities/filters/autocomplete-filter-kraaden.md, frameworks/slickgrid-vue/docs/column-functionalities/filters/select-filter.md, packages/common/src/editors/autocompleterEditor.ts, packages/common/src/editors/dateEditor.ts, packages/common/src/editors/selectEditor.ts, packages/common/src/filters/autocompleterFilter.ts, packages/common/src/filters/dateFilter.ts, packages/common/src/interfaces/columnEditor.interface.ts, packages/common/src/interfaces/columnFilter.interface.ts
sometime we would like to control or call a function from the external library directly, the user will now be able to do this via the `onInstantiated` callback which will return the 3rd party lib instance when ready
```ts
this.columns = [
{
id: 'prerequisites', name: 'Prerequisites', field: 'prerequisites', filterable: true,
filter: {
model: Filters.multipleSelect,
collection: [/*...*/],
onInstantiated: (msSelect) => console.log('ms-select instance', msSelect),
},
},
];
```
=> feat: add `onInstantiated` on all Editor/Filter with 3rd party lib

packages/common/src/formatters/formatters.index.ts, packages/common/src/interfaces/formatter.interface.ts, packages/common/src/interfaces/sorter.interface.ts, packages/common/src/services/utilities.ts, packages/common/src/sortComparers/sortComparers.index.ts
while working on a base Date Formatters, I saw an opportunity to decrease lib build size by creating all date Formatters & SortComparers dynamically and remove duplicative code (duplicate lines of code for all date types).
=> perf: build date Formatters/Sorters dynamically to decrease build size

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts
fixes an issue identified in SlickGrid, see [issue 1123](https://github.com/6pac/SlickGrid/pull/1123)
- when preHeader is enabled, it should be added to the calculation of the grid container auto-height, this wasn't the case before and the frozen scroll ended up being shown in the hidden section making it completely unusable
=> fix: autoHeight should add preHeader height when enabled

demos/aurelia/test/cypress/e2e/example32.cy.ts, demos/react/test/cypress/e2e/example32.cy.ts, demos/vue/test/cypress/e2e/example32.cy.ts, frameworks/angular-slickgrid/test/cypress/e2e/example32.cy.ts, packages/common/src/core/slickGrid.ts, packages/common/src/services/resizer.service.ts, test/cypress/e2e/example14.cy.ts
- depending on which `border-sizing` style the user has defined on its grid container element, the border was sometime not showing at bottom of the grid (ie: the grid below should have a border all around, but its bottom border wasn't showing)
- this wasn't an issue if the container has `border-sizing: 'content-box'` but most users have it set to `'border-box'` which is the default.
- also fix a problem that was in some rare occasion showing horizontal scroll for no reason, it seemed that the canvas width with slightly too wide and just removing `0.1px` out of the equation is enough to fix the problem
=> fix: incorrect grid container box size calculation border not showing

demos/aurelia/src/examples/slickgrid/example33.scss, demos/aurelia/src/examples/slickgrid/example33.ts, demos/react/src/examples/slickgrid/Example33.tsx, demos/react/src/examples/slickgrid/example33.scss, demos/vanilla/src/examples/example16.scss, demos/vanilla/src/examples/example16.ts, demos/vue/src/components/Example33.vue, docs/migrations/migration-to-9.x.md, frameworks/angular-slickgrid/docs/migrations/migration-to-9.x.md, frameworks/angular-slickgrid/src/demos/examples/example33.component.scss, frameworks/angular-slickgrid/src/demos/examples/example33.component.ts, frameworks/aurelia-slickgrid/docs/migrations/migration-to-9.x.md, frameworks/slickgrid-react/docs/migrations/migration-to-9.x.md, frameworks/slickgrid-vue/docs/migrations/migration-to-9.x.md, packages/common/src/interfaces/customTooltipOption.interface.ts, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-plugins.scss, packages/custom-tooltip-plugin/src/__tests__/slickCustomTooltip.spec.ts, packages/custom-tooltip-plugin/src/slickCustomTooltip.ts
- removing the Arrow pointer from the Custom Tooltip because it was often showing at the wrong place because of its fixed position, so I think it's better to just remove it completely and just keep tooltip auto-positioning and that should be more than sufficient.
- this also helps decreasing the build size by about 2kb (less code but also less CSS)
=> fix!: remove Arrow pointer from Custom Tooltip

packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/services/resizer.service.ts, packages/common/src/styles/_variables.scss
- partially rolling back a small change made in PR https://github.com/ghiscoding/slickgrid-universal/pull/1961
- use `Math.fround` (float) instead of `Math.floor` (int) for column width calculations, it helps with some grids but not all of them
trying again to fix the issue shown below, this issue is only happening in some Chromium browsers, it's rare but it does show then it shows consistently and it never happens in Firefox. I'm assuming this issue is caused by Chrome miscalculating the width (possibly because of float precision) and when that happens the scrollbar shows too early. In the case below, our grid container is 800px, we remove 15px for scrollbar and so we have 785px left for the columns and it's supposed to fit perfectly... but for some reasons, some browsers show the …
=> fix(core): small UI regression causing column width to be smaller

packages/common/src/core/slickGrid.ts, packages/common/src/styles/extra-styling.scss, packages/common/src/styles/slick-editors.scss, packages/common/src/styles/slick-grid.scss, packages/common/src/styles/slick-plugins.scss, packages/common/src/styles/slick-without-bootstrap-min-styling.scss
- rollback again #1973 because it still causes UI issues, so we're pretty much back to the original code (before v9)
- also cleanup SASS files and also remove unnecessary `::ms-*` styling since we're no longer supporting any MS IE browsers
=> fix(core): rollback slickgrid width UI change & drop `::ms` styling

packages/common/src/services/resizer.service.ts
- another trial at fixing or I should patching the issue I first tried to fix in #1961, this new patch seems to work a lot better though and is much more safe which is just to add `0.2px` to the grid container but only after the grid columns autosize is called.
- this is just a patch because in the end, I'm pretty sure that it's a Chromium bug because this issue never shows in Firefox and I would guess that it's caused by a floating precision which could differ on different computers. There are some open Chromium bugs for similar things but it could take a very long time before any fix comes in, so let's patch it since we can
=> fix: Chromium patch to avoid showing scrollbar too early

demos/react/package.json, frameworks/angular-slickgrid/package.json, frameworks/slickgrid-react/package.json, pnpm-lock.yaml
- no longer needed since this was introduced for IE specifically but since it is no longer needed, we can safely remove it all
=> chore(deps): remove unused custom event polyfill

packages/common/src/editors/dateEditor.ts, packages/common/src/services/filter.service.ts, packages/common/src/services/pagination.service.ts, packages/utils/src/__tests__/utils.spec.ts, packages/utils/src/utils.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- another 1 of those "regular JS code fails in Salesforce LWC with locker service".... so `queueMicrotask` isn't supported but `setTimeout` is fine, so let's add a wrapper function with try/catch to fallback to `setTimeout` when `queueMicrotask` isn't available
=> fix: fallback to `setTimeout` when `queueMicrotask` fails in SF

packages/event-pub-sub/src/eventPubSub.service.spec.ts, packages/event-pub-sub/src/eventPubSub.service.ts
I previously changed the `getEventNameByNamingConvention()` implementation in commit 1b93a341 but introduced a regression without detecting it because of proper unit tests
=> fix(pubsub): event naming convention incorrect in Salesforce

packages/common/src/extensions/slickCellExternalCopyManager.ts, packages/common/src/formatters/formatterUtilities.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/vanilla-force-bundle/src/salesforce-global-grid-options.ts
- default browser clipboard API doesn't seem to work in Salesforce LWC, so let's add an override but only in the Salesforce global grid options.
=> fix: use custom clipboard override when native API unsupported in SF

docs/column-functionalities/filters/input-filter.md, docs/column-functionalities/filters/select-filter.md, frameworks/angular-slickgrid/docs/column-functionalities/filters/input-filter.md, frameworks/angular-slickgrid/docs/column-functionalities/filters/select-filter.md, frameworks/aurelia-slickgrid/docs/column-functionalities/filters/input-filter.md, frameworks/aurelia-slickgrid/docs/column-functionalities/filters/select-filter.md, frameworks/slickgrid-react/docs/column-functionalities/filters/input-filter.md, frameworks/slickgrid-vue/docs/column-functionalities/filters/input-filter.md, packages/common/src/filters/inputFilter.ts, packages/common/src/services/__tests__/filter.service.spec.ts
this PR expands the previous PR #2016 
By default, we should be able to filter empty values using the default input filter and then using Grid State/Preset should also work when reloading the grid with Grid Preset. This was even more problematic when using a Tree Data grid
=> fix(filter): input filter empty values & save GridState/Preset

frameworks/slickgrid-react/src/components/slickgrid-react.tsx, frameworks/slickgrid-vue/src/components/SlickgridVue.vue, packages/common/src/services/filter.service.ts, packages/composite-editor-component/src/slick-composite-editor.component.ts, packages/utils/src/utils.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
partially reverting PR #1516 and reimplement previous custom `deepCopy()` function, because I found that `jQuery.extend()` (which is `node-extend` implementation in here) does not properly do a deep copy for array of objects as described in this Stack Overflow: [`jquery.extend(true, [], obj)` not creating a deep copy](https://stackoverflow.com/questions/16512773/jquery-extendtrue-obj-not-creating-a-deep-copy)
So let's reimplement the same custom code I had before in `deepCopy()` function and replace any usage of `extend(true, [], arr1, arr2)` with `deepCopy(arr1, arr2)`. Deep copy of an object should still be ok though, it's mainly array which might be the problem. 
This issue came up in Salesforce LWC because SF doesn't allow extending or modify a proxy object, so we do a deep copy of …
=> fix: partial revert of PR #1516 custom deepCopy() for array in SF/LWC

packages/common/src/services/domUtilities.ts, packages/common/src/styles/_variables.scss, packages/common/src/styles/slick-editors.scss, pnpm-lock.yaml, pnpm-workspace.yaml
This PR is a follow-up of a recent PR #2048, but it now properly fixes the ms-select width and positioning via a new ms-select version but also via a few CSS fixes in here too. 
This PR fixes or improves the following:
- now correctly calculates drop width by widest text
-  the previous code wasn't very accurate and had few issues
- better positioning of the drop 
- the drop wasn't always correctly positioned especially in the Composite Editor modal window
- better styling 
- some border and width styles weren't correctly following other filter/editor
=> fix: followup of PR #2048 ms-select width/position/styling, fixes #2044

packages/common/src/extensions/__tests__/slickCellMenu.plugin.spec.ts, packages/common/src/extensions/__tests__/slickContextMenu.spec.ts, packages/common/src/extensions/__tests__/slickGridMenu.spec.ts, packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts, packages/common/src/extensions/menuBaseClass.ts, packages/common/src/extensions/menuFromCellBaseClass.ts, packages/common/src/extensions/slickCellMenu.ts, packages/common/src/extensions/slickContextMenu.ts, packages/common/src/extensions/slickGridMenu.ts, packages/common/src/extensions/slickHeaderMenu.ts, packages/common/src/interfaces/gridMenuOption.interface.ts
Reconciling all Menu plugins `repositionMenu()` functions into a single location for all these menu plugins:
- Cell Menu
- Context Menu
- Grid Menu
- Header Menu
This saves about 100 lines of code (even though codecov is only showing 36 lines)
=> perf: reconcile multiple `repositionMenu()` into single fn for all menus

packages/common/src/extensions/__tests__/slickGridMenu.spec.ts, packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts, packages/common/src/extensions/menuBaseClass.ts
- use offsetHeight for cell menu positioning to be equivalent to the same position as prior to PR #2071
=> chore: use offsetHeight instead of clientHeight for cell menu position

demos/aurelia/src/examples/slickgrid/example28.ts, demos/react/src/examples/slickgrid/Example28.tsx, demos/vanilla/src/examples/example06.ts, demos/vue/src/components/Example28.vue, frameworks/angular-slickgrid/src/demos/examples/example28.component.ts, frameworks/angular-slickgrid/src/library/components/__tests__/angular-slickgrid.component.spec.ts, frameworks/angular-slickgrid/src/library/components/angular-slickgrid.component.ts, frameworks/aurelia-slickgrid/src/custom-elements/aurelia-slickgrid.ts, frameworks/slickgrid-react/src/components/slickgrid-react.tsx, frameworks/slickgrid-vue/src/components/SlickgridVue.vue, packages/common/src/services/__tests__/treeData.service.spec.ts, packages/common/src/services/treeData.service.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
The `initiallyCollapsed` option for Tree Data was working fine for a parent/child dataset but it wasn't working at all for a hierarchical (tree) dataset. This fixes it and it now works for both types
=> fix: `initiallyCollapsed` should work with hierarchical tree dataset

packages/utils/src/__tests__/domUtils.spec.ts, packages/utils/src/domUtils.ts, test/vitest.config.mts
The previous html decode wasn't decoding entities with numbers (e.g. `&#233;`). The new code uses the browser to decode without executing any JS code, so it's still XSS safe and will decode everything a browser can decode
=> fix: htmlDecode should work with number entities `é` is `&#233;`

.github/workflows/test-aurelia.yml, .vscode/launch.json, demos/aurelia/src/examples/slickgrid/example13.ts, demos/aurelia/test/cypress.config.ts, demos/aurelia/test/cypress/e2e/example13.cy.ts, demos/aurelia/vite.config.mts, demos/react/src/examples/slickgrid/Example13.tsx, demos/react/test/cypress/e2e/example13.cy.ts, demos/vanilla/src/examples/example02.ts, demos/vue/src/components/Example13.vue, demos/vue/test/cypress/e2e/example13.cy.ts, frameworks/angular-slickgrid/src/demos/examples/example13.component.ts, frameworks/angular-slickgrid/test/cypress/e2e/example13.cy.ts, test/cypress/e2e/example02.cy.ts
- I think it's better to load the Grouping grids with a default Group by Duration, to highlight grouping from the "get go"
- also change Aurelia demo port from 9000 to 7900 since 9000 is restricted in some domains
=> chore: always load Grouping grids with a Group by Duration

demos/aurelia/src/examples/slickgrid/example27.html, demos/react/src/examples/slickgrid/Example27.tsx, demos/vanilla/src/examples/example05.html, demos/vue/src/components/Example27.vue, frameworks/angular-slickgrid/src/demos/examples/example27.component.html, packages/common/src/services/__tests__/treeData.service.spec.ts, packages/common/src/services/treeData.service.ts, packages/common/src/services/utilities.ts
improve perf toggle of expand/collapse all tree data items by toggling all props on both hierarchical/flat datasets. The previous code was toggling all flat but then re-converting the flat to hierarchical dataset, that was however less performant compare to simply toggling the collapsed prop in both datasets.
before: ~96ms
after: ~64ms
smaller: ~33% faster 
It was still pretty fast before, but hey why not go even faster :)
=> perf: improve expand/collapse all tree data items

demos/aurelia/src/examples/slickgrid/example18.ts, demos/aurelia/test/cypress/e2e/example18.cy.ts, demos/react/src/examples/slickgrid/Example18.tsx, demos/react/test/cypress/e2e/example18.cy.ts, demos/vanilla/src/examples/example03.ts, demos/vue/src/components/Example18.vue, demos/vue/test/cypress/e2e/example18.cy.ts, docs/grid-functionalities/grid-state-preset.md, frameworks/angular-slickgrid/docs/TOC.md, frameworks/angular-slickgrid/docs/column-functionalities/filters/select-filter.md, frameworks/angular-slickgrid/docs/grid-functionalities/Row-Selection.md, frameworks/angular-slickgrid/docs/grid-functionalities/grid-state-preset.md, frameworks/angular-slickgrid/src/demos/examples/example18.component.ts, frameworks/angular-slickgrid/test/cypress/e2e/example18.cy.ts, frameworks/aurelia-slickgrid/docs/column-functionalities/filters/select-filter.md, frameworks/aurelia-slickgrid/docs/grid-functionalities/grid-state-preset.md, frameworks/slickgrid-react/docs/column-functionalities/filters/select-filter.md, frameworks/slickgrid-react/docs/grid-functionalities/grid-state-preset.md, frameworks/slickgrid-vue/docs/column-functionalities/filters/select-filter.md, frameworks/slickgrid-vue/docs/grid-functionalities/grid-state-preset.md, packages/common/src/enums/gridStateType.enum.ts, packages/common/src/extensions/__tests__/slickDraggableGrouping.spec.ts, packages/common/src/extensions/slickDraggableGrouping.ts, packages/common/src/interfaces/gridState.interface.ts, packages/common/src/services/__tests__/gridState.service.spec.ts, packages/common/src/services/gridState.service.ts
- add Grouping to Grid State
- for Grid Presets it only works with Draggable Grouping since regular Grouping requires much more setup and only Draggable Grouping accepts an `initialGroupBy: []` value
=> feat: add Grouping to Grid State

packages/common/src/extensions/__tests__/slickCellRangeDecorator.spec.ts, packages/common/src/extensions/slickCellRangeDecorator.ts, packages/common/src/interfaces/cellRange.interface.ts
Thanks to Ben for adding this new feature via SlickGrid PR: 
https://github.com/6pac/SlickGrid/pull/1140
Note that this is used in the next PR, it's not directly used at the moment. This is the drag-fill feature, and this PR allows the drag-fill selection to look different to the initial selection.
It's very simple, but it's just logically separate to the rest, so I'm separating it.
=> feat: add second css property to RangeDecorator plugin

frameworks/angular-slickgrid/src/library/components/__tests__/angular-slickgrid.component.spec.ts, frameworks/angular-slickgrid/src/library/components/angular-slickgrid.component.ts, frameworks/aurelia-slickgrid/src/custom-elements/aurelia-slickgrid.ts, frameworks/slickgrid-react/src/components/slickgrid-react.tsx, frameworks/slickgrid-vue/src/components/SlickgridVue.vue, packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts, packages/common/src/extensions/slickHeaderMenu.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/services/__tests__/grid.service.spec.ts, packages/common/src/services/grid.service.ts, packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts, packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts, packages/vanilla-force-bundle/src/__tests__/vanilla-force-bundle.spec.ts, test/cypress/e2e/example17.cy.ts
- fully reimplement frozen column check because PR #2129 was causing a big negative side effect in our Salesforce implementation and in some occasions even hang the browser because it would fall into infinite loop when trying to resize the browser smaller than visible pinned column (this is caused by the constant auto-resize loop that is required for it to work in Salesforce)
- the fix is really to **only** inspect it once when changing or assigning the grid options, and **not** do it on every column or grid resize which is what the previous code was doing. So doing the check only when assigning is a much lighter approach and will not trigger a recheck every column/grid resize like previously which was way too much and caused the issue mentioned above.
=> fix: validate allowed frozen column only when setting grid options

docs/grid-functionalities/frozen-columns-rows.md, frameworks/angular-slickgrid/docs/grid-functionalities/frozen-columns-rows.md, frameworks/aurelia-slickgrid/docs/grid-functionalities/frozen-columns-rows.md, frameworks/slickgrid-react/docs/grid-functionalities/frozen-columns-rows.md, frameworks/slickgrid-vue/docs/grid-functionalities/frozen-columns-rows.md, packages/common/src/core/__tests__/slickGrid.spec.ts, packages/common/src/core/slickGrid.ts, packages/common/src/extensions/__tests__/slickColumnPicker.spec.ts, packages/common/src/extensions/__tests__/slickGridMenu.spec.ts, packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts, packages/common/src/extensions/extensionCommonUtils.ts, packages/common/src/extensions/slickHeaderMenu.ts, packages/common/src/interfaces/gridOption.interface.ts, packages/common/src/services/__tests__/grid.service.spec.ts, test/cypress/e2e/example04.cy.ts, test/cypress/e2e/example17.cy.ts
- if a user tries to hide too many columns on the right side of the column freeze, it would make the UI unusable. So we need to add a validation function to make sure that there's at least 1 or more column on the right side of the column freeze/pinning to avoid UI problems
- the new code will now show an alert of the error when invalid and will abort the action
=> fix: validate to always have 1 or more column on right freeze section

demos/aurelia/src/examples/slickgrid/example47-detail-view.html, demos/aurelia/src/examples/slickgrid/example47.html, demos/aurelia/test/cypress/e2e/example47.cy.ts, demos/react/src/examples/slickgrid/Example47-detail-view.tsx, demos/react/src/examples/slickgrid/Example47.tsx, demos/react/test/cypress/e2e/example47.cy.ts, demos/vanilla/src/examples/example36.html, demos/vanilla/src/examples/example36.ts, demos/vue/src/components/Example47.vue, demos/vue/src/components/Example47Detail.vue, demos/vue/test/cypress/e2e/example47.cy.ts, frameworks/angular-slickgrid/src/demos/examples/example47-rowdetail.component.html, frameworks/angular-slickgrid/src/demos/examples/example47.component.html, frameworks/angular-slickgrid/src/library/extensions/__tests__/slickRowDetailView.spec.ts, frameworks/angular-slickgrid/test/cypress/e2e/example47.cy.ts, packages/common/src/core/__tests__/slickDataView.spec.ts, packages/common/src/core/slickCore.ts, packages/common/src/core/slickDataview.ts, packages/row-detail-view-plugin/src/slickRowDetailView.spec.ts, packages/row-detail-view-plugin/src/slickRowDetailView.ts, test/cypress/e2e/example36.cy.ts
This fixes an issue that I only found in the vanilla implementation of Row Detail, the issue was that there's a "Click Me" button inside each Row Detail and it worked fine the first time we open the Row Detail but then if we collapse a Group (single and/or all groups) then the button click stopped working. Again I'm not exactly why it still worked in all other framework wrappers, but still we should consider the Row Detail to be out of the viewport when we collapse a data Group (because it's no longer visible, hence considered to be "out of viewport" so that we can trigger some events related that change, which are remove all button events and re-add them back when we open the Group again)
=> fix: toggling Row Detail under a Group should become out of viewport

demos/aurelia/src/examples/slickgrid/utilities.ts, demos/react/src/examples/slickgrid/utilities.ts, demos/vanilla/src/examples/utilities.ts, demos/vue/src/components/utilities.ts, frameworks/angular-slickgrid/src/demos/examples/utilities.ts
popover should be supported by all browser, but let's use a fallback until at least next major release since it's considered as Baseline 2024
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/showPopover
This is a custom toast, it's just used by the examples and is a mainly a playground to test before using it in the future in our Custom Tooltip (though that will take much longer, since I also want to use css-anchor for Custom Tooltip and this is still not supported by Firefox yet, hopefully by end of 2025, they will)
=> chore: use native popover to show custom toast
