- packages/common/src/interfaces/externalResource.interface.ts
- packages/common/src/interfaces/gridOption.interface.ts
- packages/common/src/interfaces/index.ts
- packages/common/src/services/excelExport.service.ts
- packages/common/src/services/textExport.service.ts
- packages/composite-editor-component/src/slick-composite-editor.component.ts
- packages/empty-warning-component/src/slick-empty-warning.component.ts
- packages/empty-warning-component/src/slick-empty-warning.spec.ts
- packages/excel-export/src/excelExport.service.ts
- packages/text-export/src/textExport.service.ts
- packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts
- packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- create new ExternalResource interface and make all external resources (components/services) implement it
> fix(components): refactor to use registerExternalResources grid option

- examples/webpack-demo-vanilla-bundle/package.json
- examples/webpack-demo-vanilla-bundle/src/examples/example04.ts
- examples/webpack-demo-vanilla-bundle/src/examples/icons.ts
- examples/webpack-demo-vanilla-bundle/webpack.config.js
- packages/common/src/editors/__tests__/autoCompleteEditor.spec.ts
- packages/common/src/editors/__tests__/selectEditor.spec.ts
- packages/common/src/editors/autoCompleteEditor.ts
- packages/common/src/editors/checkboxEditor.ts
- packages/common/src/editors/dateEditor.ts
- packages/common/src/editors/dualInputEditor.ts
- packages/common/src/editors/floatEditor.ts
- packages/common/src/editors/integerEditor.ts
- packages/common/src/editors/longTextEditor.ts
- packages/common/src/editors/selectEditor.ts
- packages/common/src/editors/sliderEditor.ts
- packages/common/src/editors/textEditor.ts
- packages/common/src/interfaces/collectionOverrideArgs.interface.ts
- packages/common/src/interfaces/column.interface.ts
- packages/common/src/interfaces/columnEditor.interface.ts
- packages/common/src/interfaces/index.ts
- packages/common/src/styles/material-svg-icons.scss
- yarn.lock
- only applies to Editor with collection (autocomplete & single/multiple select)
> feat(editors): add Column Editor collectionOverride option

- packages/common/src/editors/autoCompleteEditor.ts
- packages/common/src/editors/checkboxEditor.ts
- packages/common/src/editors/dateEditor.ts
- packages/common/src/editors/dualInputEditor.ts
- packages/common/src/editors/floatEditor.ts
- packages/common/src/editors/integerEditor.ts
- packages/common/src/editors/longTextEditor.ts
- packages/common/src/editors/multipleSelectEditor.ts
- packages/common/src/editors/selectEditor.ts
- packages/common/src/editors/singleSelectEditor.ts
- packages/common/src/editors/sliderEditor.ts
- packages/common/src/editors/textEditor.ts
- also changed all services to readonly
> feat(editors): change all private keyword to protected for extensability

- packages/common/src/enums/operatorType.enum.ts
- packages/common/src/filter-conditions/__tests__/collectionSearchFilterCondition.spec.ts
- packages/common/src/filter-conditions/__tests__/filterUtilities.spec.ts
- packages/common/src/filter-conditions/executeMappedCondition.ts
- packages/common/src/filter-conditions/filterUtilities.ts
- using indexOf returns true whenever the substring is found within a string and that could cause issue, for example "Task1" will be found in "Task123" but that shouldn't be accepted
> fix(filters): don't use indexOf NOT_IN_CONTAINS

- packages/common/src/filters/__tests__/compoundDateFilter.spec.ts
- packages/common/src/filters/__tests__/compoundInputFilter.spec.ts
- packages/common/src/filters/__tests__/compoundSliderFilter.spec.ts
- packages/common/src/filters/compoundDateFilter.ts
- packages/common/src/filters/compoundInputFilter.ts
- packages/common/src/filters/compoundSliderFilter.ts
- packages/common/src/interfaces/columnFilter.interface.ts
- packages/common/src/interfaces/index.ts
- packages/common/src/interfaces/operatorDetail.interface.ts
- see [Wiki - Custom Compound Operator List](https://github.com/ghiscoding/slickgrid-universal/wiki/Compound-Filters#compound-operator-list-custom-list)
> feat(filters): option to add custom compound operator list

- packages/binding/package.json
- packages/composite-editor-component/package.json
- packages/custom-footer-component/package.json
- packages/empty-warning-component/package.json
- packages/event-pub-sub/package.json
- packages/pagination-component/package.json
- packages/rxjs-observable/package.json
- packages/vanilla-bundle/package.json
- on the other end we shouldn't include "directories", it should be "files" only that we want to include
> fix(build): the "files" property should be included in pkg.json

- examples/webpack-demo-vanilla-bundle/src/examples/example16.ts
- packages/excel-export/package.json
- packages/excel-export/src/excelExport.service.ts
- packages/text-export/src/textExport.service.ts
- yarn.lock
- also fix a number cell format in Excel export
> fix(export): sanitize any html that could exist in header titles

- examples/webpack-demo-vanilla-bundle/assets/i18n/en.json
- examples/webpack-demo-vanilla-bundle/assets/i18n/fr.json
- packages/common/src/constants.ts
- packages/common/src/extensions/gridMenuExtension.ts
- packages/common/src/interfaces/locale.interface.ts
- packages/vanilla-bundle/src/salesforce-global-grid-options.ts
- fixes an issue raised by the other team while translating grids to French
> fix(translation): add new UNFREEZE_COLUMNS to fix translation

- packages/common/src/services/treeData.service.ts
> fix(treeGrid): Bug in onCellClick event

- packages/common/src/filters/selectFilter.ts
Fix bug when using "updateFilters" method on fields with selection filter in adding "filled" class for styling purposes
> fix(filter): add the "filled" class for styling purposes 

- package.json
- packages/common/src/extensions/__tests__/slickRowMoveManager.spec.ts
- packages/common/src/extensions/__tests__/slickRowSelectionModel.spec.ts
- packages/common/src/extensions/slickCellRangeSelector.ts
- packages/common/src/extensions/slickRowMoveManager.ts
- packages/common/src/extensions/slickRowSelectionModel.ts
- packages/common/src/interfaces/column.interface.ts
- packages/common/src/interfaces/rowMoveManagerOption.interface.ts
- packages/common/src/interfaces/rowSelectionModelOption.interface.ts
- packages/common/src/services/extension.service.ts
- test/cypress/integration/example17.spec.js
- yarn.lock
- add auto-scroll on RowMoveManager, this is a continuation of previous PR #662
> feat(plugins): Apply auto scroll when dragging on RowMoveManager plugin

- package.json
As discussed here https://github.com/ghiscoding/slickgrid-universal/discussions/585
> fix(build): optimize dev watch

- examples/webpack-demo-vanilla-bundle/src/app.ts
- examples/webpack-demo-vanilla-bundle/src/examples/example01.ts
- examples/webpack-demo-vanilla-bundle/src/examples/example18.ts
- packages/common/src/extensions/menuBaseClass.ts
- packages/common/src/extensions/slickDraggableGrouping.ts
- packages/common/src/filters/compoundDateFilter.ts
- packages/common/src/filters/dateRangeFilter.ts
- packages/common/src/services/__tests__/bindingEvent.service.spec.ts
- packages/common/src/services/bindingEvent.service.ts
- packages/common/src/services/extension.service.ts
- packages/common/src/services/filter.service.ts
- packages/composite-editor-component/src/compositeEditor.factory.spec.ts
- packages/composite-editor-component/src/compositeEditor.factory.ts
- packages/composite-editor-component/src/slick-composite-editor.component.ts
- packages/custom-footer-component/src/slick-footer.component.ts
- packages/event-pub-sub/src/eventPubSub.service.spec.ts
- packages/event-pub-sub/src/eventPubSub.service.ts
- packages/excel-export/src/excelExport.service.spec.ts
- packages/excel-export/src/excelExport.service.ts
- packages/text-export/src/textExport.service.spec.ts
- packages/text-export/src/textExport.service.ts
- packages/vanilla-bundle/src/components/__tests__/slick-vanilla-grid.spec.ts
- packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- note that Flatpickr still has some mem/event leaks but a fix was put in place, we are just waiting for a new version release from their side to fix that leak
- also fixed some leaks in my own custom rendered SPA, technically that shouldn't be a problem in a regular SPA framework
> fix(memory): clear & dispose of grid to avoid mem leaks & detached elm

- examples/webpack-demo-vanilla-bundle/src/examples/example09.ts
- packages/odata/src/services/__tests__/grid-odata.service.spec.ts
- packages/odata/src/services/grid-odata.service.ts
- test/cypress/integration/example09.spec.js
Fixes https://github.com/ghiscoding/slickgrid-universal/issues/604 for the odata backend.
> fix(odata): fix range filtering with ".."

- packages/graphql/src/services/__tests__/graphql.service.spec.ts
- packages/graphql/src/services/graphql.service.ts
- test/cypress/integration/example10.spec.js
- range filter was no longer working for GraphQL backend Service
> fix(graphql): fix range filtering with ".."

- examples/webpack-demo-vanilla-bundle/src/examples/example11.ts
- examples/webpack-demo-vanilla-bundle/src/examples/example16.ts
- packages/common/src/editors/__tests__/sliderEditor.spec.ts
- packages/common/src/editors/sliderEditor.ts
- packages/common/src/filters/__tests__/singleSelectFilter.spec.ts
- packages/common/src/filters/__tests__/sliderRangeFilter.spec.ts
- packages/common/src/filters/sliderFilter.ts
- packages/common/src/interfaces/columnEditor.interface.ts
- packages/common/src/interfaces/columnFilter.interface.ts
- packages/common/src/interfaces/sliderOption.interface.ts
- packages/common/src/styles/_variables.scss
- packages/common/src/styles/slick-plugins.scss
- test/cypress/e2e/example07.cy.js
- test/cypress/e2e/example11.cy.js
- test/cypress/e2e/example12.cy.js
- after merging all Slider filters and changing all its styling, the Slider editor also needs to be updated to use same code
- this PR also adds the slider track filling color that previous Slider filter PR brought
> fix(editors): Slider editor track not showing after Slider filter change

- examples/webpack-demo-vanilla-bundle/src/examples/example16.ts
- packages/custom-tooltip-plugin/src/__tests__/slickCustomTooltip.spec.ts
- packages/custom-tooltip-plugin/src/slickCustomTooltip.ts
- custom alignment of tooltip were inverted to the user's expectation, this PR fixes that
> fix(toolip): left & right align were inverted

- packages/common/src/extensions/__tests__/slickCheckboxSelectColumn.spec.ts
- packages/common/src/extensions/slickCheckboxSelectColumn.ts
- packages/common/src/extensions/slickRowMoveManager.ts
- packages/row-detail-view-plugin/src/slickRowDetailView.spec.ts
- packages/row-detail-view-plugin/src/slickRowDetailView.ts
- some addons are adding special columns dynamically (Row Move, Row Detail & Row Selection) and in rare occasion it could end up adding the same special column multiple time
> fix(addons): do not add special columns twice (like Row Selection)

- .github/workflows/cypress.yml
- update a few GitHub Actions plugins to their latest versions
> chore: update GitHub Actions to use latest versions

- packages/common/src/services/__tests__/grid.service.spec.ts
- packages/common/src/services/grid.service.ts
- refers to Angular-Slickgrid issue https://github.com/ghiscoding/Angular-Slickgrid/issues/1167
> chore: throw when `addItem` is called with top position and Tree Data

- examples/vite-demo-vanilla-bundle/package.json
- packages/common/package.json
- pnpm-lock.yaml
this version had a small breaking change with `customFilter` argument signature, but that shouldn't affect this project since it wasn't using that directly
> chore(deps); upgrade to latest version of multiple-select-vanilla

- packages/common/src/services/__tests__/filter.service.spec.ts
- packages/common/src/services/filter.service.ts
- test/cypress/e2e/example06.cy.ts
- this PR fixes an issue where the Tree Totals were not being updated for collapsed items when filtering
> fix(TreeData): auto-recalc should update totals for collapsed items too

- packages/common/src/editors/autocompleterEditor.ts
- packages/common/src/editors/dualInputEditor.ts
- packages/common/src/editors/floatEditor.ts
- packages/common/src/editors/inputEditor.ts
- packages/common/src/editors/integerEditor.ts
- packages/common/src/filters/autocompleterFilter.ts
- packages/common/src/filters/inputFilter.ts
- it seems that input `autocomplete: none` is invalid, we should be using `off` instead and we can also add `ariaAutoComplete: none`
> chore: off input autocomplete

- tsconfig.base.json
- see this SO for ref: https://stackoverflow.com/a/75873587/1212166
> chore: remove baseUrl to fix import relative path in Lerna

- .github/renovate.json5
- examples/vite-demo-vanilla-bundle/src/app-routing.ts
- examples/vite-demo-vanilla-bundle/src/app.html
- examples/vite-demo-vanilla-bundle/src/examples/example18.ts
- examples/vite-demo-vanilla-bundle/src/examples/example19.ts
- examples/vite-demo-vanilla-bundle/src/examples/example20.html
- examples/vite-demo-vanilla-bundle/src/examples/example20.ts
- package.json
- packages/common/package.json
- packages/common/src/extensions/__tests__/slickDraggableGrouping.spec.ts
- packages/common/src/extensions/__tests__/slickGridMenu.spec.ts
- packages/common/src/extensions/slickDraggableGrouping.ts
- packages/common/src/extensions/slickGridMenu.ts
- packages/common/src/extensions/slickHeaderMenu.ts
- packages/common/src/interfaces/gridOption.interface.ts
- packages/common/src/services/__tests__/extension.service.spec.ts
- packages/vanilla-bundle/package.json
- pnpm-lock.yaml
- test/cypress/e2e/example20.cy.ts
> feat: add support for grid inside Shadow DOM

- .github/workflows/cypress.yml
- .github/workflows/main.yml
- test/cypress.config.ts
- test/cypress/e2e/example01.cy.ts
- test/cypress/e2e/example02.cy.ts
- test/cypress/e2e/example03.cy.ts
- test/cypress/e2e/example04.cy.ts
- test/cypress/e2e/example05.cy.ts
- test/cypress/e2e/example06.cy.ts
- test/cypress/e2e/example07.cy.ts
- test/cypress/e2e/example08.cy.ts
- test/cypress/e2e/example09.cy.ts
- test/cypress/e2e/example10.cy.ts
- test/cypress/e2e/example11.cy.ts
- test/cypress/e2e/example12.cy.ts
- test/cypress/e2e/example13.cy.ts
- test/cypress/e2e/example14.cy.ts
- test/cypress/e2e/example15.cy.ts
- test/cypress/e2e/example16.cy.ts
- test/cypress/e2e/example17.cy.ts
- test/cypress/e2e/example18.cy.ts
- test/cypress/e2e/example19.cy.ts
- test/cypress/e2e/example20.cy.ts
- see https://docs.cypress.io/guides/references/experiments/#Experimental-Flake-Detection-Features
> chore: use Cypress new experimental option `experimentalStrategy`

- packages/common/src/core/slickDataview.ts
- old IE era code, it should be safe to remove since IE is no longer supported
> chore: remove old IE era unused code DataView `fastSort`

- examples/vite-demo-vanilla-bundle/src/examples/example12.ts
- packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
> chore(demo): Unsaved Cell CSS Styling should follow pagination

- packages/common/src/core/__tests__/slickGrid.spec.ts
- packages/common/src/core/slickGrid.ts
- packages/utils/src/__tests__/utils.spec.ts
- packages/utils/src/utils.ts
- also add extra `isDefinedNumber()` to fix issue with number returning `NaN` when used with `isDefined()` which was invalid
> chore(tests): add SlickGrid tests getCellFromEvent/getCellFromPoint

- examples/vite-demo-vanilla-bundle/src/examples/example22.html
- examples/vite-demo-vanilla-bundle/src/examples/example22.ts
- packages/common/src/extensions/__tests__/slickRowBasedEdit.spec.ts
- packages/common/src/extensions/slickRowBasedEdit.ts
- test/cypress/e2e/example22.cy.ts
- test/translateServiceStub.ts
- change fetch response alert with notification in UI
- add missing unit tests for translation
> chore: add missing tests for RowBaseEditor & tweak UI

- packages/common/src/styles/slick-bootstrap.scss
- as per Angular-Slickgrid opened [issue](https://github.com/ghiscoding/Angular-Slickgrid/issues/1368)
> fix(styling): add full width to grid container

- packages/common/src/interfaces/__tests__/column.interface.spec.ts
- packages/common/src/interfaces/column.interface.ts
> fix: Join type

- packages/common/src/extensions/__tests__/slickColumnPicker.spec.ts
- packages/common/src/extensions/__tests__/slickContextMenu.spec.ts
- packages/common/src/extensions/__tests__/slickGridMenu.spec.ts
- packages/common/src/extensions/__tests__/slickHeaderMenu.spec.ts
- packages/common/src/extensions/slickColumnPicker.ts
- packages/common/src/extensions/slickContextMenu.ts
- packages/common/src/extensions/slickGridMenu.ts
- packages/common/src/extensions/slickHeaderMenu.ts
- clicking a grid cell should close any opened menu, except Cell Menu.
> fix(plugins): clicking a grid cell should close any open menu

- examples/vite-demo-vanilla-bundle/src/examples/example09.ts
- examples/vite-demo-vanilla-bundle/src/examples/example10.ts
- examples/vite-demo-vanilla-bundle/src/examples/example14.ts
- examples/vite-demo-vanilla-bundle/src/examples/example15.ts
- packages/common/src/filter-conditions/stringFilterCondition.ts
- packages/common/src/services/filter.service.ts
- packages/graphql/src/services/__tests__/graphql.service.spec.ts
- packages/graphql/src/services/graphql.service.ts
- packages/odata/src/services/__tests__/grid-odata.service.spec.ts
- packages/odata/src/services/grid-odata.service.ts
- test/cypress/e2e/example09.cy.ts
- test/cypress/e2e/example10.cy.ts
- test/cypress/e2e/example15.cy.ts
> feat(filters): add StartsWith/EndsWith (`a*z`) to OData/GraphQL

- examples/vite-demo-vanilla-bundle/src/examples/example18.scss
- examples/vite-demo-vanilla-bundle/src/examples/example18.ts
> chore: add sparkline tooltip to trading demo

- test/cypress/e2e/example14.cy.ts
- just try to move the failing describe block to an earlier describe block and see if that helps because Cypress is weird sometime and it fails for no reason.
- Cypress is very strange sometime, below is the Cypress failure which as you can see is... blank, why??? no clue since it shouldn't and it seemed to have change location for whatever reason even though I didn't ask to
> chore(tests): try to fix Example 14 sometime flaky Cypress test

- test/cypress/e2e/example10.cy.ts
add a bit more Cypress E2E tests related to previous PR #1545
> chore(tests): add more Cypress E2E tests related to PR #1545

- packages/common/src/filters/__tests__/autocompleterFilter.spec.ts
- packages/common/src/filters/__tests__/compoundDateFilter.spec.ts
- packages/common/src/filters/__tests__/compoundSliderFilter.spec.ts
- packages/common/src/filters/__tests__/inputFilter.spec.ts
- packages/common/src/filters/__tests__/selectFilter.spec.ts
- packages/common/src/filters/autocompleterFilter.ts
- packages/common/src/filters/dateFilter.ts
- packages/common/src/filters/inputFilter.ts
- packages/common/src/filters/selectFilter.ts
- packages/common/src/filters/sliderFilter.ts
- packages/common/src/interfaces/filter.interface.ts
- test/cypress/e2e/example09.cy.ts
- test/cypress/e2e/example15.cy.ts
- related to issue #1569 which will help to implement the new feature and eventually close the issue
> feat(filters): add `setValues()` optional flag to trigger query

- examples/vite-demo-vanilla-bundle/src/examples/example03.ts
- packages/common/src/editors/dateEditor.ts
- test/cypress/e2e/example03.cy.ts
- open date editor and select a date, then reopen the same date picker should still have the same date and it wasn't
> fix(editor): selecting date editor then reopen should have same date

- packages/common/src/styles/_variables.scss
Add missing semicolon in line 1147 of _variables.scss
> fix(styles): Add missing semicolon in line 1147 of _variables.scss

- docs/grid-functionalities/infinite-scroll.md
- examples/vite-demo-vanilla-bundle/src/app-routing.ts
- examples/vite-demo-vanilla-bundle/src/app.html
- examples/vite-demo-vanilla-bundle/src/examples/example26.ts
- examples/vite-demo-vanilla-bundle/src/examples/example27.html
- examples/vite-demo-vanilla-bundle/src/examples/example28.html
- examples/vite-demo-vanilla-bundle/src/examples/example28.ts
- test/cypress/e2e/example26.cy.ts
- test/cypress/e2e/example28.cy.ts
> feat: add Infinite Scroll with local JSON data

- packages/common/src/core/slickGrid.ts
- packages/common/src/interfaces/gridOption.interface.ts
should fix failure of PR #1639 that updates dependencies
> fix: add missing TrustedHTML type

- packages/common/src/extensions/__tests__/slickCellExternalCopyManager.spec.ts
- packages/common/src/extensions/slickCellExternalCopyManager.ts
- test/vitest.config.mts
@zewa666 oops it looks like I merged the PR a little too early, the code below is not being covered. I did add coverage for the first line but the condition below is not covered. It actually looks like it's not even possible to go into the `if` condition, because the `addRows` variable is assigned to `0` and so how can it even go into the `if` condition?
is the code shown below still needed?
> chore: add SlickCellExternalCopyManager test coverage

- packages/common/src/core/slickGrid.ts
Performance optimisation from O(n square) to O(n)
> perf: Optimize SlickGrid handleSelectedRangesChanged by using Set

- examples/vite-demo-vanilla-bundle/src/material-styles.scss
- packages/common/src/styles/_variables-theme-material.scss
- packages/common/src/styles/_variables-theme-salesforce.scss
- packages/common/src/styles/_variables.scss
- more fixes for ms-select on selected filters, more specifically the border/box-shadow were different compare to other form inputs and now they are fully aligned with the others (also tested in Bootstrap as well)
> fix: more ms-select Dark Mode styling fixes

- packages/vanilla-bundle/src/components/slick-vanilla-grid-bundle.ts
- the handler was the same for the collection observer and the collection setter
> chore: remove duplicate columnDefinitionsChanged handler

- frameworks/slickgrid-vue/package.json
- frameworks/slickgrid-vue/scripts/changelog.mjs
- frameworks/slickgrid-vue/scripts/child-process.mjs
- frameworks/slickgrid-vue/scripts/fs-utils.mjs
- frameworks/slickgrid-vue/scripts/git-utils.mjs
- frameworks/slickgrid-vue/scripts/npm-utils.mjs
- frameworks/slickgrid-vue/scripts/release.mjs
- pnpm-lock.yaml
- add some NodeJS npm release script until our next major version that will eventually use Lerna-Lite to release
> chore: add temp npm release script for Slickgrid-Vue

- frameworks/slickgrid-vue/package.json
- frameworks/slickgrid-vue/vite.config.mts
> fix(vue): use dts w/Rollup to fix types & pass "are the types wrong"

- demos/vue/package.json
- demos/vue/src/components/Example03.vue
- demos/vue/src/components/jsonp.ts
- examples/vite-demo-vanilla-bundle/package.json
- examples/vite-demo-vanilla-bundle/src/examples/example04.ts
- examples/vite-demo-vanilla-bundle/src/examples/jsonp.ts
- pnpm-lock.yaml
- rewrite fetch-jsonp as ESM but only locally since this is only used for demo purposes
> chore: localize fetch-json to avoid importing old CJS package

- packages/common/src/core/slickGrid.ts
- refactor from code that comes from previously closed PR #1843, that previous PR was closed but the code refactoring does make sense since it's good way to remove duplicate code
> refactor: externalize duplicate code into separate function

- packages/common/package.json
- packages/excel-export/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Upgrade both of these dependencies (that I also manage) to v4.0.0
- excel-builder-vanilla@4.0.0
- multiple-select-vanilla@4.0.0
> chore(deps): upgrade Excel-Builder-Vanilla & Ms-Select-Vanilla to v4.0

- packages/common/src/extensions/__tests__/slickCellExternalCopyManager.spec.ts
- packages/common/src/extensions/slickCellExternalCopyManager.ts
- since SlickGrid predate modern browsers, when IE6 was still a thing, it was originally creating a temp textarea (that was hidden) to copy text. However nowadays, `navigator.clipboard` is widely available in all browsers.
- Note that using the `clipboard` API requires the end user to accept/permit the use of clipboard
> feat(copy)!: use browser `clipboard` API instead of using textarea

- packages/common/src/core/slickGrid.ts
- let's ignore some SlickGrid lines to be full 100% coverage which is easier to detect if it goes below 100% in future PR
> chore: skip some unit tests line to be at 100% coverage

- demos/react/package.json
- demos/vue/package.json
- frameworks/slickgrid-react/package.json
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- any dependency that is declared in multiple packages should be moved to the global catalog
> chore(deps): move `globals` dependency to catalog

- packages/common/src/core/__tests__/slickGrid.spec.ts
- packages/common/src/core/slickGrid.ts
fixes #2034 
I'm not sure if it fixes entirely the issue mentioned in #2034 but it surely helps and I'm not expecting more code change for that issue anyway, so hopefully that's enough
> fix(core): stopPropagation to avoid browser scrolling, fixes #2034

- packages/common/src/filters/__tests__/compoundSliderFilter.spec.ts
- packages/common/src/filters/sliderFilter.ts
- packages/common/src/styles/_variables.scss
- packages/common/src/styles/slick-plugins.scss
- slider border wasn't following Bootstrap form-control border color
- add couple of missed editor border colors in dark mode
> fix(styling): a few more styling fixes for light/dark themes

- packages/common/src/core/slickGrid.ts
in some cases when we had a grid with a `frozenColumn` (pinning) defined and then on the right section, we scroll a bit on the right and then if we changed the column header reorder it sometime cause a bug that the column header titles didn't align with the data (the titles was scrolled back to `scrollLeft: 0` while the data itself stayed at the same scroll position causing the misalignment). So to avoid such issues, we can simply scroll to the same X coordinate which we had before executing the action (I moved some internal code into a now public function named `scrollToX()` that we now call after the header title reordering is finished.
> fix: column header reorder should keep scroll position even frozen grid
